### PR TITLE
Loading modal when returning from OcenAudio (OT-852)

### PR DESCRIPTION
**Pull request by darrellcolehill**
Pushes the logic for processing data on verse/chapter edit to a different thread so the UI can show the loading modal while data is being processed. 

Removed ChapterReturnFromPluginEvent and instead just directly call the onChapterReturnFromPlugin method. onChapterReturnFromPlugin then fires PluginClosedEvent once the data processed. 

I am not crazy about this approach, but the only way I could think of keeping the event and showing the modal on the PluginOpenedPage is by not unsubscribing from ChapterReturnFromPluginEvent on NarrationPage un-dock, but that seems like a recipe for memory leaks.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096)

### CODE REVIEW

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @darrellcolehill and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 155 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096#-Nu_BjeR1S9WQqIr4Psb:-Nu_BjeR1S9WQqIr4Psc:b-ojgjj2) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/d0da8def25b59ddffa74c9076d5528337ad4fd31/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L155)):*
> ```Kotlin
>     }
> 
>     fun loadFromSelectedChapterFileTask(): Completable {
> ```

adding "Task" to the method name in the context of this class introduces inconsistency. Let's just remove it
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 156 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096#-Nu_BPPa5VeB0SVnBBmc:-Nu_BPPa5VeB0SVnBBmd:b6mnd0l) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/d0da8def25b59ddffa74c9076d5528337ad4fd31/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L156)):*
> ```Kotlin
> 
>     fun loadFromSelectedChapterFileTask(): Completable {
>         return Completable.create {
> ```

try this so you don't need to call onComplete() manually
```
Completable.fromAction {
     // op 
}
```
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 272 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096#-Nu_C4Fj5Y3OU56wOaOK:-Nu_C4Fk9pmpl5QKFZrP:bf5u5yy) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/d0da8def25b59ddffa74c9076d5528337ad4fd31/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L272)):*
> ```Kotlin
>     }
> 
>     fun onEditVerseTask(verseIndex: Int, editedFile: File): Completable {
> ```

same here for naming
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 274 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096#-Nu_C84549FY-5Pe7VMG:-Nu_C84549FY-5Pe7VMH:b-5rkvar) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/d0da8def25b59ddffa74c9076d5528337ad4fd31/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L274)):*
> ```Kotlin
>     fun onEditVerseTask(verseIndex: Int, editedFile: File): Completable {
> 
>         return Completable.create {
> ```

`fromAction { }`

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 155 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096#-Nu_BjeR1S9WQqIr4Psb:-Nu_DDW24olgFbmt97bZ:b-hfghm4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/d0da8def25b59ddffa74c9076d5528337ad4fd31/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L155)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

adding "Task" to the method name in the context of this class introduces inconsistency. Let's just remove it
</blockquote></details>

Sounds good
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 156 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096#-Nu_BPPa5VeB0SVnBBmc:-Nu_DVyz6cHNOHhb6uXq:bki0060) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/d0da8def25b59ddffa74c9076d5528337ad4fd31/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L156)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

try this so you don't need to call onComplete() manually
```
Completable.fromAction {
     // op 
}
```
</blockquote></details>

Thanks for pointing that out! That is much cleaner! 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 272 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096#-Nu_C4Fj5Y3OU56wOaOK:-Nu_DQdX74yGyl8-gTvB:b-hfghm4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/d0da8def25b59ddffa74c9076d5528337ad4fd31/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L272)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

same here for naming
</blockquote></details>

Sounds good

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096#-:-NueQNj1D7JYQdGTLULK:bnfp4nl)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @darrellcolehill)

**Review by AnonymousWalker — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1096)* status: all files reviewed, 4 unresolved discussions (waiting on @darrellcolehill)

**Pull request merged**
