### PR TITLE
Verse markers layer

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783)

### CODE REVIEW

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarker.kt` line 26 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783#-NahOe3y1JmWNvGtwz44:-NahOe3y1JmWNvGtwz45:bkb4b22) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c4c718990ee1273c11c114495f131ce8d6e8d554/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarker.kt#L26)):*
> ```Kotlin
>     val verseIndexProperty = SimpleIntegerProperty()
>     val labelProperty = SimpleStringProperty()
>     val canBeMovedProperty: BooleanBinding = verseIndexProperty.greaterThan(0)
> ```

We probably should go ahead and allow them all to be movable.

Ultimately, we foresee a future where additional markers, such as the Chapter Title/Book Title,  could be added, which would be content which precedes the first verse. 

(this would need to be updated in the marker app in the future as well, but let's just take care of it here for now)
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt` line 160 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783#-NahNjPEEhdpkW4uPzLF:-NahNjPEEhdpkW4uPzLG:b-95i1lb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c4c718990ee1273c11c114495f131ce8d6e8d554/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt#L160)):*
> ```Kotlin
>     }
> 
>     private fun absolutePositionToRelative(verse: VerseNode): Pair<Int, Int> {
> ```

Don't leak abstractions. The whole concept of absolute and relative positions should never leave the ChapterRepresentation class, that's the entire purpose of encapsulation and abstraction- to isolate the place where these quirks exist.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt` line 171 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783#-NahLxEE0PTzcg2JGF2q:-NahLxEE0PTzcg2JGF2r:b-u6qj8y) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c4c718990ee1273c11c114495f131ce8d6e8d554/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt#L171)):*
> ```Kotlin
>     private fun getVerseLabel(verse: VerseNode): String {
>         val index = markers.indexOf(verse)
>         return (index + 1).toString()
> ```

Let's use VerseMarkers here, not VerseNode; let the VerseNode be package internal to the ChapterRepresentation. 

We can read VerseMarkers out of an existing audio file using OratureAudioFile instead of AudioFile. OratureAudioFile has a getMarkers<VerseMarker>() method. 

Additionally, we should get Verses from whatever is providing us the text. If this is from Chunks, fine, but we need start and end info. Verse numbers can't be just index + 1 because some GLs have verse bridges.

The VerseMarker class takes in the start verse and end verse (end should be the same as start unless it's a bridge). The formattedLabel is what will get written to the file ("orature-vm-#") while the label is what you will wish to return here (which, will be the verse number or verse range)

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarker.kt` line 26 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783#-NahOe3y1JmWNvGtwz44:-NakMzi8CEHMZZe6N93w:b-8jqvft) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c4c718990ee1273c11c114495f131ce8d6e8d554/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarker.kt#L26)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

We probably should go ahead and allow them all to be movable.

Ultimately, we foresee a future where additional markers, such as the Chapter Title/Book Title,  could be added, which would be content which precedes the first verse. 

(this would need to be updated in the marker app in the future as well, but let's just take care of it here for now)
</blockquote></details>

This is only not to allow the first marker to be moved. Not the first verse. So it could be chapter marker or whatever that goes first.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt` line 160 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783#-NahNjPEEhdpkW4uPzLF:-NakP5y51Z8Cu93HcJu6:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c4c718990ee1273c11c114495f131ce8d6e8d554/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt#L160)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Don't leak abstractions. The whole concept of absolute and relative positions should never leave the ChapterRepresentation class, that's the entire purpose of encapsulation and abstraction- to isolate the place where these quirks exist.
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt` line 171 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783#-NahLxEE0PTzcg2JGF2q:-NakQ-D13ae7BY2LrvDq:b-rai44q) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c4c718990ee1273c11c114495f131ce8d6e8d554/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt#L171)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Let's use VerseMarkers here, not VerseNode; let the VerseNode be package internal to the ChapterRepresentation. 

We can read VerseMarkers out of an existing audio file using OratureAudioFile instead of AudioFile. OratureAudioFile has a getMarkers<VerseMarker>() method. 

Additionally, we should get Verses from whatever is providing us the text. If this is from Chunks, fine, but we need start and end info. Verse numbers can't be just index + 1 because some GLs have verse bridges.

The VerseMarker class takes in the start verse and end verse (end should be the same as start unless it's a bridge). The formattedLabel is what will get written to the file ("orature-vm-#") while the label is what you will wish to return here (which, will be the verse number or verse range)
</blockquote></details>

OratureAudioFile doesn't have verse markers if it's a PCM file.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt` line 160 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783#-NahNjPEEhdpkW4uPzLF:-Nalc_8d0zC7G9j-Qda0:b-g8x2gi) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c4c718990ee1273c11c114495f131ce8d6e8d554/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt#L160)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

so then the variable names relStart/relEnd make no sense here in this file and function
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt` line 171 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783#-NahLxEE0PTzcg2JGF2q:-NalcFA5DL1sxfQk5F_j:buw4cea) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c4c718990ee1273c11c114495f131ce8d6e8d554/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt#L171)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

OratureAudioFile doesn't have verse markers if it's a PCM file.
</blockquote></details>

Cool, then it won't give any markers when you ask for them and you know to load them from the serialized Narration.

But it will give you markers if you're loading a chapter wav/mp3 file from a previous instance that was finalized or importing a chapter audio file.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt` line 171 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/783#-NahLxEE0PTzcg2JGF2q:-NapUjN7AvaCCaw9a1AO:b712gxu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c4c718990ee1273c11c114495f131ce8d6e8d554/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt#L171)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Cool, then it won't give any markers when you ask for them and you know to load them from the serialized Narration.

But it will give you markers if you're loading a chapter wav/mp3 file from a previous instance that was finalized or importing a chapter audio file.
</blockquote></details>

Well, at first, narration doesn't work with wav/mp3 files. And if there is a chapter wav/mp3 file, it will convert it to pcm and will work with pcm only. Second, VerseNode is the source of the narration, every functionality is bound to it. If you want to use VerseMarker instead, it means that I have to start over and rewrite narration staff from zero. Unless you know how to do it easily. So instead of throwing puzzle hints, please give me the right solution. I can't read your mind.

**Pull request closed without merging**
