### PR TITLE
Reset take recording

### PR DESCRIPTION
**Pull request by AnonymousWalker**
No record
image
After record
image
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/602)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
Design approved

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/602)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/recorderapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/recorder/app/viewmodel/RecorderViewModel.kt` line 48 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/602#-N4Y5RK0DrA7I2mjdru3:-N4Y5RK0DrA7I2mjdru4:b-6l2xh3) ([raw file](https://github.com/bible-translation-tools/orature/blob/ab98d1397e268f7718958a02f0b7e8d40641ad2c/jvm/recorderapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/recorder/app/viewmodel/RecorderViewModel.kt#L48)):*
> ```Kotlin
> 
>     val targetFile = File(parameters.named["wav"])
>     var tempTake = createTempRecordingTake()
> ```

I would move initializing these variables (tempTake, wavAudio and writer) to a function to reduce code duplication.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/602)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[`jvm/recorderapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/recorder/app/viewmodel/RecorderViewModel.kt` line 48 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/602#-N4Y5RK0DrA7I2mjdru3:-N4bM4Nr02Rpjz0TSgV8:b-7bgh0h) ([raw file](https://github.com/bible-translation-tools/orature/blob/ab98d1397e268f7718958a02f0b7e8d40641ad2c/jvm/recorderapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/recorder/app/viewmodel/RecorderViewModel.kt#L48)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I would move initializing these variables (tempTake, wavAudio and writer) to a function to reduce code duplication. 
</blockquote></details>

Great point! Resolved.

**Review by mXaln — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/602)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

**Review by mXaln — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/602)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Comment by OpThomasPrime1** [comment]
Approved by QA (Thomas Oliver) on Windows, Linux, and Mac

**Pull request merged**
