### PR TITLE
Fixed tests

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/482)

### CODE REVIEW

**Review by AnonymousWalker — APPROVED** [review]

**Review by jsarabia — COMMENTED** [review]
Could you add a description of what was fixed and why?

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/482#-:-MtInlVm9DnaLSzpUEvE:bqbwt25)* status: 0 of 12 files reviewed, all discussions resolved

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/482)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModelTest.kt, line 45 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/482#-MtIoA9j9WNdiNddLvud:-MtIoA9j9WNdiNddLvue:bisl7cr) ([raw file](https://github.com/bible-translation-tools/orature/blob/3a3d080b9015823ead32477875a9d97efa944d45/jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModelTest.kt#L45)):*
> ```Kotlin
> 
> class BookWizardViewModelTest {
>     companion object {
> ```

Why are you guys putting stuff in companion objects for tests? Running tests shouldn't be making multiple instances of test classes?

Same with static methods.

**Review by mXaln — COMMENTED** [review]
Added @AfterClass methods for cleaning test suites.

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/482#-:-MtIpBRH1MnXoRA_AA1a:bt16cym)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @afterclass and @jsarabia)

___
*[jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModelTest.kt, line 45 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/482#-MtIoA9j9WNdiNddLvud:-MtIotIM5HxVIL75WtUT:b-nawaar) ([raw file](https://github.com/bible-translation-tools/orature/blob/3a3d080b9015823ead32477875a9d97efa944d45/jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModelTest.kt#L45)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why are you guys putting stuff in companion objects for tests? Running tests shouldn't be making multiple instances of test classes?

Same with static methods.
</blockquote></details>

Methods like @BeforeClass and @AfterClass are static and needs to be in a static class (companion object) as I understand

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/482)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @jsarabia)

___
*[jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModelTest.kt, line 45 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/482#-MtIoA9j9WNdiNddLvud:-MtIrMtw8_rFcOSSPQ9L:b-h0tila) ([raw file](https://github.com/bible-translation-tools/orature/blob/3a3d080b9015823ead32477875a9d97efa944d45/jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModelTest.kt#L45)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Methods like @BeforeClass and @AfterClass are static and needs to be in a static class (companion object) as I understand
</blockquote></details>

I see, okay!

**Pull request merged**
