### PR TITLE
Undo moving marker

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Previously we supported undo for addition & deletion of markers. Now we are able to undo moving/dragging markers back to the original position. On top of this, we use the undo stack to determine whether the markers are in a dirty state or not before saving/discarding the changes.

This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 3 of 129 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855)* status: 3 of 135 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt` line 351 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-NhTERgRDqnWpfiF8d50:-NhTERgRDqnWpfiF8d51:bzcegjx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a402eaf43e5161f709c808599b62aa1a335490b4/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt#L351)):*
> ```Kotlin
>     }
> 
>     private inner class Move(
> ```

Architecturally, this is kind of a mess- undo and redo should be in Domain classes- you're doing too much domain work in the viewmodel. The ViewModel needs to just be a middle man passing information back and forth and not doing real work itself.

So this inner class especially needs to be part of that Domain.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855)* status: 2 of 137 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt` line 351 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-NhTERgRDqnWpfiF8d50:-NhWeeU_4rxwa3M59foD:b-negxkm) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a402eaf43e5161f709c808599b62aa1a335490b4/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt#L351)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Architecturally, this is kind of a mess- undo and redo should be in Domain classes- you're doing too much domain work in the viewmodel. The ViewModel needs to just be a middle man passing information back and forth and not doing real work itself.

So this inner class especially needs to be part of that Domain.
</blockquote></details>

I've refactored it to common/. Also added the undoable interface

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 1 of 102 files at r5, 54 of 129 files at r7, 11 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855)* status: 68 of 137 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/IUndoable.kt` line 3 at r8](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-Nhl_QtD7PBw0SP16BCQ:-Nhl_QtD7PBw0SP16BCR:b-netfcn) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/082a1a9045936362f6fe7f522a1d25fdb6f68278/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/IUndoable.kt#L3)):*
> ```Kotlin
> package org.wycliffeassociates.otter.common.domain
> 
> interface IUndoable {
> ```

This might work for many things, but may not be a one size fits all solution either. I would recommend putting this specifically in whichever subdomain package you're putting translation stuff in.

After all, Narration has something like this (an interface with execute, undo, redo) and they all require parameters.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt` line 47 at r8](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-Nhl_j9o6cZfBvyxRDW0:-Nhl_j9o6cZfBvyxRDW1:b-4xw9vc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/082a1a9045936362f6fe7f522a1d25fdb6f68278/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt#L47)):*
> ```Kotlin
>     val markers = mutableListOf<ChunkMarkerModel>()
> 
>     var markerCount = 1
> ```

is this the total, or should this be a property which returns the size of markers?

**Comment by AnonymousWalker** [comment]
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt` line 47 at r8](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-Nhl_j9o6cZfBvyxRDW0:-NhldfMOEfmIAusFpxhI:b-45zoq6) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/082a1a9045936362f6fe7f522a1d25fdb6f68278/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt#L47)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

is this the total, or should this be a property which returns the size of markers?
</blockquote></details>

This is just to replace `markerCountProperty: BooleanProperty`. I see the value of it may not be always the same as `markers.size`

**Comment by AnonymousWalker** [comment]
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/IUndoable.kt` line 3 at r8](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-Nhl_QtD7PBw0SP16BCQ:-NhmNN0D0NZbq3EtxFDE:b58vxw) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/082a1a9045936362f6fe7f522a1d25fdb6f68278/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/IUndoable.kt#L3)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This might work for many things, but may not be a one size fits all solution either. I would recommend putting this specifically in whichever subdomain package you're putting translation stuff in.

After all, Narration has something like this (an interface with execute, undo, redo) and they all require parameters.
</blockquote></details>

I feel like this is a good and simple way to do it, especially at the highest level of abstraction. You can have the common parameters for each of these methods and pass them around on each invocation, or you can just send them once to the class constructor. I prefer the latter approach which allows the action class to store the state/data as class properties and to interact with them from inside the class.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855)* status: 68 of 137 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt` line 47 at r8](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-Nhl_j9o6cZfBvyxRDW0:-Ni-XRYI4CmAZpxneIHG:bc9mtg1) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/082a1a9045936362f6fe7f522a1d25fdb6f68278/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt#L47)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

This is just to replace `markerCountProperty: BooleanProperty`. I see the value of it may not be always the same as `markers.size`
</blockquote></details>

can we rename it to something less ambiguous?
Is this markersPlacedCount?

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855)* status: 68 of 137 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt` line 47 at r8](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-Nhl_j9o6cZfBvyxRDW0:-Ni-XhMMBMqBrdWlf8kZ:b-r0csgs) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/082a1a9045936362f6fe7f522a1d25fdb6f68278/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt#L47)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can we rename it to something less ambiguous?
Is this markersPlacedCount?
</blockquote></details>

Like, I don't know by the name if this is all of the markers in the verse (placed and unplaced), or just the ones placed so far?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855)* status: 67 of 137 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt` line 47 at r8](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-Nhl_j9o6cZfBvyxRDW0:-Ni-aqM345p6zSAn7711:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/082a1a9045936362f6fe7f522a1d25fdb6f68278/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/VerseMarkerModel.kt#L47)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Like, I don't know by the name if this is all of the markers in the verse (placed and unplaced), or just the ones placed so far?
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/855#-:-Ni_QRbF5TRrFLIpgyOQ:bnfp4nl)* status: 67 of 137 files reviewed, all discussions resolved

**Pull request merged**
