### PR TITLE
Notifications of Import/Export

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Creates toast notification snackbar. This could be used across the app where popup notification is needed

image

This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771)* status: 0 of 39 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/ProjectExporterCallback.kt` line 8 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771#-NZQfvNB8T_-Y-dQDAYe:-NZQfvNB8T_-Y-dQDAYf:b-fzairi) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/090fbfae4cb7f7709e4b7d8ed15c851b5707bac4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/ProjectExporterCallback.kt#L8)):*
> ```Kotlin
> interface ProjectExporterCallback {
>     /**
>      * Pushes a success notification to the GUI.
> ```

This is just a callback declaration to be executed on success. One implementation could give a visual notification of success, but nothing about the architecture requires it- it could just be logging data for example. 

Especially in the common package, referencing things GUI related doesn't make a lot of sense.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/system/FileSystemUtil.kt` line 6 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771#-NZQn3EQ0GDZZOGpk57Z:-NZQn3EQ0GDZZOGpk57_:b2locoy) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/090fbfae4cb7f7709e4b7d8ed15c851b5707bac4/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/system/FileSystemUtil.kt#L6)):*
> ```Kotlin
>  * Opens the given filePath in the current OS file manager/explorer.
>  */
> fun openInFilesManager(filePath: String) {
> ```

Could this instead be a method of the directory provider?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771)* status: 0 of 39 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/ProjectExporterCallback.kt` line 8 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771#-NZQfvNB8T_-Y-dQDAYe:-NZQpOQt6qqwJccYWe0n:b-x46l7g) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/090fbfae4cb7f7709e4b7d8ed15c851b5707bac4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/ProjectExporterCallback.kt#L8)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This is just a callback declaration to be executed on success. One implementation could give a visual notification of success, but nothing about the architecture requires it- it could just be logging data for example. 

Especially in the common package, referencing things GUI related doesn't make a lot of sense.
</blockquote></details>

Nice catch! I'd replace it with something more general.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/system/FileSystemUtil.kt` line 6 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771#-NZQn3EQ0GDZZOGpk57Z:-NZQw28F2A3p0x3g5ASQ:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/090fbfae4cb7f7709e4b7d8ed15c851b5707bac4/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/system/FileSystemUtil.kt#L6)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Could this instead be a method of the directory provider?
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771)* status: 0 of 43 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/DirectoryProvider.kt` line 227 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771#-NZSxBIMDc2Lbse7hp1K:-NZSxBIMDc2Lbse7hp1L:b-488u21) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/53aa043c9622590fac5106a4a4ecdbd65cec4040/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/DirectoryProvider.kt#L227)):*
> ```Kotlin
>         }
> 
>         val osName = System.getProperty("os.name").uppercase()
> ```

it would be better to use the existing member variable to be more consistent with the behavior elsewhere in this class, especially since the osName could be provided as a parameter.

**Review by mXaln — APPROVED** [review]
> Reviewed 36 of 39 files at r1, 7 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/DirectoryProvider.kt` line 227 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771#-NZSxBIMDc2Lbse7hp1K:-NZ_xRtS4ADuqKVN198i:bgh4p7o) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/53aa043c9622590fac5106a4a4ecdbd65cec4040/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/DirectoryProvider.kt#L227)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

it would be better to use the existing member variable to be more consistent with the behavior elsewhere in this class, especially since the osName could be provided as a parameter.
</blockquote></details>

sure. I was not aware of its existence.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/771#-:-NZgkHEj5u__eZwhTDeF:bnfp4nl)* status: 42 of 43 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
