### PR TITLE
Burrito Alignment Timing

### PR DESCRIPTION
**Pull request by jsarabia**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160)

### CODE REVIEW

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> Reviewed 4 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160)* status: 4 of 19 files reviewed, 12 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BiblicalReferences.kt` line 50 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Age_fDLKL1i6wnHFB:-O4Age_fDLKL1i6wnHFC:b-qrwhda) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BiblicalReferences.kt#L50)):*
> ```Kotlin
>                 val verseStart = verse.group(1)!!
>                 val verseEnd = if (verse.groupCount() == 2) verse.group(2) else null
>                 if (verseEnd != null) "orature-vm-${verseStart}-${verseEnd}" else "orature-vm-$verseStart"
> ```

separate lines would make the diff in if/else's body easier to read
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BiblicalReferences.kt` line 81 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Ah7Jk9qcC7Dzc-rKr:-O4Ah7Jl9qpardFaEi4e:b-wvruy7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BiblicalReferences.kt#L81)):*
> ```Kotlin
> 
>                 is VerseMarker -> {
>                     val label = if (marker.end != marker.start) "${marker.start}-${marker.end}" else "${marker.start}"
> ```

^same here
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 24 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AhAdIDzdOp6hvsDF0:-O4AhAdIDzdOp6hvsDF1:btn94ut) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L24)):*
> ```Kotlin
>     private val burritoTimingFile: File,
>     private val audioFile: File
> ) : CueMetadata {
> ```

I like the refactor of separating the AudioMetadata interface into two. However, I am not sure why this class inherits CueMetadata interface?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 67 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AhvHb31xKk9NmrXeJ:-O4AhvHc17a5-UFQkeA-:b-izu9au) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L67)):*
> ```Kotlin
>                 it as BookMarker
>                 it.bookSlug
>             }!!
> ```

this `!!` assumption defeats the purpose of `?.` operator above
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 73 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Ai6Mg4YQ6OqDS2hGR:-O4Ai6Mg4YQ6OqDS2hGS:b-j7012s) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L73)):*
> ```Kotlin
>                 it as ChapterMarker
>                 it.chapterNumber
>             }!!
> ```

^ same here for `!!` following `?.`
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 90 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AiOva2sYhfyXzHC7I:-O4AiOva2sYhfyXzHC7J:bu7s8pv) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L90)):*
> ```Kotlin
>         val alignment = if (burritoTimingFile.length() > 0) {
>             BurritoAudioAlignment.load(burritoTimingFile)
>         } else BurritoAudioAlignment.create(audioFile, burritoTimingFile)
> ```

else block { }
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 102 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AiSNK7SIGt-_sMIbj:-O4AiSNK7SIGt-_sMIbk:bylkj7g) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L102)):*
> ```Kotlin
>                         WebvttCueInfo(
>                             Cue.Builder()
>                                 .addMarkup("<c.u23003>$tag</c.u23003>")
> ```

This seems the only place that markup is used. Would you please add a short comment for it?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 138 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Aj03Z45eDIQpePjU4:-O4Aj03Z45eDIQpePjU5:b-ggh7zo) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L138)):*
> ```Kotlin
> 
> internal fun framesToUs(frames: Int): Long {
>     val us = (frames.toLong() * (1000000 / DEFAULT_SAMPLE_RATE.toDouble())).toLong()
> ```

- How about `1_000_000.0` replacing the `.toDouble()`? 

- Is `frames.toLong()` necessary in this case?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 22 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AkIEsCWh8RMfGwQEm:-O4AkIEsCWh8RMfGwQEn:bxdwg3l) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L22)):*
> ```Kotlin
>     @Synchronized
>     fun getMarkers(type: OratureCueType): List<AudioMarker> {
>         if (!cueMap.containsKey(type)) cueMap[type] = mutableListOf()
> ```

you could use `cueMap.getOrPut(mutableListOf())` for those check-and-set
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 29 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AjouT0PPp6qoOeMvx:-O4AjouT0PPp6qoOeMvy:bvndpeh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L29)):*
> ```Kotlin
>     fun getMarkers(): List<AudioMarker> = cueMap.values.flatten()
> 
>     fun addMarkers(type: OratureCueType, markers: List<AudioMarker>) {
> ```

do we need `@Synchronized` annotation for adding markers?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt` line 114 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AkvNfE6wxYUA9ZoES:-O4AkvNfE6wxYUA9ZoET:b-uxcqlm) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt#L114)):*
> ```Kotlin
>         moveUSFMFiles(burrito, usfmFilesByBook, inputAccessor, outputAccessor)
>         moveAudioFiles(burrito, chapterAudioByBook, inputAccessor, outputAccessor)
>         //updateTimingFiles(burrito, chapterAudioByBook, inputAccessor, outputAccessor)
> ```

is this commented for later use?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/ScriptureBurritoUtils.kt` line 210 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AlNTF276sRHPznJ5k:-O4AlNTF276sRHPznJ5l:b-gzypvv) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/ScriptureBurritoUtils.kt#L210)):*
> ```Kotlin
>                     }
>                 }
>                 if (outFile.extension in listOf("wav", "mp3")) {
> ```

```
AudioFileFormat.WAV.extension, AudioFileFormat.MP3.extension
```

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160)* status: 4 of 19 files reviewed, 12 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BiblicalReferences.kt` line 50 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Age_fDLKL1i6wnHFB:-O4QivWv060FNxvCejBC:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BiblicalReferences.kt#L50)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

separate lines would make the diff in if/else's body easier to read
</blockquote></details>

Done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BiblicalReferences.kt` line 81 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Ah7Jk9qcC7Dzc-rKr:-O4QixgSBwLIgaaByUiB:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BiblicalReferences.kt#L81)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

^same here
</blockquote></details>

Done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 24 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AhAdIDzdOp6hvsDF0:-O4QJhipBciW-DZv9GNH:bhod3w) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L24)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I like the refactor of separating the AudioMetadata interface into two. However, I am not sure why this class inherits CueMetadata interface?
</blockquote></details>

Because this Alignment Metadata format is what we're using to store timing (cues) in Scripture Burrito. So, this file gets cues and adds cues.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 90 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AiOva2sYhfyXzHC7I:-O4QizqoDc-GX953Vump:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L90)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

else block { }
</blockquote></details>

Done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 138 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Aj03Z45eDIQpePjU4:-O4QLV_g55wO-g4jk8k2:bktxvgt) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L138)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

- How about `1_000_000.0` replacing the `.toDouble()`? 

- Is `frames.toLong()` necessary in this case?
</blockquote></details>

I feel like I'd rather be explicit about the types to signify that we need it to NOT be integer division.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 22 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AkIEsCWh8RMfGwQEm:-O4QLqFv5SA5BJb0F5XS:b-5kvlxe) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L22)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

you could use `cueMap.getOrPut(mutableListOf())` for those check-and-set
</blockquote></details>

oh, that's great, thank you!!!
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 29 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AjouT0PPp6qoOeMvx:-O4Qj1v1EceDWNP3ZMGe:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L29)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

do we need `@Synchronized` annotation for adding markers?
</blockquote></details>

Done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt` line 114 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AkvNfE6wxYUA9ZoES:-O4QRzAjAEqMEdClsAxL:bcotdyp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt#L114)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

is this commented for later use?
</blockquote></details>

yeah, added a TODO
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/ScriptureBurritoUtils.kt` line 210 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AlNTF276sRHPznJ5k:-O4Qj3_YDtBpzMldXQPh:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/ScriptureBurritoUtils.kt#L210)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

```
AudioFileFormat.WAV.extension, AudioFileFormat.MP3.extension
```
</blockquote></details>

Done

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160)* status: 4 of 19 files reviewed, 16 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 33 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4QrvP134sSGdZjlsgU:-O4QrvP134sSGdZjlsgV:bwdry9j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/675dc9600302ddf411904bd1186db7f9005cfaa9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L33)):*
> ```Kotlin
>         if (!cueMap.containsKey(type)) cueMap[type] = mutableListOf()
>         cueMap[type]!!.addAll(markers)
>     }
> ```

this function could be just 
`cueMap.getOrPut(type) { mutableListOf() }.addAll(markers)`
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 39 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Qs30wAoWkmLRwStCw:-O4Qs30wAoWkmLRwStCx:b-jyb2et) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/675dc9600302ddf411904bd1186db7f9005cfaa9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L39)):*
> ```Kotlin
>         if (!cueMap.containsKey(type)) cueMap[type] = mutableListOf()
>         cueMap[type]!!.add(marker)
>     }
> ```

`cueMap.getOrPut(type) { mutableListOf() }.add(marker)`
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 49 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4QsNYO-tLb0evh5SgD:-O4QsNYO-tLb0evh5SgE:b64go2t) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/675dc9600302ddf411904bd1186db7f9005cfaa9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L49)):*
> ```Kotlin
>             cueMap[type]!!.clear()
>         }
>     }
> ```

`cueMap[type] = mutableListOf() `
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 55 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4QskmF-XVfjNvrjiX1:-O4QskmF-XVfjNvrjiX2:b-jgtqeo) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/675dc9600302ddf411904bd1186db7f9005cfaa9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L55)):*
> ```Kotlin
>         if (!cueMap.containsKey(entry.key)) cueMap[entry.key] = mutableListOf()
>         cueMap[entry.key]!!.addAll(entry.value)
>     }
> ```

`cueMap.getOrPut(entry.key) { mutableListOf() }.addAll(entry.value)`

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160)* status: 4 of 19 files reviewed, 16 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 102 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AiSNK7SIGt-_sMIbj:-O4QqEQD3VObA-wafMNN:bju34fw) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L102)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

This seems the only place that markup is used. Would you please add a short comment for it?
</blockquote></details>

Done via constant name
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 33 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4QrvP134sSGdZjlsgU:-O4RIT2f09GjKYdQqUgb:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/675dc9600302ddf411904bd1186db7f9005cfaa9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L33)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this function could be just 
`cueMap.getOrPut(type) { mutableListOf() }.addAll(markers)`
</blockquote></details>

Done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 39 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Qs30wAoWkmLRwStCw:-O4RISVC9jYiJeSNW0sC:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/675dc9600302ddf411904bd1186db7f9005cfaa9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L39)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`cueMap.getOrPut(type) { mutableListOf() }.add(marker)`
</blockquote></details>

Done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 49 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4QsNYO-tLb0evh5SgD:-O4RIRwY-vYi-MbhoKWX:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/675dc9600302ddf411904bd1186db7f9005cfaa9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L49)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`cueMap[type] = mutableListOf() `
</blockquote></details>

Done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt` line 55 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4QskmF-XVfjNvrjiX1:-O4RIRVY3Wtg5CTZEgiv:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/675dc9600302ddf411904bd1186db7f9005cfaa9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/OratureMarkers.kt#L55)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`cueMap.getOrPut(entry.key) { mutableListOf() }.addAll(entry.value)`
</blockquote></details>

Done

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160)* status: 4 of 19 files reviewed, 16 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 67 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4AhvHb31xKk9NmrXeJ:-O4RIfLF-KVMW8FoW7pp:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L67)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this `!!` assumption defeats the purpose of `?.` operator above
</blockquote></details>

Done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt` line 73 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-O4Ai6Mg4YQ6OqDS2hGR:-O4RIjhDEX8CXVFkaQBI:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1ece935a6ca502904f85a29e80299dcd994e85c4/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/metadata/BurritoAlignmentMetadata.kt#L73)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

^ same here for `!!` following `?.`
</blockquote></details>

Done

**Review by AnonymousWalker — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1160#-:-O4RlvY2BBttopox0kqs:bnfp4nl)* status: 4 of 19 files reviewed, 16 unresolved discussions

**Pull request merged**
