### PR TITLE
Export project as source audio

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 110 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2roQmp0LttfWRTd_Hz:-N2roQmp0LttfWRTd_I-:bmp82ko) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L110)):*
> ```Kotlin
>     }
> 
>     fun exportAsSource(
> ```

Can this be a separate Use Case?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 277 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2row_D3-j3KzMg66Ix:-N2row_D3-j3KzMg66Iy:bkai4r6) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L277)):*
> ```Kotlin
>     }
> 
>     private fun updateManifest(
> ```

updateManifest of what? and for what purpose?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 288 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2rp2JzCWzQLw-VtGOu:-N2rp2JzCWzQLw-VtGOv:burx487) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L288)):*
> ```Kotlin
>         ResourceContainer.load(rcFile).use { rc ->
>             // update manifest.yaml
>             ResourceContainer.load(sourceRCFile).use { sourceRC ->
> ```

this can be a function
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 305 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2rp5A11oz62i1gJF_L:-N2rp5A11oz62i1gJF_M:bsje1j9) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L305)):*
> ```Kotlin
>             }
>             // update media (.yaml + files)
>             val mediaManifest = let {
> ```

this can be another function
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 313 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2rp96EBf87_sr8dmBJ:-N2rp96EBf87_sr8dmBK:bqiqc18) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L313)):*
> ```Kotlin
>                 languageSlug, resourceSlug, projectSlug, "{chapter}", AudioFileFormat.MP3.extension
>             )
>             val mp3Media = Media(
> ```

sounds like we should do some abstraction here to add a filetype to the manifest, rather than hard coding mp3 and cue

**Review by jsarabia — COMMENTED** [review]
Also, honestly, if you could replace getting selected takes out of the workbook with getting it out of the database instead... This is directly related to the issue I'm already having to refactor around with the chunking code =|

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588#-:-N2s55t7EY8uF5Rv7DSO:bph0zgg)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 110 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2roQmp0LttfWRTd_Hz:-N2t6V7Q4M2xbcEAjbEB:bbceci8) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L110)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Can this be a separate Use Case?
</blockquote></details>

looks like we would end up having 3 different use cases: exportOratureFile, exportMp3 and exportAsSource, each in its own class. Or you have other suggestion? I see that they belong to project export use case

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 110 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2roQmp0LttfWRTd_Hz:-N2tDYek4nuCK5rOg9oM:b79abbg) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L110)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

looks like we would end up having 3 different use cases: exportOratureFile, exportMp3 and exportAsSource, each in its own class. Or you have other suggestion? I see that they belong to project export use case
</blockquote></details>

I think we can have a SourceProjectExporter just for this use case alone, as it's growing quite large now

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 110 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2roQmp0LttfWRTd_Hz:-N2v9X0yCmTuGVUkv2az:b-v3lcc2) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L110)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I think we can have a SourceProjectExporter just for this use case alone, as it's growing quite large now
</blockquote></details>

Sounds like a good time for an Exporter interface or abstract class then, and many implementations

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 277 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2row_D3-j3KzMg66Ix:-N2vsL8hBV0BEpp1v_R2:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L277)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

updateManifest of what? and for what purpose?
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 288 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2rp2JzCWzQLw-VtGOu:-N2vsJpSAyHF-38vXje9:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L288)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this can be a function
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 305 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2rp5A11oz62i1gJF_L:-N2vsJZw2oZAEJ5xNFV7:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L305)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this can be another function
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 313 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2rp96EBf87_sr8dmBJ:-N2vsJ7S9dDDsUxnXOLD:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L313)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

sounds like we should do some abstraction here to add a filetype to the manifest, rather than hard coding mp3 and cue
</blockquote></details>

Done.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt` line 110 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N2roQmp0LttfWRTd_Hz:-N2vy04T4VxRjBqs9k6V:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4a280ea9f7800e5c311de15006720630523c7ebc/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L110)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Sounds like a good time for an Exporter interface or abstract class then, and many implementations
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModelTest.kt` line 158 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N3-ioMh4KGQV5KCJQjI:-N3-ioMi2drC1q5CgqXm:bftin3t) ([raw file](https://github.com/bible-translation-tools/orature/blob/297e583f25a91c34200144dbdd308f845e1a43b2/jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModelTest.kt#L158)):*
> ```Kotlin
> 
>     @Test
>     fun exportWorkbook() {
> ```

Why is this test being deleted rather than maintained?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModelTest.kt` line 158 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/588#-N3-ioMh4KGQV5KCJQjI:-N34XCEpB_eb_DTq9LZR:b-flp7ax) ([raw file](https://github.com/bible-translation-tools/orature/blob/297e583f25a91c34200144dbdd308f845e1a43b2/jvm/workbookapp/src/test/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModelTest.kt#L158)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why is this test being deleted rather than maintained?
</blockquote></details>

Thanks for the catch, I temporarily removed it for debugging the feature and forgot to add it back.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/588#-:-N34h2Ns0o11VrnH86JT:bnfp4nl)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @jsarabia)

**Pull request merged**
