### PR TITLE
Exclude audio media when copying source

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Every time a project is created or ProjectFilesAccessor -> copySourceFiles() is called, it copies the whole source RC with all the audio files that were previously imported as source. This results in a large size of derived project with possibly unrelated source audio in it.
This PR excludes the audio/media in such RC and update the manifest respectively when copying source files to target project.

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/466)

### CODE REVIEW

**Review by mXaln — COMMENTED** [review]
There is one problem with this. If you import a resource container that includes media files, it will work fine. But if you uninstall the app (or delete Orature config), the media files won't be there to re-import. So restored project won't have the source audio.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/466#-:-MrX_zR87VLmbNwMGI2B:b-vizghm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by AnonymousWalker — COMMENTED** [review]
I have retained the source media for the project that is created and discard others', with effort to reduce the unnecessary amount of duplicated source audio among project RCs

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/466#-:-MrXs65433ed_pEAGStp:b-sjkzlf)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @jsarabia and @mXaln)

**Review by mXaln — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/466)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — CHANGES_REQUESTED** [review]
@mxaln This is the kind of issue that needs to be taken up with an product owner or someone filling that kind of role.

I don't agree that there is a problem with not including the media files, since they've always been separate from projects and can be added after the fact. Source audio is BIG. Our exporting is currently the only way to export or back up a project, which means many translators will be exporting many times. This is also the content they will ultimately upload to us. Which means, we want that data to be as slim as possible. 

You're right, if it's imported into an install of Orature that doesn't have source audio, they won't have source audio installed; but that is easily solved by either downloading it from Audio.Biel, getting a copy from another translator, etc.

I'd rather not make tons of copies of the source audio every time they back up or want to upload a project, even if it's the source audio pertaining to the project in question.

But again, we can discuss this with Glenn, Mark, Craig, etc and see what they think.

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/466#-:-Ms1NGWS2gUWJNLX19bp:b-m17r08)* status: all files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 226 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1Kh1e8le9o3_1YUnm:-Ms1Kh1e8le9o3_1YUnn:b-m37qpp) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L226)):*
> ```Kotlin
> 
>     private fun copySourceWithoutMedia(source: File, target: File) {
>         val ext = source.path.substringAfterLast(".")
> ```

you could (and should) just use source.extension
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 230 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1LlYWDW7pj7vQKqW6:-Ms1LlYWDW7pj7vQKqW7:b-jmgnj7) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L230)):*
> ```Kotlin
>             return
>         }
>         val extractedDir = createTempDirectory("otter").toFile()
> ```

don't create temp directories this way, use the directory provider. The reason is, with the directory provider temp dir, we will always clean that up. Temp directories created this way may not get cleaned up leaking large date if the app crashes before the directory is cleaned up. Then, it's up to the OS to hopefully purge its temp directories periodically but I don't want to rely on that.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 231 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1MEiuErp_baRsEx6G:-Ms1MEiuErp_baRsEx6H:bi1q2ls) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L231)):*
> ```Kotlin
>         }
>         val extractedDir = createTempDirectory("otter").toFile()
>         Zip4J(source).extractAll(extractedDir.path)
> ```

This is antithetical to OOP.

You're assuming the structure and format of a project. That's none of Orature's business.
Use the accessor functionality in the RC library.

We won't use only Resource Containers forever.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 261 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1MaQb5ZY2SOzDOm7O:-Ms1MaQb5ZY2SOzDOm7P:bnbt8i4) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L261)):*
> ```Kotlin
>             rc.writeMedia()
>         }
>         extractedDir.deleteRecursively()
> ```

Even if we were to continue using createTempDir, you always would want this in a finally block for a try/catch.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/RcConstants.kt, line 22 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1Mkuz4uuyZQsM3r01:-Ms1Mkuz4uuyZQsM3r02:b-vkrzz) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/RcConstants.kt#L22)):*
> ```Kotlin
> 
> internal object RcConstants {
>     const val PROJECT_CONTENT_DIR = "content"
> ```

Have you looked at where this was previously used EVERYWHERE and updated it? 
Were we previously writing media content to the content dir?
Does this need to get migrated in old projects?

If so, don't make this change in this PR. Make a separate branch pertaining solely to this issue, and be exhaustive about the solution.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/466)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 226 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1Kh1e8le9o3_1YUnm:-MsaVVz5DVViPPMlrCSE:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L226)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

you could (and should) just use source.extension
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 230 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1LlYWDW7pj7vQKqW6:-MsaVVojAbbmuzOa2DQi:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L230)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

don't create temp directories this way, use the directory provider. The reason is, with the directory provider temp dir, we will always clean that up. Temp directories created this way may not get cleaned up leaking large date if the app crashes before the directory is cleaned up. Then, it's up to the OS to hopefully purge its temp directories periodically but I don't want to rely on that.
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 231 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1MEiuErp_baRsEx6G:-MsaVWRhDGJNLiat7ICV:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L231)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This is antithetical to OOP.

You're assuming the structure and format of a project. That's none of Orature's business.
Use the accessor functionality in the RC library.

We won't use only Resource Containers forever.
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 261 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1MaQb5ZY2SOzDOm7O:-MsaVWv136uSIx1Bn7Tx:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L261)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Even if we were to continue using createTempDir, you always would want this in a finally block for a try/catch.
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/RcConstants.kt, line 22 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/466#-Ms1Mkuz4uuyZQsM3r01:-MsaVXIp9-7Xnp0vKv3e:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/06368486f78a1ac504b0a8be3d910dfd744a5c91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/RcConstants.kt#L22)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Have you looked at where this was previously used EVERYWHERE and updated it? 
Were we previously writing media content to the content dir?
Does this need to get migrated in old projects?

If so, don't make this change in this PR. Make a separate branch pertaining solely to this issue, and be exhaustive about the solution.
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/466#-:-MsftWYu3cYBkOPTf7zm:bnfp4nl)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
