### PR TITLE
Translation Final Review step

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862)

### CODE REVIEW

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862)* status: 0 of 140 files reviewed, 1 unresolved discussion

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationTake.kt` line 18 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862#-Nia4uqlDVi-3_PBDiV2:-Nia4uqlDVi-3_PBDiV3:b-4v1ael) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6101061e79ea302df2e88614e25444aee04564e8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationTake.kt#L18)):*
> ```Kotlin
> import javax.inject.Inject
> 
> class ChapterTranslationTake @Inject constructor(
> ```

if we have a better name for this domain class and its method, I'd love to change it

**Review by jsarabia — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862)* status: 0 of 144 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationTake.kt` line 18 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862#-Nia4uqlDVi-3_PBDiV2:-Niv2bIgAzhQn02nYOLw:b-qy5g7d) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6101061e79ea302df2e88614e25444aee04564e8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationTake.kt#L18)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

if we have a better name for this domain class and its method, I'd love to change it
</blockquote></details>

ChapterTranslationBuilder?

The class itself isn't a take after all

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862)* status: 0 of 144 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/ChunkingStep.kt` line 10 at r9](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862#-Niv2xTc-jrQeHTV8q7d:-Niv2xTc-jrQeHTV8q7e:b-cpp0xg) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/8ac0686560f664a88c6c2f02e52ff8f882b29fdc/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/ChunkingStep.kt#L10)):*
> ```Kotlin
>     KEYWORD_CHECK("keyword_check"),
>     VERSE_CHECK("verse_check"),
>     CHAPTER_REVIEW("final_review")
> ```

Should all references to "Final Review" be replaced with "Chapter Review" for consistency? Or vice versa?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862)* status: 0 of 144 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationTake.kt` line 18 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862#-Nia4uqlDVi-3_PBDiV2:-NivEFfa7jsjdXohPmJC:b-q71ta1) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6101061e79ea302df2e88614e25444aee04564e8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationTake.kt#L18)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

ChapterTranslationBuilder?

The class itself isn't a take after all
</blockquote></details>

Agreed, thanks!
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/ChunkingStep.kt` line 10 at r9](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862#-Niv2xTc-jrQeHTV8q7d:-NivEM5w-eKRYuNjyeIt:b-pkgs1b) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/8ac0686560f664a88c6c2f02e52ff8f882b29fdc/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/ChunkingStep.kt#L10)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Should all references to "Final Review" be replaced with "Chapter Review" for consistency? Or vice versa?
</blockquote></details>

Sounds good to me

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/862#-:-Nj8Y_PECVTGd7_90uHP:bnfp4nl)* status: 0 of 144 files reviewed, all discussions resolved

**Pull request merged**
