### PR TITLE
Dh chapter selector update

### PR DESCRIPTION
**Pull request by darrellcolehill**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860)

### CODE REVIEW

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt` line 15 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmAvJKE7iByZpdzCQ7:-NhmAvJKE7iByZpdzCQ8:b-7bn6jk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt#L15)):*
> ```Kotlin
> private const val GRID_COLUMNS = 5
> 
> class ChapterGrid(list: ObservableList<ChapterGridItemData>) : GridPane() {
> ```

Not super crazy about this being an ObservableList, but I couldn't think of another way to have the grid change when we navigate to a different book
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt` line 22 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmB5l8CTUr83F2Njzl:-NhmB5l8CTUr83F2Njzm:b-gmkygs) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt#L22)):*
> ```Kotlin
>         addClass("chapter-grid")
>         list.onChange {
>             Platform.runLater {
> ```

Not sure if this runLater will always run when I am expecting it to. The purpose of this is to have children in the grid cleared whenever the list changes.

This fixed the issue I was having where I started on Genesis (which showed all 50 chapters correctly), but then moved to Exodus and saw 50 chapter instead of 40. 
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt` line 23 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmBrj10j0Kzs26r595:-NhmBrj10j0Kzs26r596:b19qspq) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt#L23)):*
> ```Kotlin
>     init {
> 
>         chapterList.onChange {
> ```

Not crazy about this mapping happening in the View and not a ViewModel
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt` line 37 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmC-Q99dILnY2_HHSz:-NhmC-Q99dILnY2_HHT-:bke49vg) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt#L37)):*
> ```Kotlin
>             val chapterGrid = ChapterGrid(chapterGridItemList).apply {
>                 prefWidth = 500.0
>                 selectedChapterIndexProperty.addListener { _, old, new ->
> ```

When should/how should I free this listener? 
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 39 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmDqkZ6wqAwmefAz3d:-NhmDqkZ6wqAwmefAz3e:b-p66hib) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L39)):*
> ```Kotlin
>     private val popupMenu = ChapterGridMenu().apply {
>         chapterList.bind(viewModel.chapterList) { it }
>         onChapterSelectedProperty.set {
> ```

I am not a huge fan of having to set this property in the NarrationHeader. The problem I am trying to solve by doing this is "How do I call fire(OpenChapterEvent(chapter)) with the correct chapter?", but it feels a bit hacky and possibly prone to memory leaks. 
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 108 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmC7ooAH3IHahUN5uf:-NhmC7ooAH3IHahUN5ug:b-tqvle9) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L108)):*
> ```Kotlin
>         }
> 
>         viewModel.chapterGridMenuOpenProperty.addListener { _, old, new ->
> ```

I was thinking that this should belong in the ViewModel, but that also seems weird because that would require the ViewModel to be aware of the popup.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @darrellcolehill)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt` line 15 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmAvJKE7iByZpdzCQ7:-Nhmmo_867EiRumgunqR:b1ilcsd) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt#L15)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Not super crazy about this being an ObservableList, but I couldn't think of another way to have the grid change when we navigate to a different book
</blockquote></details>

this is one of the possible solutions. The other would be to just create a new ChapterGrid, which I originally intended that way since there may not be changes in chapters while the chapter selector grid is shown and updating the grid means we just clear all the children of it and re-insert new items.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt` line 22 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmB5l8CTUr83F2Njzl:-NhmnqMWB-nYV5RvqpD5:b-5bil) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt#L22)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Not sure if this runLater will always run when I am expecting it to. The purpose of this is to have children in the grid cleared whenever the list changes.

This fixed the issue I was having where I started on Genesis (which showed all 50 chapters correctly), but then moved to Exodus and saw 50 chapter instead of 40.
</blockquote></details>

I think using `runLater { }` in the UI (view) means we don't have other better choices to make the code "flow" in the expected order. With the list as an observable collection, you can try out this binding and see if it works. This does pretty much the same as `add(node, index % GRID_COLUMNS, index / GRID_COLUMNS)`



_Code snippet:_
```Kotlin
bindChildren(list) {
    val index = list.indexOf(it)
    StackPane().apply {
        // create chapter node here ...

        setConstraints(this, index % , index / )
    }
}
    
```
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt` line 23 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmBrj10j0Kzs26r595:-NhmrX4p2LTs2s5RvyXV:byrq2m7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt#L23)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Not crazy about this mapping happening in the View and not a ViewModel
</blockquote></details>

see below
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt` line 37 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmC-Q99dILnY2_HHSz:-Nhmrq--8o7nuRvM5ilw:b-xizzs6) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt#L37)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

When should/how should I free this listener?
</blockquote></details>

if you `fire(ChapterSelectedEvent(number))` from ChapterGrid where the node's action is set, you don't need it here.
Let the ViewModel take care of the lookup by chapter number.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt` line 27 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmqwN918CUcPNBegm0:-NhmqwN918CUcPNBegm1:b3bv10x) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/770dab7f5120a7a3e2eaff98cebf8ae8a9326a07/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt#L27)):*
> ```Kotlin
>         // Handle changes in showingProperty. Used to update completed icon for each chapter.
>         showingProperty().onChange { showing ->
>             updateChapterGridItemList()
> ```

or you can have a method that set the chapter list right before we show() the menu:



_Code snippet:_
```Kotlin
// on open menu
popupMenu.chapterListl.setAll(...) or .loadChapters(...)
popupMenu.show()
```
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt` line 61 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmqeDD21Scp6HeohtN:-NhmqeDD21Scp6HeohtO:bqknk3k) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/770dab7f5120a7a3e2eaff98cebf8ae8a9326a07/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt#L61)):*
> ```Kotlin
>             )
>         })
>     }
> ```

this mapping should be done in the ViewModel and we only need `chapterGridItemList` property here in the View.



_Code quote:_
```Kotlin
    private fun updateChapterGridItemList() {
        chapterGridItemList.setAll(chapterList.map {
            ChapterGridItemData(
                it.sort,
                SimpleBooleanProperty(it.hasSelectedAudio())
            )
        })
    }
```
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 39 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmDqkZ6wqAwmefAz3d:-Nhmse9C7JOy0W4n7tHc:bh4xwr6) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L39)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

I am not a huge fan of having to set this property in the NarrationHeader. The problem I am trying to solve by doing this is "How do I call fire(OpenChapterEvent(chapter)) with the correct chapter?", but it feels a bit hacky and possibly prone to memory leaks.
</blockquote></details>

you have the chapter number - ChapterGridItemData - to fire the event. It's like "Hey, whoever's listening, the user just clicked on chapter number '9'!". Feel free to let the VM do the heavier work of looking up the chapter
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 108 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-NhmC7ooAH3IHahUN5uf:-Nhmu2lt1FP46Wgxe-de:bepbotc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/666da67a8165b810be429272f82478c522859da3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L108)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

I was thinking that this should belong in the ViewModel, but that also seems weird because that would require the ViewModel to be aware of the popup.
</blockquote></details>

you can bring the body of this to line 89-91. We don't need to ask the VM to do the View's job if it can do on its own.



_Code snippet:_
```Kotlin
            setOnTitleClickedProperty {
                viewModel.setChapterGridOpen(!viewModel.chapterGridMenuOpenProperty.value)
            }
```

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860)* status: 0 of 10 files reviewed, 12 unresolved discussions (waiting on @darrellcolehill)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterSelector.kt` line 33 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-Ni4dmR8EzAcN983MpAl:-Ni4dmR8EzAcN983MpAm:b-ktxbzm) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/3cb85f91da019a097f62bb7f795d0e752d9e1d39/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterSelector.kt#L33)):*
> ```Kotlin
> class ChapterSelector : Control() {
>     val chapterTitleProperty = SimpleStringProperty()
>     val onTitleClickedProperty = SimpleObjectProperty<EventHandler<MouseEvent>>()
> ```

we should name the property something that is unambiguous. For example, `onChapterListOpenedProperty` or`onChapterSelectorOpenedProperty` would communicate better the purpose of this event handler property and someone who reads this code later won't have to trace it to understand what it actually does.

Additionally, for reusable purposes, please use ActionEvent or something common instead of MouseEvent. This will benefit us when the trigger action is not a mouse click but a key input.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt` line 17 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-Ni4d_uwAJO5vpQ7Yo_l:-Ni4d_uwAJO5vpQ7Yo_m:b-57cqui) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/3cb85f91da019a097f62bb7f795d0e752d9e1d39/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/popup/ChapterGridMenu.kt#L17)):*
> ```Kotlin
> class ChapterGridMenu : ContextMenu() {
> 
>     private val chapterGridItemList: MutableList<ChapterGridItemData> = listOf<ChapterGridItemData>().toMutableList()
> ```

= mutableListOf<>()
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 87 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-Ni4ipZy6Ki3FTPAuzNm:-Ni4ipZy6Ki3FTPAuzNn:b-1o75p4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/3cb85f91da019a097f62bb7f795d0e752d9e1d39/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L87)):*
> ```Kotlin
>                 setOnTitleClickedProperty {
> 
>                     popupMenu.updateChapterGrid(viewModel.chapterList.map { it })
> ```

your `viewModel.chapterList` (in NarrationHeaderViewModel) could be refactored to `ObservableList<ChapterGridItemData>` and you don't have to convert/map Chapter object to ChapterGridItemData inside updateChapterGrid() function which is part of the View. This process should be done in the ViewModel
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 188 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-Ni4k9HM0bsV45C3xlt2:-Ni4k9HM0bsV45C3xlt3:bjc0pjp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/3cb85f91da019a097f62bb7f795d0e752d9e1d39/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L188)):*
> ```Kotlin
> 
>         subscribe<OpenChapterEvent> {
>             viewModel.loadChapter(viewModel.chapterList[it.chapterNumber])
> ```

this "lookUp" should be done in the ViewModel. The view just calls loadChapter() and sends the argument(s) only. You can have an overload of loadChapter(_) that takes an Int

**Comment by AnonymousWalker** [comment]
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt` line 31 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-Ni4nQu60JpyAwLoEEBJ:-Ni4nQu79XcsxbEpQvgx:bn63628) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/3cb85f91da019a097f62bb7f795d0e752d9e1d39/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt#L31)):*
> ```Kotlin
>     }
> 
>     private fun addChaptersToGrid() {
> ```

thanks for moving it to a function

**Review by AnonymousWalker — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/860#-:-Nia2cLjBYQN6x44vmhd:bnfp4nl)* status: 0 of 12 files reviewed, 12 unresolved discussions (waiting on @darrellcolehill and @jsarabia)

**Pull request merged**
