### PR TITLE
Bring back #1096 dialog returning from ocenaudio

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Returning from ocenaudio will execute two major processes: append to scratch audio file and bounce audio

This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1119)

### CODE REVIEW

**Review by darrellcolehill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1119)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 684 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1119#-Nv3c5jc3g583XY-90d-:-Nv3c5jc3g583XY-90d0:b-1yr3k5) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5667c92d77b3c6cfd53abfe1bfa951d12c9e8ef0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L684)):*
> ```Kotlin
>             .doFinally {
>                 recordedVerses.setAll(narration.activeVerses)
>                 resetNarratableList()
> ```

I believe that the following lines is what causes the crash we experienced before. 

When I was bug hunting, I noticed that I was getting concurrent modification exceptions followed by an index out of bounds error, and I think it was because we call resetNarratableList here and on NarrationPage dock, so it was iterating over the narratableList while also modifying it. 



_Code snippet:_
```Kotlin
                recordedVerses.setAll(narration.activeVerses)
                resetNarratableList()
```

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1119)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @darrellcolehill)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 684 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1119#-Nv3c5jc3g583XY-90d-:-Nv3eY_K3uodH-8qk5nl:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5667c92d77b3c6cfd53abfe1bfa951d12c9e8ef0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L684)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

I believe that the following lines is what causes the crash we experienced before. 

When I was bug hunting, I noticed that I was getting concurrent modification exceptions followed by an index out of bounds error, and I think it was because we call resetNarratableList here and on NarrationPage dock, so it was iterating over the narratableList while also modifying it.
</blockquote></details>

Done.

**Review by darrellcolehill — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1119)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

**Review by darrellcolehill — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AnonymousWalker)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1119#-:-NvC9UYU0N4ITy77zSsm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AnonymousWalker)

**Pull request merged**
