### PR TITLE
Calculate estimated export file size

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952)

### CODE REVIEW

**Review by mXaln — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952)* status: all files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/AudioProjectExporter.kt` line 61 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952#-NmkyRgw7QL-ySkQv4Ej:-NmkyRgw7QL-ySkQv4Ek:blcyy3m) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1a5ae629c5af35f56e52ab9bf1d23ed24bbfbfe6/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/AudioProjectExporter.kt#L61)):*
> ```Kotlin
>     }
> 
>     override fun estimateExportSize(workbook: Workbook,chapterFilter: List<Int>): Long {
> ```

please put space between arguments
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/BackupProjectExporter.kt` line 124 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952#-NmkyZEL9L3ZiKJWRUO8:-NmkyZEL9L3ZiKJWRUO9:blcyy3m) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1a5ae629c5af35f56e52ab9bf1d23ed24bbfbfe6/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/BackupProjectExporter.kt#L124)):*
> ```Kotlin
>     }
> 
>     override fun estimateExportSize(workbook: Workbook,chapterFilter: List<Int>): Long {
> ```

please put space between arguments
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/SourceProjectExporter.kt` line 88 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952#-NmkzhgrAFlniHLQIZaY:-NmkzhgrAFlniHLQIZaZ:blcyy3m) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1a5ae629c5af35f56e52ab9bf1d23ed24bbfbfe6/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/SourceProjectExporter.kt#L88)):*
> ```Kotlin
>     }
> 
>     override fun estimateExportSize(workbook: Workbook,chapterFilter: List<Int>): Long {
> ```

please put space between arguments

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/AudioProjectExporter.kt` line 61 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952#-NmkyRgw7QL-ySkQv4Ej:-Nml9ksv7YtVpw0Jm1w5:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1a5ae629c5af35f56e52ab9bf1d23ed24bbfbfe6/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/AudioProjectExporter.kt#L61)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

please put space between arguments
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/BackupProjectExporter.kt` line 124 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952#-NmkyZEL9L3ZiKJWRUO8:-Nml9lAoBoluJMWD6VDy:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1a5ae629c5af35f56e52ab9bf1d23ed24bbfbfe6/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/BackupProjectExporter.kt#L124)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

please put space between arguments
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/SourceProjectExporter.kt` line 88 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952#-NmkzhgrAFlniHLQIZaY:-Nml9lTE6qsX8YFa_azR:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1a5ae629c5af35f56e52ab9bf1d23ed24bbfbfe6/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/SourceProjectExporter.kt#L88)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

please put space between arguments
</blockquote></details>

Done.

**Review by mXaln — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952#-:-NnB4pSp2wgpPxujKkWD:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/AudioProjectExporter.kt` line 68 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952#-NnB4SA4EhpW_tCmBjQO:-NnB4SA4EhpW_tCmBjQP:b-b61dla) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/af782a921416b04fd0af0ca4190217df338bc344/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/AudioProjectExporter.kt#L68)):*
> ```Kotlin
>                 when (AudioFileFormat.of(nextFile.extension)) {
>                     AudioFileFormat.MP3 -> size + nextFile.length()
>                     AudioFileFormat.WAV -> size + nextFile.length() / WAV_TO_MP3_COMPRESSED_RATE
> ```

presumably MP3 and WAV are swapped here
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/SourceProjectExporter.kt` line 95 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/952#-NnB4ixR9gHXk0Mdqa9j:-NnB4ixR9gHXk0Mdqa9k:b-ya81ng) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/af782a921416b04fd0af0ca4190217df338bc344/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/SourceProjectExporter.kt#L95)):*
> ```Kotlin
>                 when (AudioFileFormat.of(nextFile.extension)) {
>                     AudioFileFormat.MP3 -> size + nextFile.length()
>                     AudioFileFormat.WAV -> size + nextFile.length() / WAV_TO_MP3_COMPRESSED_RATE
> ```

Same as above

**Pull request merged**
