### PR TITLE
Reconstruct chapter representation on chapter take return from plugin

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879)

Fixes OT-733 and OT-749

### CODE REVIEW

**Review by darrellcolehill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 432 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879#-Niovk_DDCTtu43USET5:-Niovk_DDCTtu43USET6:b6jdmfg) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/8eae57b2ae3d5fc0916a1384961d2d3c555c2f60/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L432)):*
> ```Kotlin
>                         bytesWritten += toCopy
>                         position += toCopy
>                         framesToRead -= toCopy / frameSizeInBytes
> ```

This does make more sense, but I slightly worry how placing this in the try/catch will change rendering the waveform and the placement of markers. 
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 269 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879#-NiowxtB4Q8Sj8YiJuXV:-NiowxtB4Q8Sj8YiJuXW:bsu0cgr) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/8eae57b2ae3d5fc0916a1384961d2d3c555c2f60/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L269)):*
> ```Kotlin
>                 .subscribe(
>                     {
>                         chapterTakeProperty.set(it)
> ```

I definitely like setting chapterTakeProperty here. The only question I have is if I start making a chapter take of chapter 1, then quickly navigate to chapter 2 before createChapterTake is finished, will chapter 2 now have it's chapterTakeProperty set to the take of chapter 1?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @darrellcolehill and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 432 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879#-Niovk_DDCTtu43USET5:-NisqMrt6_NdkfjHVCX_:b-ds6agm) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/8eae57b2ae3d5fc0916a1384961d2d3c555c2f60/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L432)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

This does make more sense, but I slightly worry how placing this in the try/catch will change rendering the waveform and the placement of markers.
</blockquote></details>

Good point, but I'm not sure how it will change the markers and rendering. I just thought that if `System.arraycopy` throws an error, we should not update `bytesWritten`, `position` and `framesToRead` with potentially incorrect values. Maybe there should be better error handling here.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 269 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879#-NiowxtB4Q8Sj8YiJuXV:-Nisr05SDdCJsmEolM7h:bf9yr9l) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/8eae57b2ae3d5fc0916a1384961d2d3c555c2f60/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L269)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

I definitely like setting chapterTakeProperty here. The only question I have is if I start making a chapter take of chapter 1, then quickly navigate to chapter 2 before createChapterTake is finished, will chapter 2 now have it's chapterTakeProperty set to the take of chapter 1?
</blockquote></details>

That should not happen. For that reason I have added `chapterTakeBusyProperty`, to disable chapter selector and other controls, until chapter take is created. So a user won't be able to go to the other chapter, while this chapter take is creating.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @darrellcolehill and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 269 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879#-NiowxtB4Q8Sj8YiJuXV:-NitnrMu4HoNkxwhKmGx:b-rah8g1) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/8eae57b2ae3d5fc0916a1384961d2d3c555c2f60/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L269)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

That should not happen. For that reason I have added `chapterTakeBusyProperty`, to disable chapter selector and other controls, until chapter take is created. So a user won't be able to go to the other chapter, while this chapter take is creating.
</blockquote></details>

I've just noticed that my PR breaks some tests in `ChapterRepresntationTest`. I have to look at it.

**Review by darrellcolehill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 74 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879#-Nj7sc_UAP9pls0G3s9f:-Nj7sc_UAP9pls0G3s9g:b3ujypr) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/40be19ac31b22bb0ead4eb413af6d69865d83630/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L74)):*
> ```Kotlin
>         return chapter
>             .chunks
>             .take(1)
> ```

Not sure if we will always want to use the first take. Maybe make a constant and assign 1 to it.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @darrellcolehill and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 74 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/879#-Nj7sc_UAP9pls0G3s9f:-NjI_-369MLXq1q2Gzkl:b-2obukb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/40be19ac31b22bb0ead4eb413af6d69865d83630/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L74)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Not sure if we will always want to use the first take. Maybe make a constant and assign 1 to it.
</blockquote></details>

Sorry. This change comes from another branch that ended up here because of incorrectly merging with my branch. I have created another clean PR #887

**Pull request closed without merging**
