### PR TITLE
Optimize performance for Translation UI

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Pushes the non-UI code to Observables in View Models, so they can run asynchronously

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/881)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/881)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/PartialView.kt` line 12 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/881#-Nj8QhVO51U2CxSdSdbz:-Nj8QhVO51U2CxSdSdc-:b-e8nbj1) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/eb0f8883d1be43226233bddb05d979580ba98bf5/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/PartialView.kt#L12)):*
> ```Kotlin
>  * It is highly recommended to use this class instead of Fragment.
>  */
> abstract class PartialView : View()
> ```

This is just useless bloat since you're not adding additional functionality- it's just a View

You could have just typealias, but again, why add purposeless obfuscation? Just use View.

The ONLY difference between a Fragment and a View is scoping. View is Singleton. It's not that one is intended for smaller UI or anything like that. Our UI framework is TornadoFX. Our developers need to learn and understand TornadoFX rather than arbitrarily rename things to better fit our mental models of how it might map to some other UI framework that our team is not using. What makes sense to you from your past work may not make sense to someone else with a different work history. Our common language is TornadoFX, since that's the only UI Framework this project uses.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt` line 117 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/881#-Nj8TO_38E1skZf9l-g3:-Nj8TO_38E1skZf9l-g4:bvkch5q) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/eb0f8883d1be43226233bddb05d979580ba98bf5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt#L117)):*
> ```Kotlin
> 
>     fun dock() {
>         startAnimationTimer()
> ```

Timers probably belong in the View
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt` line 101 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/881#-Nj8T-UW5tXFTkrVyMM7:-Nj8T-UW5tXFTkrVyMM8:b-lcr01d) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/eb0f8883d1be43226233bddb05d979580ba98bf5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt#L101)):*
> ```Kotlin
>                 }
>                 add(waveform)
>                 val slider = createAudioScrollbarSlider().also { viewModel.slider = it }
> ```

I don't feel like the ViewModel should have a reference to a View, this feels like it goes against the MVVM pattern.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/881)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/PartialView.kt` line 12 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/881#-Nj8QhVO51U2CxSdSdbz:-Nj8tlOU7im-Q93OBytw:b-wapame) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/eb0f8883d1be43226233bddb05d979580ba98bf5/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/PartialView.kt#L12)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This is just useless bloat since you're not adding additional functionality- it's just a View

You could have just typealias, but again, why add purposeless obfuscation? Just use View.

The ONLY difference between a Fragment and a View is scoping. View is Singleton. It's not that one is intended for smaller UI or anything like that. Our UI framework is TornadoFX. Our developers need to learn and understand TornadoFX rather than arbitrarily rename things to better fit our mental models of how it might map to some other UI framework that our team is not using. What makes sense to you from your past work may not make sense to someone else with a different work history. Our common language is TornadoFX, since that's the only UI Framework this project uses.
</blockquote></details>

It's fine to have it noted somewhere in the repo, since the issue doesn't manifest itself in the documentation. I reverted the change here.

**Comment by AnonymousWalker** [comment]
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt` line 117 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/881#-Nj8TO_38E1skZf9l-g3:-Nj926g6-oGPsKtzpFPs:bsw9ar2) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/eb0f8883d1be43226233bddb05d979580ba98bf5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt#L117)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Timers probably belong in the View
</blockquote></details>

similar to VerseMarkerViewModel, I find that letting the VM manages starting/stopping the timer's state would be more appropriate

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/881#-:-Nj9W8wM4X56tA_UWv0F:bnfp4nl)* status: 0 of 23 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

**Pull request merged**
