### PR TITLE
Add logging to reactive streams

### PR DESCRIPTION
**Pull request by jsarabia**
Adds logging to onError and doOnError for reactive streams to give more feedback in the event of a crash

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/171)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 49 of 49 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/171)* status: all files reviewed, 13 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt, line 253 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRKCJ-EZySqudfXVpP:-MHRKCJ-EZySqudfXVpQ:b-108cjc) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L253)):*
> ```Kotlin
>                 {
>                     db.deleteTake(modelTake, it)
>                         .subscribe()
> ```

Add doOnError to db.deleteTake, since it's a rx completable?
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt, line 305 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRKPFU8m7nK6YhWlb7:-MHRKPFU8m7nK6YhWlb8:bz601o3) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L305)):*
> ```Kotlin
>                     content.selectedTake = it.value?.let { wbTake -> takeMap[wbTake] }
>                     db.updateContent(content)
>                         .subscribe()
> ```

Same as above. Add doOnError to db.updateContent, since it's a rx completable?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/AudioPluginRepository.kt, line 163 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRMzXY6opTRiyVWbXM:-MHRMzXY6opTRiyVWbXN:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/AudioPluginRepository.kt#L163)):*
> ```Kotlin
>                         .subscribeOn(Schedulers.io())
>                 }
>             }.doOnError { e ->
> ```

move .doOnError to the next line
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 284 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNKap5axeDgniApYv:-MHRNKap5axeDgniApYw:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L284)):*
> ```Kotlin
>                     "A collection matching slug: $slug and metadata: [$metadata] was not found."
>                 )
>             }.doOnError { e ->
> ```

move .doOnError to the next line
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 296 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNR1xC3iqH6xGdN24:-MHRNR1xC3iqH6xGdN25:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L296)):*
> ```Kotlin
>                 entity.sourceFk = newSource.id
>                 collectionDao.update(entity)
>             }.doOnError { e ->
> ```

move .doOnError to the next line
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 319 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNSfQ4XB9x3IUYuT4:-MHRNSfQ4XB9x3IUYuT5:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L319)):*
> ```Kotlin
>             .fromCallable {
>                 collectionDao.insert(collectionMapper.mapToEntity(collection))
>             }.doOnError { e ->
> ```

move .doOnError to the next line
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 331 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNTWi4UOt-XmgJOu_:-MHRNTWi4UOt-XmgJOua:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L331)):*
> ```Kotlin
>                 val newEntity = collectionMapper.mapToEntity(obj, entity.parentFk, entity.sourceFk)
>                 collectionDao.update(newEntity)
>             }.doOnError { e ->
> ```

move .doOnError to the next line
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 401 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNUz78fV6WLt7FmdH:-MHRNUz78fV6WLt7FmdI:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L401)):*
> ```Kotlin
>                     )
>                 }
>             }.doOnError { e ->
> ```

move .doOnError to the next line
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/LanguageRepository.kt, line 35 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNgks-I1UN1rkl1U9:-MHRNgks-I1UN1rkl1UA:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/LanguageRepository.kt#L35)):*
> ```Kotlin
>             .fromCallable {
>                 languageDao.insertAll(languages.map(mapper::mapToEntity))
>             }.doOnError { e ->
> ```

move .doOnError to the next line
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceMetadataRepository.kt, line 14 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRO5nB6u2sbCTdvkLA:-MHRO5nB6u2sbCTdvkLB:blgisdm) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceMetadataRepository.kt#L14)):*
> ```Kotlin
> import org.wycliffeassociates.otter.jvm.workbookapp.persistence.repositories.mapping.LanguageMapper
> import org.wycliffeassociates.otter.jvm.workbookapp.persistence.repositories.mapping.ResourceMetadataMapper
> import kotlin.math.log
> ```

Unused import
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt, line 77 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRP-om6fdI1X9I_gSB:-MHRP-om6fdI1X9I_gSC:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt#L77)):*
> ```Kotlin
>                     .fetchByContentId(content.id, includeDeleted)
>                     .map(this::buildTake)
>             }.doOnError { e ->
> ```

move .doOnError to the next line
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt, line 120 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRP1bB1FJVCj_XTwSK:-MHRP1bB1FJVCj_XTwSL:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt#L120)):*
> ```Kotlin
>                     markerDao.insert(markerEntity)
>                 }
>             }.doOnError { e ->
> ```

move .doOnError to the next line
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt, line 144 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRP2SI46tWPi1r28TL:-MHRP2SI46tWPi1r28TM:b-97eve5) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt#L144)):*
> ```Kotlin
>                     }
>                 }
>             }.doOnError { e ->
> ```

move .doOnError to the next line

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/171)* status: 43 of 49 files reviewed, 13 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/AudioPluginRepository.kt, line 163 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRMzXY6opTRiyVWbXM:-MHRUGU60CH7hu4d8LgN:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/AudioPluginRepository.kt#L163)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 284 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNKap5axeDgniApYv:-MHRUN8f59u_orR7p6op:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L284)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 296 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNR1xC3iqH6xGdN24:-MHRUNr32K4Sq0AA_Ad_:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L296)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 319 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNSfQ4XB9x3IUYuT4:-MHRUOXL6drRZC4DrwPb:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L319)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 331 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNTWi4UOt-XmgJOu_:-MHRUQ-E6r-Iy8Mq69gK:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L331)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt, line 401 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNUz78fV6WLt7FmdH:-MHRUWSM-TeVioyxg5a7:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L401)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/LanguageRepository.kt, line 35 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRNgks-I1UN1rkl1U9:-MHRUdQ9AWKZSGDojY8f:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/LanguageRepository.kt#L35)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceMetadataRepository.kt, line 14 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRO5nB6u2sbCTdvkLA:-MHRUh-00M2q4kYgZgSL:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceMetadataRepository.kt#L14)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

Unused import
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt, line 77 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRP-om6fdI1X9I_gSB:-MHRV4l-EK-zqICC-GgQ:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt#L77)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt, line 120 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRP1bB1FJVCj_XTwSK:-MHRV5IY3vBqiHDrDeJT:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt#L120)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt, line 144 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRP2SI46tWPi1r28TL:-MHRV71N9Of4dj9W5X_a:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/TakeRepository.kt#L144)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

move .doOnError to the next line
</blockquote></details>

Done.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/171)* status: 43 of 49 files reviewed, 13 unresolved discussions (waiting on @mXaln)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt, line 253 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRKCJ-EZySqudfXVpP:-MHRVVdwBVnyEJeOR2So:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L253)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

Add doOnError to db.deleteTake, since it's a rx completable?
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt, line 305 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/171#-MHRKPFU8m7nK6YhWlb7:-MHRVW7gD4lcRdV_jNoq:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/2dd50f94917c8976196acd4f6f8a85fcdf644c33/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L305)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

Same as above. Add doOnError to db.updateContent, since it's a rx completable?
</blockquote></details>

Done.

**Review by mXaln — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/171)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
