### PR TITLE
Fix Narration Teleprompter State Machine

### PR DESCRIPTION
**Pull request by jsarabia**
Actually model the narration states with their valid transitions, and apply them from transition actions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865)

### CODE REVIEW

**Review by darrellcolehill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt` line 43 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLRTQkAkWgqtBpwSxn:-NiLRTQkAkWgqtBpwSxo:b9vjju3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt#L43)):*
> ```Kotlin
>             for (i in 0 until index) {
>                 contexts[i].restore()
>                 if (contexts[i].state.type == TeleprompterItemState.RE_RECORD_DISABLED) {
> ```

Not sure what this condition is checking for. Unsure how we would go from RE_RECORDING_DISABLED state to a RE_RECORD state.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt` line 136 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLQYqMENBwfr7VO2zJ:-NiLQYqMENBwfr7VO2zK:b-jvk3bu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt#L136)):*
> ```Kotlin
> }
> 
> object SaveRecordingAction {
> ```

I feel like we need to account for when they record the last verse (i.e. all other list item state machines are in the re-recording state) in a chapter because currently, when I click save, I do not see the UI reflect that the chapter take has been created until I re-load the chapter after the take has been created.

I was having a similar issue with the Narration Options #863

**Review by darrellcolehill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt` line 43 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLRTQkAkWgqtBpwSxn:-NiLRTQkAkWgqtBpwSxo:b9vjju3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt#L43)):*
> ```Kotlin
>             for (i in 0 until index) {
>                 contexts[i].restore()
>                 if (contexts[i].state.type == TeleprompterItemState.RE_RECORD_DISABLED) {
> ```

Not sure what this condition is checking for. Unsure how we would go from RE_RECORDING_DISABLED state to a RE_RECORD state.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt` line 136 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLQYqMENBwfr7VO2zJ:-NiLQYqMENBwfr7VO2zK:b-jvk3bu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt#L136)):*
> ```Kotlin
> }
> 
> object SaveRecordingAction {
> ```

I feel like we need to account for when they record the last verse (i.e. all other list item state machines are in the re-recording state) in a chapter because currently, when I click save, I do not see the UI reflect that the chapter take has been created until I re-load the chapter after the take has been created.

I was having a similar issue with the Narration Options #863

**Review by darrellcolehill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt` line 43 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLRTQkAkWgqtBpwSxn:-NiLRTQkAkWgqtBpwSxo:b9vjju3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt#L43)):*
> ```Kotlin
>             for (i in 0 until index) {
>                 contexts[i].restore()
>                 if (contexts[i].state.type == TeleprompterItemState.RE_RECORD_DISABLED) {
> ```

Not sure what this condition is checking for. Unsure how we would go from RE_RECORDING_DISABLED state to a RE_RECORD state.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt` line 136 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLQYqMENBwfr7VO2zJ:-NiLQYqMENBwfr7VO2zK:b-jvk3bu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt#L136)):*
> ```Kotlin
> }
> 
> object SaveRecordingAction {
> ```

I feel like we need to account for when they record the last verse (i.e. all other list item state machines are in the re-recording state) in a chapter because currently, when I click save, I do not see the UI reflect that the chapter take has been created until I re-load the chapter after the take has been created.

I was having a similar issue with the Narration Options #863

**Review by darrellcolehill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 64 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLjzY_EtXUFyam_Iv7:-NiLjzY_EtXUFyam_Iv8:b-8tanfk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L64)):*
> ```Kotlin
> 
>     val totalVerses: List<AudioMarker>
>         get() = run {
> ```

this could be simply `get() {  ... }`
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateMachine.kt` line 24 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLnzX4B5rtQtxFYoVa:-NiLnzX4B5rtQtxFYoVb:b-z11dj2) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateMachine.kt#L24)):*
> ```Kotlin
>     }
> 
>     fun applyTransition(request: TeleprompterStateTransitions, requestIndex: Int): List<TeleprompterItemState> {
> ```

given your well-defined class name, this method could be simply named "transition" or "shift"
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt` line 3 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLpFdj3DFQV3X4vHEJ:-NiLpFdj3DFQV3X4vHEK:b-mcykhl) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt#L3)):*
> ```Kotlin
> package org.wycliffeassociates.otter.common.domain.narration.teleprompter
> 
> enum class TeleprompterStateTransitions {
> ```

should be singular (without 's) for this name
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 155 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLlkJg0VJWMidWmJG7:-NiLlkJg0VJWMidWmJG8:btyo9q1) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L155)):*
> ```Kotlin
>         subscribe<ResumeRecordingAgainEvent> {
>             viewModel.resumeRecording()
>             viewModel.handleEvent(it)
> ```

Could we let the View Model execute the toggle actions like pause/resume/toggle... inside `when (event) { }` statement? I feel like it would be nicer if the View just receives the event and delegates it to the VM, ideally, in a single call and let the View Model do the toggles.



_Code quote:_
```Kotlin
            viewModel.pauseRecording(it.index)
            viewModel.handleEvent(it)
        }.let { eventSubscriptions.add(it) }

        subscribe<PauseRecordAgainEvent> {
            viewModel.pauseRecording(it.index)
            viewModel.handleEvent(it)
        }.let { eventSubscriptions.add(it) }

        subscribe<ResumeRecordingEvent> {
            viewModel.resumeRecording()
            viewModel.handleEvent(it)
        }.let { eventSubscriptions.add(it) }

        subscribe<ResumeRecordingAgainEvent> {
            viewModel.resumeRecording()
            viewModel.handleEvent(it)
```

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 64 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLjzY_EtXUFyam_Iv7:-NiPb9Wd0rrMCxtD-XdZ:b4zshmm) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L64)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this could be simply `get() {  ... }`
</blockquote></details>

Oh, I didn't know that, thanks!!
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateMachine.kt` line 24 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLnzX4B5rtQtxFYoVa:-NiPbCmd6IF0jZNXyCJ3:b-t77xc3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateMachine.kt#L24)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

given your well-defined class name, this method could be simply named "transition" or "shift"
</blockquote></details>

agreed
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt` line 3 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLpFdj3DFQV3X4vHEJ:-NiPbGsDAJ0Rc16J-ZBV:b-t77xc3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateTransitions.kt#L3)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

should be singular (without 's) for this name
</blockquote></details>

agreed

**Comment by AnonymousWalker** [comment]
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 155 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLlkJg0VJWMidWmJG7:-NiX0yeo34_2_cao2OVo:b-jedm38) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L155)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Could we let the View Model execute the toggle actions like pause/resume/toggle... inside `when (event) { }` statement? I feel like it would be nicer if the View just receives the event and delegates it to the VM, ideally, in a single call and let the View Model do the toggles.
</blockquote></details>

ideally:
```
        subscribe<PauseRecordAgainEvent> {
            viewModel.handleEvent(it)
        }.let { eventSubscriptions.add(it) }

        subscribe<ResumeRecordingEvent> {
            viewModel.handleEvent(it)
        }.let { eventSubscriptions.add(it) }
```

**Review by mXaln — APPROVED** [review]
Great work on this telepropmpter state machine. I found some bugs in "record again" actions and state, so I have created a PR instead. https://github.com/Bible-Translation-Tools/Orature/pull/869

> Reviewed 11 of 11 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-:-NiZUNq_A-11Ej98PYMG:b2tsl0h)* status: all files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

**Review by darrellcolehill — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865)* status: all files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 155 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/865#-NiLlkJg0VJWMidWmJG7:-Nia6vnA-zEAIxXgRbxM:bz5r7wz) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cbb1a3d2e73399c9063a12788e0d1f8882f344ce/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L155)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

ideally:
        subscribe<PauseRecordAgainEvent> {
            viewModel.handleEvent(it)
        }.let { eventSubscriptions.add(it) }

        subscribe<ResumeRecordingEvent> {
            viewModel.handleEvent(it)
        }.let { eventSubscriptions.add(it) }
</blockquote></details>

Agreed, done

**Review by AnonymousWalker — APPROVED** [review]

**Pull request merged**
