### PR TITLE
Home page: Translation cards

### PR DESCRIPTION
**Pull request by AnonymousWalker**
The translation card components will replace the old ones

This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
follows #743

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 8 of 22 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744)* status: all files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/NewTranslationCard2.kt` line 15 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV-kmCd6fQAop9M4Z9S:-NV-kmCd6fQAop9M4Z9T:b8umv4t) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/aabc4a9ea229091a3f69a1966dbbae9e8614b555/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/NewTranslationCard2.kt#L15)):*
> ```Kotlin
> import tornadofx.FX.Companion.messages
> 
> class NewTranslationCard2(
> ```

Did you mean to rename it at some point? It has number 2 in the name
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard2.kt` line 20 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV-mmIG2GqnNCk4B9Pm:-NV-mmIH7I07LkXhyKff:bhaf72) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/aabc4a9ea229091a3f69a1966dbbae9e8614b555/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard2.kt#L20)):*
> ```Kotlin
> import java.text.MessageFormat
> 
> class TranslationCard2(
> ```

Same as above. I don't think that this is a good pattern of naming classes. Adding order numbers to the class or function names feels like a debug code.
___
*[`jvm/controls/src/main/resources/css/translation-card-2.css` line 1 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV-nhKKA6dyAZGbKyF_:-NV-nhKKA6dyAZGbKyFa:b-vq13vy) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/aabc4a9ea229091a3f69a1966dbbae9e8614b555/jvm/controls/src/main/resources/css/translation-card-2.css#L1)):*
> ```CSS
> .translation-card {
> ```

Just the file name, that I don't like

**Comment by AnonymousWalker** [comment]
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/NewTranslationCard2.kt` line 15 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV-kmCd6fQAop9M4Z9S:-NV-plWk9sJmU0VXviTv:bvdel6b) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/aabc4a9ea229091a3f69a1966dbbae9e8614b555/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/NewTranslationCard2.kt#L15)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Did you mean to rename it at some point? It has number 2 in the name
</blockquote></details>

Great question! Yes, I intentionally & temporarily named it that way so we will change when the original ___Card is deleted. Currently, I don't want to mess up the old ones until we finish all the components in Home page

**Review by mXaln — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744)* status: all files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744)* status: all files reviewed, 8 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ActiveTranslationCard.kt` line 15 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9jToD9ZRO-zWG4v1R:-NV9jToD9ZRO-zWG4v1S:beclzyr) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ActiveTranslationCard.kt#L15)):*
> ```Kotlin
> import java.text.MessageFormat
> 
> class ActiveTranslationCard(
> ```

If NewTranslationCard and CreateTranslationCard are in one source file, why isn't this in the same file with them?
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ActiveTranslationCard.kt` line 17 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9jjif2qqRoyLYFwx6:-NV9jjif2qqRoyLYFwx7:bqgs2vx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ActiveTranslationCard.kt#L17)):*
> ```Kotlin
> class ActiveTranslationCard(
>     sourceLanguage: String,
>     targetLanguage: String,
> ```

Why are the languages not accepted as properties here like the other cards?

(maybe one constructor could accept strings and set the properties?
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/NewTranslationCard2.kt` line 78 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9kQ2e0caj8whi7R4M:-NV9kQ2e0caj8whi7R4N:bo6pc04) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/NewTranslationCard2.kt#L78)):*
> ```Kotlin
> }
> 
> class CreateTranslationCard : VBox() {
> ```

Can we get an EventTarget extension function for this?
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCardWrapper.kt` line 26 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9l9a58vPM6OUvy1IE:-NV9l9a58vPM6OUvy1IF:b-yq34jk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCardWrapper.kt#L26)):*
> ```Kotlin
> 
>     init {
>         activeTranslationCard(sourceLanguage.name, targetLanguage.name, mode) {
> ```

could this just be accomplished by adding or removing CSS classes though? Or creating a base TranslationCard control with different skins for the differences in layouts, and swap between skins by changing the -fx-skin css property?
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/TranslationMode.kt` line 3 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9tkI17NktdYwZ1x7X:-NV9tkI17NktdYwZ1x7Y:bbpb6f4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/TranslationMode.kt#L3)):*
> ```Kotlin
> package org.wycliffeassociates.otter.jvm.controls.model
> 
> enum class TranslationMode(val titleKey: String) {
> ```

By having this in the jvm.controls package, this is only useful within the UI. However, this appears to be related to the Workbook/Project- what the intent/purpose of that workbook is. It seems therefore, to be domain related, and could be useful at some time beyond just the UI here.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744)* status: all files reviewed, 8 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ActiveTranslationCard.kt` line 15 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9jToD9ZRO-zWG4v1R:-NVA7LQj6--S2KEAvtHs:bjujajs) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ActiveTranslationCard.kt#L15)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

If NewTranslationCard and CreateTranslationCard are in one source file, why isn't this in the same file with them?
</blockquote></details>

I would put this together with TranslationCard as they are similar in nature (styling, too): both are to display the existing items. NewTranslationCard and CreateTranslationCard are good to stay together and away from the other cards.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ActiveTranslationCard.kt` line 17 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9jjif2qqRoyLYFwx6:-NVA89xI5dUjO8_mvFlA:b-n9lkg6) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ActiveTranslationCard.kt#L17)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why are the languages not accepted as properties here like the other cards?

(maybe one constructor could accept strings and set the properties?
</blockquote></details>

it's meant to render static content whereas the NewTranslationCard uses properties for dynamic values (language binds to user selection)
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCardWrapper.kt` line 26 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9l9a58vPM6OUvy1IE:-NVA6Sjd9c0Fh4yPIxuv:b-2ak9uo) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCardWrapper.kt#L26)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

could this just be accomplished by adding or removing CSS classes though? Or creating a base TranslationCard control with different skins for the differences in layouts, and swap between skins by changing the -fx-skin css property?
</blockquote></details>

I tried with toggling between css styles and that worked for most except the layout difference between horizontal and vertical arrangement.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/TranslationMode.kt` line 3 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9tkI17NktdYwZ1x7X:-NVA5mawAUJXTFIKNzZL:b-77z8wa) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/TranslationMode.kt#L3)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

By having this in the jvm.controls package, this is only useful within the UI. However, this appears to be related to the Workbook/Project- what the intent/purpose of that workbook is. It seems therefore, to be domain related, and could be useful at some time beyond just the UI here.
</blockquote></details>

Great catch! Yes, it's supposed to be in the common package.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744)* status: all files reviewed, 8 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/NewTranslationCard2.kt` line 78 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9kQ2e0caj8whi7R4M:-NVAYPul2-3_P_XGOCZB:b5e46lt) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/NewTranslationCard2.kt#L78)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Can we get an EventTarget extension function for this?
</blockquote></details>

does this sound a bit strange to use? 
```
createTranslationCard { 

}
```
compared to
```
add(
    CreateTranslationCard()
)
```

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744)* status: all files reviewed, 8 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCardWrapper.kt` line 26 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV9l9a58vPM6OUvy1IE:-NVAZ3z32Xi_IcptvhZb:b-ti6rz) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/055c395fd69f293fdf5c447cedc6ac9cd46560bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCardWrapper.kt#L26)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

I tried with toggling between css styles and that worked for most except the layout difference between horizontal and vertical arrangement.
</blockquote></details>

using skin would be even more clunky as it needs to create a skin every time we switch the boolean

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744)* status: all files reviewed, 8 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard2.kt` line 20 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV-mmIG2GqnNCk4B9Pm:-NVAZPzV4H6bHwMYFWF5:b-gf6jfq) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/aabc4a9ea229091a3f69a1966dbbae9e8614b555/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard2.kt#L20)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Same as above. I don't think that this is a good pattern of naming classes. Adding order numbers to the class or function names feels like a debug code.
</blockquote></details>

discussed
___
*[`jvm/controls/src/main/resources/css/translation-card-2.css` line 1 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-NV-nhKKA6dyAZGbKyF_:-NVAZMuQ0I9NSXvD6rvw:b-gf6jfq) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/aabc4a9ea229091a3f69a1966dbbae9e8614b555/jvm/controls/src/main/resources/css/translation-card-2.css#L1)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Just the file name, that I don't like
</blockquote></details>

discussed

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/744#-:-NW2E5Tj1AGXav8_JipX:bnfp4nl)* status: 14 of 22 files reviewed, 6 unresolved discussions (waiting on @mXaln)

**Pull request merged**
