### PR TITLE
Chunking view - Steps pane/wizard

### PR DESCRIPTION
**Pull request by AnonymousWalker**
image

This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/791)

### CODE REVIEW

**Review by mXaln — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Comment by AnonymousWalker** [comment]
image

**Review by mXaln — COMMENTED** [review]
> Reviewed 4 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/791)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/resources/css/chunking-page.css` line 12 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/791#-NbOU5Kc4iy00Qq52DNA:-NbOU5Kd7wK_4J_1anGR:b-z6dzes) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9bcaa18cc49782d4d1de386f3424c71d0646e02d/jvm/workbookapp/src/main/resources/css/chunking-page.css#L12)):*
> ```CSS
> 
> .chunking-step.completed .chunking-step__title {
>     -fx-text-fill: #82A93F;
> ```

I can see this repeated three time here. Can you move this to a color variable?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/791)* status: 11 of 15 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[`jvm/workbookapp/src/main/resources/css/chunking-page.css` line 12 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/791#-NbOU5Kc4iy00Qq52DNA:-NbPGC6DBeCbOkbWBbmZ:b-5z5zrh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9bcaa18cc49782d4d1de386f3424c71d0646e02d/jvm/workbookapp/src/main/resources/css/chunking-page.css#L12)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I can see this repeated three time here. Can you move this to a color variable?
</blockquote></details>

sure. I planned to have it done when we get to dark mode but seems like this is a quick fix

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/791#-:-Nbyzlfb4kHF1QalZtIT:bnfp4nl)* status: 9 of 15 files reviewed, 1 unresolved discussion (waiting on @mXaln)

**Pull request merged**
