### PR TITLE
Home Page 2

### PR DESCRIPTION
**Pull request by AnonymousWalker**
There will be a separate PR that replace the old UI components with the new one having number "2" suffix in their names.

This PR features the following:

- replacing the old home page with the new design.
- re-architecting the way projects are stored: now translations are "project groups" grouped by ProjectGroupKey. WorkbookDescriptor is effectively a summary version of the workbook (lite).
- creating a project group will pre-populate all the books for that collection (usually 66 books).

This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/753)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/753)* status: 0 of 40 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/collections/CreateProject.kt` line 69 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/753#-NWiIxoN5r4MBMwZLc_T:-NWiIxoN5r4MBMwZLc_U:bybx94c) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6593dc74bbe8f41c7afcbfa34b8d8d6f374bb2a5/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/collections/CreateProject.kt#L69)):*
> ```Kotlin
>         }
> 
>         // TODO: use mode from method argument instead
> ```

Should this get resolved before approving/merging?
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard2.kt` line 79 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/753#-NWiJTN5Ej1qN2EUHWcZ:-NWiJTN5Ej1qN2EUHWc_:b-bqukhe) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6593dc74bbe8f41c7afcbfa34b8d8d6f374bb2a5/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard2.kt#L79)):*
> ```Kotlin
>     }
> 
>     override fun hashCode(): Int {
> ```

Using a UI class as a map key and checking for equality sounds like a symptom of bad design?

Why are these overriden?

**Comment by AnonymousWalker** [comment]
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/collections/CreateProject.kt` line 69 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/753#-NWiIxoN5r4MBMwZLc_T:-NWiQZdt6VkI2T-SaxLB:b-r99063) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6593dc74bbe8f41c7afcbfa34b8d8d6f374bb2a5/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/collections/CreateProject.kt#L69)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Should this get resolved before approving/merging?
</blockquote></details>

this one is used by the importer, which isn't implemented at the moment of this PR.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/753)* status: 0 of 40 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard2.kt` line 79 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/753#-NWiJTN5Ej1qN2EUHWcZ:-NWltf2s3ThJpOwWeMTO:b-fjf0d0) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6593dc74bbe8f41c7afcbfa34b8d8d6f374bb2a5/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard2.kt#L79)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Using a UI class as a map key and checking for equality sounds like a symptom of bad design?

Why are these overriden?
</blockquote></details>

thanks for the catch, I changed to using ProjectGroupKey and those were supposed to be removed.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/753#-:-NWnRqHV9HqcTpcKph1V:bnfp4nl)* status: 0 of 40 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
