### PR TITLE
Dh narration relative verse refactor

### PR DESCRIPTION
**Pull request by darrellcolehill**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854)

### CODE REVIEW

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 483 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzJtY6E6l8cXlpZNEe:-NgzJtY7119ceX55rsVf:b-ygir0r) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L483)):*
> ```Kotlin
>             // relativeToAbsolute
>             val lockedVerse = lockToVerse.get()
>             val mappedSample = if(lockedVerse != CHAPTER_UNLOCKED) {
> ```

Not crazy about the name "mappedSample"
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 152 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzK53U4DU7-TrKpkqM:-NgzK53U4DU7-TrKpkqN:b-v3fdlz) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L152)):*
> ```Kotlin
> 
>     fun undo() {
>         lockedVerseIndex = null
> ```

Should really add a method in this class like "lockToVerse" that updates the variable here in this class, and calls ChapterRepresentationConnection.lockToVerse with the same value
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 271 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzKPVBCwVeIiavJKGk:-NgzKPVBCwVeIiavJKGl:b-z4d56m) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L271)):*
> ```Kotlin
>             chapterReaderConnection.start = range.first
>             chapterReaderConnection.end = range.last
>             seek(0)
> ```

Not crazy about the seek(0) because it is ambiguous and not clear that it is seeking the player and connection to 0 to get them both in the verse space, since we just locked to a new verse 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 444 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzKiZSAdd7yl7mUxQd:-NgzKiZSAdd7yl7mUxQe:b-h49eob) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L444)):*
> ```Kotlin
>         } else {
>             player.getLocationInFrames()
>         }
> ```

The logic assigning a value to loc is nearly identical to the logic in getLocationInFrames, but it does not account for uncommittedRecordedFrames. If there is reason to account for that when seeking to next/previous, then should use the getLocationInFrames method, if not, then I should break this portion of the logic into another method
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 467 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzL9Do9Ha3EkAt17aa:-NgzL9Do9Ha3EkAt17ab:b-33iz) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L467)):*
> ```Kotlin
>         } ?: chapterRepresentation.apply {
>             val lastFrame = absoluteToRelative(activeVerses.last().lastFrame())
>             seek(lastFrame)
> ```

Replaced this because the player could vary likely have another verse loaded into it, so seeking to the player's duration is not reliable. Instead, I changed it to just go to the last relative frame because that seems like a better default and it more explicit in what to do when handling cases where there is not verseMarker with a location greater than the location of the playhead.

**Review by jsarabia — CHANGES_REQUESTED** [review]
Please at least run the auto-format tool before submitting PRs.

Also, follow the formatting conventions for long lines. For example:
https://kotlinlang.org/docs/coding-conventions.html#wrap-chained-calls

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-:-Nh1kUmoEkePygrMdzVI:b62k21g)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @darrellcolehill)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 288 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-Nh1hfwZ7LzL6sY_qF70:-Nh1hfwZ7LzL6sY_qF71:b-4evjch) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L288)):*
> ```Kotlin
> 
> 
>         fun absoluteToRelative(absoluteFrame: Int) : Int {
> ```

please document these
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 483 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzJtY6E6l8cXlpZNEe:-Nh1idWu4Uq51aTcZ0Ew:b5dl6bo) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L483)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Not crazy about the name "mappedSample"
</blockquote></details>

at this point, the variable would be relativeChapterSample
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 152 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzK53U4DU7-TrKpkqM:-Nh1jCrt0ED_rQtUmtHk:bua6mvy) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L152)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Should really add a method in this class like "lockToVerse" that updates the variable here in this class, and calls ChapterRepresentationConnection.lockToVerse with the same value
</blockquote></details>

agreed, do that ;D
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 271 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzKPVBCwVeIiavJKGk:-Nh1jMN24rTBmEYlErGX:b-jna7b7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L271)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Not crazy about the seek(0) because it is ambiguous and not clear that it is seeking the player and connection to 0 to get them both in the verse space, since we just locked to a new verse
</blockquote></details>

I think I'm fine with it, because seek is a method of Narration, so the action is with the context of Narration.

It's NARRATION that's seeking, and it in turn seeks everything in it
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 286 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-Nh1jrmK-ySNpzmcdTp1:-Nh1jrmK-ySNpzmcdTp2:bhzp87x) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L286)):*
> ```Kotlin
> 
>         lockedVerseIndex = null
>         chapterReaderConnection.lockToVerse(lockedVerseIndex)
> ```

make an unlock chapter method, so you don't keep calling these two lines all over the place
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 444 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzKiZSAdd7yl7mUxQd:-Nh1kR_Q1w1hgq5ETa1n:brryx5r) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L444)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

The logic assigning a value to loc is nearly identical to the logic in getLocationInFrames, but it does not account for uncommittedRecordedFrames. If there is reason to account for that when seeking to next/previous, then should use the getLocationInFrames method, if not, then I should break this portion of the logic into another method
</blockquote></details>

Should seek next/seek previous be changed at all?

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 444 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-NgzKiZSAdd7yl7mUxQd:-Nh24bvB5pVxLnU7w-tj:b1gqy47) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/65526111fe98bd801c44ab5624d68798bb590eb0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L444)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Should seek next/seek previous be changed at all?
</blockquote></details>

At the moment yes. If the user played the verse prior to seeking to the next/previous verse, the ChapterReaderConnection will be locked to the verse and the player's location will be in the relative verse space. So if I didn't change the logic, and I clicked "next" after playing verse 5, it would likely take me to a position before verse 5 because the player's location is relative to verse 5. 

Since we don't know if the user has played the verse or not before clicking next/previous, I added the condition that makes sure the location is in the relative chapter space regardless. Then I unlock from the verse so everything is back in the relative chapter space.

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 410 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-Nh2Sxc-CSrHfwvrs1d4:-Nh2Sxc-CSrHfwvrs1d5:b-qpmqda) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6bef18ed1e8efab1c85cd638c97b369a6f516a91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L410)):*
> ```Kotlin
>     }
> 
>     fun seek(location: Int, unlockFromVerse: Boolean = false) {
> ```

Not crazy about this, but this mostly resolves the issues with scrolling after playing a verse.

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 157 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-Nh3CP_807KEdPtp01hd:-Nh3CP_807KEdPtp01he:b-g6qg3r) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/fa2a6e70f442ad41b261fdbcfc8c001e995e7df3/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L157)):*
> ```Kotlin
> 
>     fun undo() {
>         seek(getRelativeChapterLocation())
> ```

This fixes incorrect seek after undoing a verse marker action
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 164 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-Nh3CWBY3msrnaun9cv5:-Nh3CWBY3msrnaun9cv6:b-cnq6e9) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/fa2a6e70f442ad41b261fdbcfc8c001e995e7df3/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L164)):*
> ```Kotlin
> 
>     fun redo() {
>         seek(getRelativeChapterLocation())
> ```

This fixes incorrect seek after redoing a verse marker action
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 206 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-Nh3Ccfj6gVGgONlWX_M:-Nh3Ccfj6gVGgONlWX_N:br928pm) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/fa2a6e70f442ad41b261fdbcfc8c001e995e7df3/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L206)):*
> ```Kotlin
> 
>     fun onVerseMarkerMoved(verseIndex: Int, delta: Int) {
>         seek(getRelativeChapterLocation())
> ```

This fixes incorrect seek after a verse marker action. This seek may be something that we want to put in lockToVerse(null), because I would assume that anytime we want to set lockToVerse to null, then we want to transition from the verse space to the relative chapter space.

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 206 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-Nh3Ccfj6gVGgONlWX_M:-NhCFNng50SmMfWtQNIk:bj16g09) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/fa2a6e70f442ad41b261fdbcfc8c001e995e7df3/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L206)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

This fixes incorrect seek after a verse marker action. This seek may be something that we want to put in lockToVerse(null), because I would assume that anytime we want to set lockToVerse to null, then we want to transition from the verse space to the relative chapter space.
</blockquote></details>

This is not relevant because seek now takes an optional parameter that specifies when to unlock from all verses before seeking to the position

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-:-NhSdb7a-PUqSsoh_Vwa:bnfp4nl)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @darrellcolehill)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 410 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/854#-Nh2Sxc-CSrHfwvrs1d4:-Nh88Vww7QDdAKpYidNu:bu4ver9) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6bef18ed1e8efab1c85cd638c97b369a6f516a91/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L410)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Not crazy about this, but this mostly resolves the issues with scrolling after playing a verse.
</blockquote></details>

you could have scroll unlock the verse?

**Pull request merged**
