### PR TITLE
Use case for Deleting resource container / source content

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/491)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/491)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResourceContainer.kt, line 43 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS78lv185_c50cf8tV:-MuS78lx74yyzOj3Tx1C:b3r3rz2) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResourceContainer.kt#L43)):*
> ```Kotlin
>                 if (it == DeleteResult.SUCCESS) {
>                     val file = directoryProvider.getSourceContainerDirectory(resourceContainer)
>                     file.deleteRecursively()
> ```

log the name of the directory being deleted and the result. (we need to log more)
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResult.kt, line 24 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS7Y73400eSCf42gOG:-MuS7Y73400eSCf42gOH:b2733sj) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResult.kt#L24)):*
> ```Kotlin
>     SUCCESS,
>     DEPENDENCY_EXISTS,
>     NOT_EXISTS,
> ```

NOT_FOUND or DOES_NOT_EXIST
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResult.kt, line 25 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS7jm6CuCmMEQ9vA-D:-MuS7jm6CuCmMEQ9vA-E:b6w6s0u) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResult.kt#L25)):*
> ```Kotlin
>     DEPENDENCY_EXISTS,
>     NOT_EXISTS,
>     ERROR
> ```

What kind? IO_ERROR? SQL_ERROR? can we have a better idea than just a generic ERROR?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt, line 178 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS8mAC8e79S4NS-sk1:-MuS8mAC8e79S4NS-sk2:bpsy1mp) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L178)):*
> ```Kotlin
>                         return@transaction
>                     }
>                     derivedRcExists ->{
> ```

run autoformatter

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/491)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 85 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuSB0nvAkMjvZk9dxG2:-MuSB0nvAkMjvZk9dxG3:b9wnp0u) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L85)):*
> ```Kotlin
>         }
> 
>         return when {
> ```

this when statement isn't well structured, and cases begin in the code above it too.

We're trying to determine the state of the RC and existing database, and what the appropriate response is, though the code here does not structure that in a readable way as we continue to mess with this section.

There should be two sections: evaluation, leading to an enum describing the state, and a when statement on those enums for what action to perform.

since it doesn't look like you changed "isAlreadyImported", I assume you're always going to end up merging media rather than doing the delete/update.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 176 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuSCGcR63WAvoWFAiIq:-MuSCGcR63WAvoWFAiIr:bsvy1zz) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L176)):*
> ```Kotlin
>     private fun tryRemoveRCBeforeImport(rcFile: File): Boolean {
>         ResourceContainer.load(rcFile).use { rc ->
>             resourceMetadataRepository.getAllSources().blockingGet()
> ```

We're probably not going to be able to get rid of all blocking gets until a refactor of import/export, but you should only need one in this function- at the very end.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 179 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuSC-n03wOZ7YM6r9fX:-MuSC-n03wOZ7YM6r9fY:bj8n73r) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L179)):*
> ```Kotlin
>                 .find {
>                     it.language.slug == rc.manifest.dublinCore.language.identifier &&
>                             it.identifier == rc.manifest.dublinCore.identifier
> ```

these cases should be saved to variables for readability

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/491)* status: 0 of 15 files reviewed, 7 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResourceContainer.kt, line 43 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS78lv185_c50cf8tV:-MuVvRggBa4oq0-CjxWt:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResourceContainer.kt#L43)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

log the name of the directory being deleted and the result. (we need to log more)
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResult.kt, line 24 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS7Y73400eSCf42gOG:-MuVvSDY4dAzkXcicgI4:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResult.kt#L24)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

NOT_FOUND or DOES_NOT_EXIST
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResult.kt, line 25 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS7jm6CuCmMEQ9vA-D:-MuVvT9f9XkW4VE0sMU6:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResult.kt#L25)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

What kind? IO_ERROR? SQL_ERROR? can we have a better idea than just a generic ERROR?
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 85 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuSB0nvAkMjvZk9dxG2:-MuVvb6Z20neexchCA94:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L85)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this when statement isn't well structured, and cases begin in the code above it too.

We're trying to determine the state of the RC and existing database, and what the appropriate response is, though the code here does not structure that in a readable way as we continue to mess with this section.

There should be two sections: evaluation, leading to an enum describing the state, and a when statement on those enums for what action to perform.

since it doesn't look like you changed "isAlreadyImported", I assume you're always going to end up merging media rather than doing the delete/update.
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 176 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuSCGcR63WAvoWFAiIq:-MuVw8Fb1So2-98R011Q:baypw1d) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L176)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

We're probably not going to be able to get rid of all blocking gets until a refactor of import/export, but you should only need one in this function- at the very end.
</blockquote></details>

this method only executes when the existing rc has different version. It must delete or "clean up" the old rc before importing a new one to avoid conflicts
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 179 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuSC-n03wOZ7YM6r9fX:-MuVwqAD-1QIxV9lDaCy:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L179)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

these cases should be saved to variables for readability
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt, line 178 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS8mAC8e79S4NS-sk1:-MuVwxPH8iG36xuEBghR:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L178)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

run autoformatter
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/491)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResourceContainer.kt, line 43 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS78lv185_c50cf8tV:-MuWCRggAL2-DZK3AJJb:b-3w0k72) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResourceContainer.kt#L43)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

and the result
(deleteRecursively returns a boolean as to whether it actually deleted or not)
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 179 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuSC-n03wOZ7YM6r9fX:-MuWDCAfEIQhnihQqf7a:b-m7e5nr) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L179)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see no change?
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 82 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuWE0dMDcu6yKi2DtqH:-MuWE0dMDcu6yKi2DtqI:b-lzzqhc) ([raw file](https://github.com/bible-translation-tools/orature/blob/1b84202091dcfbd0a793bce602bdfa84bd0d5f3e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L82)):*
> ```Kotlin
>                 projectImporter.importResumableProject(rcFile)
>             }
>             isAlreadyImported(rcFile) -> {
> ```

Rather than merge your update stuff into import, it should be pulled up here. Especially for readability. The case here shouldn't be "isAlreadyImported" because if it's already imported, we should know EXACTLY what we're doing, and there's two different cases.

this when statement needs to be:
invalid RC
import resumable project
merge media to existing rc
update existing rc
import new rc

This produces code that is clean and reads like comments. As we look over it we see very clearly what EXACT thing we're doing to do. Decisions aren't futher hidden in the individual actions.

The code ABOVE this block should help make it abundantly clear WHY a particular path is chosen as well.
___
*[jvm/workbookapp/src/integration-test/resources/resource-containers/hi_ulb.zip, line 0 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuWDZPc6tmstSq8wafw:-MuWDZPc6tmstSq8wafx:b5f18nn) ([raw file](https://github.com/bible-translation-tools/orature/blob/1b84202091dcfbd0a793bce602bdfa84bd0d5f3e/jvm/workbookapp/src/integration-test/resources/resource-containers/hi_ulb.zip#L0)):*
We have an rc for en-x-demo1, is there a reason that's insufficient and we must add 2mb to our code repository?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/491)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResourceContainer.kt, line 43 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuS78lv185_c50cf8tV:-MuWSWVp9JQKDwROmc1p:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/DeleteResourceContainer.kt#L43)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

and the result
(deleteRecursively returns a boolean as to whether it actually deleted or not)
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 179 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuSC-n03wOZ7YM6r9fX:-MuWQseH6yYwJRiZ2XD-:b-v03mwj) ([raw file](https://github.com/bible-translation-tools/orature/blob/b59f679071d9d9cc5915453fcf48b856c8306215/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L179)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I see no change?
</blockquote></details>

I don't know why Reviewable doesn't show it here
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt, line 82 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuWE0dMDcu6yKi2DtqH:-MuWWSdy1dH0j7I7znF1:b-qhtj0u) ([raw file](https://github.com/bible-translation-tools/orature/blob/1b84202091dcfbd0a793bce602bdfa84bd0d5f3e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L82)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Rather than merge your update stuff into import, it should be pulled up here. Especially for readability. The case here shouldn't be "isAlreadyImported" because if it's already imported, we should know EXACTLY what we're doing, and there's two different cases.

this when statement needs to be:
invalid RC
import resumable project
merge media to existing rc
update existing rc
import new rc

This produces code that is clean and reads like comments. As we look over it we see very clearly what EXACT thing we're doing to do. Decisions aren't futher hidden in the individual actions.

The code ABOVE this block should help make it abundantly clear WHY a particular path is chosen as well.
</blockquote></details>

Okay I refactored to the boolean steps.
___
*[jvm/workbookapp/src/integration-test/resources/resource-containers/hi_ulb.zip, line  at r3](https://reviewable.io/reviews/bible-translation-tools/orature/491#-MuWDZPc6tmstSq8wafw:-MuWgb5w0OB66DNGEybE:b-m3i8kt) ([raw file](https://github.com/bible-translation-tools/orature/blob/1b84202091dcfbd0a793bce602bdfa84bd0d5f3e/jvm/workbookapp/src/integration-test/resources/resource-containers/hi_ulb.zip#L)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

We have an rc for en-x-demo1, is there a reason that's insufficient and we must add 2mb to our code repository?
</blockquote></details>

en-x-demo1 is imported as derived project -- in question

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/491#-:-Mv4y4l855dxdy27enUp:bnfp4nl)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

**Pull request merged**
