### PR TITLE
Contributor Info - Back-end Model

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525)* status: 0 of 18 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/Mp3MetadataAccessor.kt, line 7 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTUFCf5iT7VtTLuwAV:-MyTUFCf5iT7VtTLuwAW:b8gcd4d) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/Mp3MetadataAccessor.kt#L7)):*
> ```Kotlin
> import java.io.File
> 
> class Mp3MetadataAccessor(private val file: File) {
> ```

We already have an Mp3Metadata class, which extends AudioMetadata; feels more appropriate to extend that than create more Mp3Metadata classes
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/Mp3MetadataAccessor.kt, line 39 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTVE8vCvgGJCZ7bQ9M:-MyTVE8vCvgGJCZ7bQ9N:b-dasww3) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/Mp3MetadataAccessor.kt#L39)):*
> ```Kotlin
>             metadata.save(tempFile.path)
>             tempFile.copyTo(file, true)
>             tempFile.delete()
> ```

deleting this should be wrapped in a try/catch in the event of an IOException so the file isn't stranded
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 234 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTVVo_BjhiQgxPJdX4:-MyTVVo_BjhiQgxPJdX5:b-nez61d) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L234)):*
> ```Kotlin
>     }
> 
>     fun setContributorInfo(contributors: List<String>) {
> ```

This should accept List<Contributor> not String, Contributor should implement toString() to serialize it appropriately.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt, line 108 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTVkfMAtaj1qmbJvzB:-MyTVkfMAtaj1qmbJvzC:b-34vmyd) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L108)):*
> ```Kotlin
>     }
> 
>     private fun setContributorInfo(contributors: List<String>, projectFile: File) {
> ```

See above
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/dialogs/ExportChapterDialog.kt, line 132 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTW9ww9SFnDodZ65rT:-MyTW9ww9SFnDodZ65rU:b-xg1tsf) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/dialogs/ExportChapterDialog.kt#L132)):*
> ```Kotlin
> 
>     fun export() {
>         viewModel.saveContributors()
> ```

Race condition
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 127 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTWge2EnqYAIiHAUSh:-MyTWge2EnqYAIiHAUSi:b5hr9ck) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L127)):*
> ```Kotlin
>         projectFilesAccessor.copySourceFiles(linkedResource)
>         projectFilesAccessor.createSelectedTakesFile()
>         activeProjectFilesAccessorProperty.set(projectFilesAccessor)
> ```

Project is synonymous with Workbook; so a project files accessor probably belongs in the workbook; not here.

This class should be effectively serve as a "bookmark" in the workbook.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525)* status: 0 of 20 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/Mp3MetadataAccessor.kt, line 39 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTVE8vCvgGJCZ7bQ9M:-MyTYGg157YvEoeCeqiQ:bjf8khd) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/Mp3MetadataAccessor.kt#L39)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

deleting this should be wrapped in a try/catch in the event of an IOException so the file isn't stranded
</blockquote></details>

it is true with ` java.nio.file.Files ` to possibly throw IOException. With ` java.io.File` it returns false.

https://docs.oracle.com/javase/8/docs/api/java/io/File.html#delete--
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt, line 234 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTVVo_BjhiQgxPJdX4:-MyT_yLP0BRqL0bqWggN:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L234)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This should accept List<Contributor> not String, Contributor should implement toString() to serialize it appropriately.
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt, line 108 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTVkfMAtaj1qmbJvzB:-MyTbElS8FYHCYk1iRnm:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectExporter.kt#L108)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 127 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTWge2EnqYAIiHAUSh:-MyTbyxg61Yq3pmow9gj:b-s6uusw) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L127)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Project is synonymous with Workbook; so a project files accessor probably belongs in the workbook; not here.

This class should be effectively serve as a "bookmark" in the workbook.
</blockquote></details>

I just re-arrange the code and use the local variable (projectFileAccessor) instead of object property (activeProjectFilesAccessor)

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525)* status: 0 of 25 files reviewed, 6 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/dialogs/ExportChapterDialog.kt, line 132 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTW9ww9SFnDodZ65rT:-MyTbfth5o0rdTIoyc2M:bu1xx18) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/dialogs/ExportChapterDialog.kt#L132)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Race condition
</blockquote></details>

It's just saving to synchronize with the project. The current (latest) contributor list is maintained inside ExportChapterViewModel, which will be used to export chapter file.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/Mp3MetadataAccessor.kt, line 7 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTUFCf5iT7VtTLuwAV:-MyTvMFo685Trjmov338:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/Mp3MetadataAccessor.kt#L7)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

We already have an Mp3Metadata class, which extends AudioMetadata; feels more appropriate to extend that than create more Mp3Metadata classes
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525)* status: 0 of 26 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/mp3/Mp3Metadata.kt, line 135 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/525#-Mygzx4u8qoBduGhxiDv:-Mygzx4u8qoBduGhxiDw:b-8pzggl) ([raw file](https://github.com/bible-translation-tools/orature/blob/60f2e1b5d1252b5b5597041bc6954b38eef97a52/common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/mp3/Mp3Metadata.kt#L135)):*
> ```Kotlin
>         id3Metadata.save(tempFile.path)
>         tempFile.copyTo(mp3File, true)
>         tempFile.delete()
> ```

can you do this all in a try/catch to make sure the temp file is deleted if there's an error?

When I mentioned it earlier, I described the problem maybe a little overly generically.

tempFile needs to be deleted. There can be exceptions before this (namely, in copyTo, perhaps in save()). So, that should be wrapped in a try, so the finally can call delete. Otherwise this potentially large file could get stranded on the user's machine, and Orature won't be able to know to clean it up.

I didn't mean to have the try catch on the delete itself.
___
*[common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/wav/WavMetadata.kt, line 69 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/525#-Myh-8ZK-rHdeVD0KpD7:-Myh-8ZK-rHdeVD0KpD8:b-gidz6o) ([raw file](https://github.com/bible-translation-tools/orature/blob/60f2e1b5d1252b5b5597041bc6954b38eef97a52/common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/wav/WavMetadata.kt#L69)):*
> ```Kotlin
>     override fun artists(): List<String> {
>         // TODO
>         return listOf()
> ```

you should be able to just do TODO(), which gets tracked as a todo, causes an error if the code gets executed, but you don't have to worry about return values and stuff
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/License.kt, line 1 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/525#-Myh0zO33j6fnVEaivaP:-Myh0zO33j6fnVEaivaQ:bvdp5k) ([raw file](https://github.com/bible-translation-tools/orature/blob/60f2e1b5d1252b5b5597041bc6954b38eef97a52/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/License.kt#L1)):*
> ```Kotlin
> package org.wycliffeassociates.otter.common.data.primitives
> ```

gpl license statement for source file
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 127 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTWge2EnqYAIiHAUSh:-Myh2niT8iVCHPmFjtyx:bq9p2ff) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L127)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I just re-arrange the code and use the local variable (projectFileAccessor) instead of object property (activeProjectFilesAccessor)
</blockquote></details>

I still don't think this belongs in a class who's sole purpose is to track what project, book, chapter, verse you're on.

It belongs as a member of the Workbook class.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525)* status: 0 of 26 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/mp3/Mp3Metadata.kt, line 135 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/525#-Mygzx4u8qoBduGhxiDv:-MyhbY2k0HNh8OcBRDP5:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/60f2e1b5d1252b5b5597041bc6954b38eef97a52/common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/mp3/Mp3Metadata.kt#L135)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can you do this all in a try/catch to make sure the temp file is deleted if there's an error?

When I mentioned it earlier, I described the problem maybe a little overly generically.

tempFile needs to be deleted. There can be exceptions before this (namely, in copyTo, perhaps in save()). So, that should be wrapped in a try, so the finally can call delete. Otherwise this potentially large file could get stranded on the user's machine, and Orature won't be able to know to clean it up.

I didn't mean to have the try catch on the delete itself.
</blockquote></details>

Done.
___
*[common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/wav/WavMetadata.kt, line 69 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/525#-Myh-8ZK-rHdeVD0KpD7:-MyhbmZf-zB992ekTLWE:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/60f2e1b5d1252b5b5597041bc6954b38eef97a52/common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/wav/WavMetadata.kt#L69)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

you should be able to just do TODO(), which gets tracked as a todo, causes an error if the code gets executed, but you don't have to worry about return values and stuff
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/License.kt, line 1 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/525#-Myh0zO33j6fnVEaivaP:-MyhbmCiCYRHERVaZqks:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/60f2e1b5d1252b5b5597041bc6954b38eef97a52/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/License.kt#L1)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

gpl license statement for source file
</blockquote></details>

Done.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525)* status: 0 of 26 files reviewed, 5 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 127 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MyTWge2EnqYAIiHAUSh:-MyhdMB95i4np5iT2Obp:bs34z93) ([raw file](https://github.com/bible-translation-tools/orature/blob/6cf578db21ae31e9b95e227629d230a6e362c255/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L127)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I still don't think this belongs in a class who's sole purpose is to track what project, book, chapter, verse you're on.

It belongs as a member of the Workbook class.
</blockquote></details>

I agree and let's do it in a separate PR

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525)* status: 0 of 26 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModel.kt, line 101 at r6](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MylfNTtB91S-HDZg0pY:-MylfNTtB91S-HDZg0pZ:b-8gdadd) ([raw file](https://github.com/bible-translation-tools/orature/blob/8fafccb0e7088afcb82719fd451d080b431f0ba2/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModel.kt#L101)):*
> ```Kotlin
>                 contributors.setAll(projectContributors)
>             }
>         }
> ```

We should probably prefer to do this in onDock and remove the listener in onUndock. The tight coupling here makes setting up tests more frustrating because you have to set all this up before all tests, regardless of ones which use the wbds, contributors, etc

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525)* status: 0 of 26 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModel.kt, line 101 at r6](https://reviewable.io/reviews/bible-translation-tools/orature/525#-MylfNTtB91S-HDZg0pY:-MyloI4SDLjtKPWc9oZ-:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/8fafccb0e7088afcb82719fd451d080b431f0ba2/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModel.kt#L101)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

We should probably prefer to do this in onDock and remove the listener in onUndock. The tight coupling here makes setting up tests more frustrating because you have to set all this up before all tests, regardless of ones which use the wbds, contributors, etc
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/525#-:-MyqjKK-B6jBMS9CEe-u:bnfp4nl)* status: 0 of 26 files reviewed, all discussions resolved (waiting on @jsarabia)

**Pull request merged**
