### PR TITLE
Refactor chunks relay

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1108)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
need more testing done before release

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 1 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1108)* status: 1 of 21 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationBuilder.kt` line 47 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1108#-Nwo9sgu21QFP6zqzdbW:-Nwo9sgu21QFP6zqzdbX:bqaxbpc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/859222219eaf481935b946e6349c51c6e36dd406/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationBuilder.kt#L47)):*
> ```Kotlin
>      */
>     fun getOrCompile(workbook: Workbook, chapter: Chapter) : Single<Take> {
>         val takes = chapter.chunks.blockingGet()
> ```

don't use blockingGet if you're not inside an observable, it prevents things from being async but the Single return value allows the consumer to assume any significant IO or computation is async or can be.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 583 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1108#-NwoBKS8730UcN7VnfN-:-NwoBKS8730UcN7VnfN0:b-ze3wrp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/859222219eaf481935b946e6349c51c6e36dd406/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L583)):*
> ```Kotlin
>                     chapter.observableChunks
>                         .filter { it.isNotEmpty() }
>                         .firstOrError()
> ```

you made .chunks a single that does exactly this- why not use it?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1108)* status: 1 of 21 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationBuilder.kt` line 47 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1108#-Nwo9sgu21QFP6zqzdbW:-NwoQtZMABzCvT4iQlxG:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/859222219eaf481935b946e6349c51c6e36dd406/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ChapterTranslationBuilder.kt#L47)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

don't use blockingGet if you're not inside an observable, it prevents things from being async but the Single return value allows the consumer to assume any significant IO or computation is async or can be.
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 583 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1108#-NwoBKS8730UcN7VnfN-:-NwoIUhk7qNv0EapapB0:b-qlv770) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/859222219eaf481935b946e6349c51c6e36dd406/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L583)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

you made .chunks a single that does exactly this- why not use it?
</blockquote></details>

I wanted to make sure the emission wasn't an empty list (default value), hence the observableChunks.filter {}. 
The `chunks: Single` is going to return the default empty list before the actual list is emitted, given that `chunkCount > 0`.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1108#-:-NwywjBTAXvnSyjdrDat:bnfp4nl)* status: 1 of 21 files reviewed, all discussions resolved

**Pull request merged**
