### PR TITLE
Refactored Workbook Page

### PR DESCRIPTION
**Pull request by mXaln**
Connected ChapterCard to the Workbook Page.
Moved workbook related actions to WorkbookDataStore

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/251)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/251)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/ProgressDialog.kt, line 32 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVSNbQ56C6F3AYTgmt3:-MVSNbQ61TyCffsUuTMm:bxra7ko) ([raw file](https://github.com/bible-translation-tools/otter/blob/742624b59f7decd37dd632cf6b8b6965200c2f74/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/ProgressDialog.kt#L32)):*
> ```Kotlin
>         importStylesheet<ProgressDialogStyles>()
> 
>         showDialogProperty.onChange {
> ```

I generally don't like the idea of the dialog being able to "show itself." It should be USED somewhere else, not by itself. 

I'd probably prefer this be done through opening a un-decorated modal?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 130 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVSRYK5-z8VP3wBSufS:-MVSRYK5-z8VP3wBSufT:b-ggbj96) ([raw file](https://github.com/bible-translation-tools/otter/blob/742624b59f7decd37dd632cf6b8b6965200c2f74/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L130)):*
> ```Kotlin
>             ))
>             graphic = ProjectGridStyles.deleteIcon("60px")
>             root.addClass(AppStyles.progressDialog)
> ```

I'd like to remove Style classes as we refactor; can you replace this with CSS?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 202 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVSQXcF6EH6Tazu1txS:-MVSQXcF6EH6Tazu1txT:bwhmaso) ([raw file](https://github.com/bible-translation-tools/otter/blob/742624b59f7decd37dd632cf6b8b6965200c2f74/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L202)):*
> ```Kotlin
>     }
> 
>     fun deleteWorkbook(workbook: Workbook? = null): Completable {
> ```

I'm not particularly keen on the idea of putting delete and export here. This class is meant to be a global observable data store of state related to open parts of the workbook, rather than make it be a viewmodel since it's not tied to a particular view.

So, first, I think these should go back to the WorkbookPageViewModel since that's where the action is. 

Second, We should not create these domain classes; use Dagger and a Provider<>
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModel.kt, line 136 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVSR8eKATGanOWT60Y6:-MVSR8eKATGanOWT60Y7:blwyb6u) ([raw file](https://github.com/bible-translation-tools/otter/blob/742624b59f7decd37dd632cf6b8b6965200c2f74/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModel.kt#L136)):*
> ```Kotlin
>                 showDeleteDialogProperty.set(false)
>                 workspace.viewStack.clear()
>                 workspace.dock<HomePage>()
> ```

why are you doing this over navigate back?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/251)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/ProgressDialog.kt, line 32 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVSNbQ56C6F3AYTgmt3:-MVVYqVv0FoS0YcOVNjM:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/742624b59f7decd37dd632cf6b8b6965200c2f74/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/ProgressDialog.kt#L32)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I generally don't like the idea of the dialog being able to "show itself." It should be USED somewhere else, not by itself. 

I'd probably prefer this be done through opening a un-decorated modal?
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 130 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVSRYK5-z8VP3wBSufS:-MVW6luj6PBhr1SpVzIw:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/742624b59f7decd37dd632cf6b8b6965200c2f74/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L130)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I'd like to remove Style classes as we refactor; can you replace this with CSS?
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 202 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVSQXcF6EH6Tazu1txS:-MVWIqQN6tem6vue5czB:b4o06am) ([raw file](https://github.com/bible-translation-tools/otter/blob/742624b59f7decd37dd632cf6b8b6965200c2f74/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L202)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I'm not particularly keen on the idea of putting delete and export here. This class is meant to be a global observable data store of state related to open parts of the workbook, rather than make it be a viewmodel since it's not tied to a particular view.

So, first, I think these should go back to the WorkbookPageViewModel since that's where the action is. 

Second, We should not create these domain classes; use Dagger and a Provider<>
</blockquote></details>

Done. Had to refactor ProjectExporter to make it provideable, 'cause it was hardly coupled with other classes
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModel.kt, line 136 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVSR8eKATGanOWT60Y6:-MVW6rMMEBr67PKDQIz4:b-lgtf1p) ([raw file](https://github.com/bible-translation-tools/otter/blob/742624b59f7decd37dd632cf6b8b6965200c2f74/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookPageViewModel.kt#L136)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why are you doing this over navigate back?
</blockquote></details>

silly me, just overthinked the simple thing (:facepalm). Thanks.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r3, 6 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/251)* status: 11 of 20 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 34 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVWUt2E-XEC53HX0GZC:-MVWUt2F71T4PJwDyqal:b-kwu254) ([raw file](https://github.com/bible-translation-tools/otter/blob/76e4a1fa38a3542d715b2c260dd15cc7d267b1b4/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L34)):*
> ```Kotlin
> 
>     @Inject
>     lateinit var collectionRepository: ICollectionRepository
> ```

Does this still need these repositories?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/251)* status: 11 of 20 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 34 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/251#-MVWUt2E-XEC53HX0GZC:-MVWXAR479oEE4zn8Uu5:bzdmmng) ([raw file](https://github.com/bible-translation-tools/otter/blob/76e4a1fa38a3542d715b2c260dd15cc7d267b1b4/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L34)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Does this still need these repositories?
</blockquote></details>

Apparently not. Removed them

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/251#-:-MVWX_8yBLOKK5ywgatD:bnfp4nl)* status: 11 of 20 files reviewed, all discussions resolved (waiting on @jsarabia)

**Pull request merged**
