### PR TITLE
Fixed waveform scrolling bugs (OT-761)

### PR DESCRIPTION
**Pull request by mXaln**
1. Correctly use scroll delta to change current position (otherwise scroll speed is slow and occasionally verse markers freeze or move unexpectedly)
2. Correctly consume mouse/drag events to prevent propagation (dragging marker 1 drags waveform instead)

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/884)

### CODE REVIEW

**Review by darrellcolehill — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/884)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Comment by mXaln** [comment]
I had to remove calls to `connectionFactory.load(state)` in `seek` method. Because `load` seeks to position 0, which creates a bug when we scroll marker layer. Every time we seek to a certain position, `load` seeks to 0, and that creates an effect of jumping verse markers (easier to see on Windows PC). Anyway, to me reloading audio twice in `seek` method looks like a workaround and actually shouldn't happen. And we should rely that the connection is loaded before calling `seek` method.

**Review by darrellcolehill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/884)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[`jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioPlayerConnection.kt` line 154 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/884#-NjJ0yTH3fI3OIHzsZuq:-NjJ0yTH3fI3OIHzsZur:bglhqni) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4683cdc7062cd305263d7d0935547f9eaeac0b8f/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioPlayerConnection.kt#L154)):*
> ```Kotlin
> 
>     override fun seek(position: Int) {
>         connectionFactory.load(state)
> ```

I agree that having to surround the connectionFactory.seek with connectionFactory.load seems odd, but it seems that without them clicking on next verse seeks back to zero.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/884)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @darrellcolehill and @jsarabia)

___
*[`jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioPlayerConnection.kt` line 154 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/884#-NjJ0yTH3fI3OIHzsZuq:-NjNO7MWB97IzlJWi9kX:b43u39y) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4683cdc7062cd305263d7d0935547f9eaeac0b8f/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioPlayerConnection.kt#L154)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

I agree that having to surround the connectionFactory.seek with connectionFactory.load seems odd, but it seems that without them clicking on next verse seeks back to zero.
</blockquote></details>

Good catch! I've fixed this by reloading player when audio has been changed.

**Review by darrellcolehill — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/884)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia)

**Pull request merged**
