### PR TITLE
initializing and cleaning listeners

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/646)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/646)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/PluginOpenedPage.kt` line 120 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/646#-N931-rv4qFUmqdD9vdk:-N931-rv4qFUmqdD9vdl:bfbp5zd) ([raw file](https://github.com/bible-translation-tools/orature/blob/6159561961bab294a1d61e0b58e9c3bf6530a329/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/PluginOpenedPage.kt#L120)):*
> ```Kotlin
>         sourceTextZoomRateProperty.onChangeWithDisposer {
>             it?.let { sourceContent.zoomRateProperty.set(it.toInt()) }
>         }.let(listeners::add)
> ```

is there a reason this can't be:

zoomProperty.bind(this@PluginOpenedPage.sourceTextZoomRateProperty) 

in the location where it was deleted?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt` line 104 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/646#-N932LNv98gLqP-m5TIs:-N932LNw4RIhLFlG4rWp:bh9oiqs) ([raw file](https://github.com/bible-translation-tools/orature/blob/6159561961bab294a1d61e0b58e9c3bf6530a329/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt#L104)):*
> ```Kotlin
>     private var recordChapterSubscription: Disposable? = null
>     private var openPluginSubscription: Disposable? = null
>     private var compileSubscription: Disposable? = null
> ```

Why do these all need their own disposables, rather than using the composite? These are all things that should complete and not need a manual dispose?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/646)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/PluginOpenedPage.kt` line 120 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/646#-N931-rv4qFUmqdD9vdk:-N96A_k2DN92ByZcWgDP:b21c09h) ([raw file](https://github.com/bible-translation-tools/orature/blob/6159561961bab294a1d61e0b58e9c3bf6530a329/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/PluginOpenedPage.kt#L120)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

is there a reason this can't be:

zoomProperty.bind(this@PluginOpenedPage.sourceTextZoomRateProperty) 

in the location where it was deleted?
</blockquote></details>

zoomProperty is also set manually in other place. I've tried bidirectional binding, but it didn't work either. Maybe because there is another listener attached to it.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt` line 104 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/646#-N932LNv98gLqP-m5TIs:-N96AIql8QHlu2S1wDFq:b-jkcqnd) ([raw file](https://github.com/bible-translation-tools/orature/blob/6159561961bab294a1d61e0b58e9c3bf6530a329/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt#L104)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why do these all need their own disposables, rather than using the composite? These are all things that should complete and not need a manual dispose?
</blockquote></details>

Yeah, you are right. I didn't know that observables self-dispose when they are completed. Removed.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/646)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt` line 104 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/646#-N96fr-F8_dyR5FADjsH:-N96fr-F8_dyR5FADjsI:b-33b27n) ([raw file](https://github.com/bible-translation-tools/orature/blob/eca5e53235cde5985a9430aacc19f45418890869/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L104)):*
> ```Kotlin
>     private var recorderSubscription: Disposable? = null
>     private var pluginSubscription: Disposable? = null
>     private var importSubscription: Disposable? = null
> ```

these are more rxObservables that should complete on their own like the previous comment

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/646)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt` line 104 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/646#-N96fr-F8_dyR5FADjsH:-N96jrT57xxKOfPSjbwe:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/eca5e53235cde5985a9430aacc19f45418890869/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L104)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

these are more rxObservables that should complete on their own like the previous comment
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/646#-:-N970Op50Y1_rvX_k3gJ:bnfp4nl)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

**Pull request merged**
