### PR TITLE
Allow to open verse node in an external app

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt` line 7 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS57dR4Bupq3VyB1Wq:-NZS57dR4Bupq3VyB1Wr:b-4lwcgv) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt#L7)):*
> ```Kotlin
> import kotlin.collections.ArrayList
> 
> interface NarrationAction {
> ```

Please add some javadoc comments to these Actions
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt` line 19 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS-cHWBxDzvkAPTcdy:-NZS-cHWBxDzvkAPTcdz:b-bt4uwy) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt#L19)):*
> ```Kotlin
>     private var node: VerseNode? = null
> 
>     override fun execute() {
> ```

shouldn't this also finalize the previous verse? (setting the end position)
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 76 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS2MrcEoYKkRMirY1t:-NZS2MrcEoYKkRMirY1u:b-8j53nx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L76)):*
> ```Kotlin
>                                 }
>                                 disableWhen {
>                                     viewModel.isRecordingAgainProperty.or(viewModel.isRecordingProperty)
> ```

shouldn't "isRecording" be true when it is recording for the first time AND when it is recording again?

How could something be recordingAgain but not recording?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 183 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS2y7J7SDgY9yvxfyg:-NZS2y7J7SDgY9yvxfyh:b-xm72od) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L183)):*
> ```Kotlin
>     private lateinit var jsonFile: File
> 
>     val contextProperty = SimpleObjectProperty(PluginType.EDITOR)
> ```

pluginContextProperty?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 257 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS3CF2D3B_Jb5r40P3:-NZS3CF2D3B_Jb5r40P4:bow94h7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L257)):*
> ```Kotlin
>         recordedAudio?.let { audio ->
>             val verse = recordedVerses[index]
>             val file = audioFileUtils.getSectionAsFile(audio, verse.start, verse.end)
> ```

if audio isn't wav, isn't this going to create a PCM file which will then ask the user for configuration in Ocenaudio? Shouldn't we ensure we are extracting the section out to wav format?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 410 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS3WR0ExXBBs_aH12E:-NZS3WR0ExXBBs_aH12F:b6fgj7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L410)):*
> ```Kotlin
>     }
> 
>     private fun processWithPlugin(file: File, index: Int) {
> ```

processWithEditor- there's too much hard coded to edit for this to be usable for any plugin (recording, verse marking, etc.)

If we should let this be processWithPlugin, then the option of which plugin type should be a parameter, but that would also involve some other refactoring of this function
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 441 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS45aBCaEzfirpn1Eg:-NZS45aBCaEzfirpn1Eh:b-vmnkwd) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L441)):*
> ```Kotlin
>                             narrationHistory.execute(action)
>                             updateHistoryAvailable()
>                             updateJsonFile()
> ```

can we extract this block to a method?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/AudioPluginViewModel.kt` line 152 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS5-8g56VRaiilprlE:-NZS5-8g56VRaiilprlF:b-ysp7er) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/AudioPluginViewModel.kt#L152)):*
> ```Kotlin
>     }
> 
>     fun edit(file: File): Single<PluginActions.Result> {
> ```

provide some documentation detailing the purpose of this method over the other edit

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760)* status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt` line 7 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS57dR4Bupq3VyB1Wq:-NZesdjF57SLp0PqNX4V:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt#L7)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Please add some javadoc comments to these Actions
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt` line 19 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS-cHWBxDzvkAPTcdy:-NZesf5w2Wnl--WDKkye:b-ywsjdj) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt#L19)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

shouldn't this also finalize the previous verse? (setting the end position)
</blockquote></details>

This will be finalized in pauseRecording method in the viewmodel
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 76 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS2MrcEoYKkRMirY1t:-NZeswSZ2A4QD44AzVha:b-a69tt4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L76)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

shouldn't "isRecording" be true when it is recording for the first time AND when it is recording again?

How could something be recordingAgain but not recording?
</blockquote></details>

yeah, isRecordingAgain property was created as a flag that the recording is not a regular recording, that should be paused, instead of stopped. But you are right, it's a little bit confusing. So I've refactored it so isRecording is always true (whether it's regular or re-recording).
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 183 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS2y7J7SDgY9yvxfyg:-NZetWpl-Zt9jh3eixvo:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L183)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

pluginContextProperty?
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 257 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS3CF2D3B_Jb5r40P3:-NZetXv37wtxxvXWz2CE:b3ivakc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L257)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

if audio isn't wav, isn't this going to create a PCM file which will then ask the user for configuration in Ocenaudio? Shouldn't we ensure we are extracting the section out to wav format?
</blockquote></details>

If audio is not wav, it will be converted to wav in PluginActions edit method.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 410 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS3WR0ExXBBs_aH12E:-NZetp0eBH64sEfL7145:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L410)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

processWithEditor- there's too much hard coded to edit for this to be usable for any plugin (recording, verse marking, etc.)

If we should let this be processWithPlugin, then the option of which plugin type should be a parameter, but that would also involve some other refactoring of this function
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 441 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS45aBCaEzfirpn1Eg:-NZetpgeBDl4U_B52G_b:bu77gva) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L441)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can we extract this block to a method?
</blockquote></details>

Done. Couldn't come up with the best name for the method though.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/AudioPluginViewModel.kt` line 152 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS5-8g56VRaiilprlE:-NZety8P3gWIbPkexvG5:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/AudioPluginViewModel.kt#L152)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

provide some documentation detailing the purpose of this method over the other edit
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt` line 19 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS-cHWBxDzvkAPTcdy:-NZkrSkv1KIQKY3ZPouW:b-sz9bvl) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationActions.kt#L19)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

This will be finalized in pauseRecording method in the viewmodel
</blockquote></details>

That's a domain responsibility (which means model), the viewmodel has no business doing that, and the end position should not be exposed publicly to something like a viewmodel, it should be encapsulated within the actions and narration history. 

Additionally, I see in the code that the viewmodel is updating the end value of a node in the ObservableList; this is also not good. 

MVVM/MVC/etc should all kinda work the same. Specifically in the case of MVVM, the View binds to properties to update any changing values, and the onClick/Action event handlers should be set to call ViewModel methods that handle the action.

The ViewModel should work as follows:
When a method is called, often corresponding to a click event, tell the model to do something. Often, the model functions need input parameters. These input parameters are retrieved out of the properties (properties allow for holding the state of inputs that the user is making in the UI). 

The model executes. This could be asynchronous, in which the ViewModel is then going to subscribe on it, so that when it is finished it can handle updating the view. If the model action is synchronous then the ViewModel gets the value back immediately.

With the result from the Model, the ViewModel should now set values in properties so that the View can show the result. The View might want data in a different structure than the Model works with, in which the ViewModel will need to map the Model data result to the data that the View likes. The ViewModel may also need to sort things. 

Note that the ViewModel is not doing ANYTHING other than taking the current state out of the properties, telling the model to do work, and then taking the result to update properties. 

ViewModels should not be doing any logic other than: mapping, filtering, sorting
Properties should not be holding much other than current UI state

SO, for this example specifically:
The ViewModel should be telling the NarrationHistory about an action to perform. It probably shouldn't even be telling the NarrationHistory about the end position of the file, because the History probably needs a reference to the file anyway and can ask the file itself. 

NarrationHistory performs the action (In this specific case, I believe the execute method of the NextVerseAction should be setting the end position value - it is part of work involved in performing the action).

When the action has been performed, the ViewModel should request the complete list of verses from the NarrationHistory, if necessary map that data type to whatever Verse data type the View cares about, and replace what is in the ObservableList with this new list.

There is probably NEVER a scenario where any updates should be performed on individual items in an ObservableList- ObservableLists should be entirely replaced or cleared.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 257 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-NZS3CF2D3B_Jb5r40P3:-NZl1vvH-0xkPiHGWx5q:b-aakhja) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e75a8e82e3cd38d90e03dc660ba30bec00cbd317/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L257)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

If audio is not wav, it will be converted to wav in PluginActions edit method.
</blockquote></details>

This should probably be mentioned in documenting the function.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/760#-:-N_3uoAkBAxuJp4YA5nO:bnfp4nl)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @mXaln)

**Pull request merged**
