### PR TITLE
Auto scroll to last selected chapter - Book specific

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Each book will "remember" the last selected chapter to scroll to on Resume

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/610)

### CODE REVIEW

**Review by mXaln — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/610)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/610)* status: all files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt` line 356 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/610#-N5eLCqI30WUARlE8Rgp:-N5eLCqJBgdmmTh6EdVK:bk6p28j) ([raw file](https://github.com/bible-translation-tools/orature/blob/0896b215f8b28a173da165281923a11913785385/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L356)):*
> ```Kotlin
> 
>             tabChaptersListeners.putIfAbsent(text, ListChangeListener {
>                 val index = workbookDataStore.lastSelectedChapterInWorkBooks.getOrDefault(
> ```

workbook is one word, so book shouldn't be capitalized
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt` line 356 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/610#-N5eMsHR7rWf_zD9R92i:-N5eMsHR7rWf_zD9R92j:by3q5fn) ([raw file](https://github.com/bible-translation-tools/orature/blob/0896b215f8b28a173da165281923a11913785385/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt#L356)):*
> ```Kotlin
> 
>     private fun updateLastSelectedChapter(chapterNumber: Int) {
>         val bookHash = workbookDataStore.workbook.hashCode()
> ```

this is a workbookHash not a bookHash
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt` line 70 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/610#-N5eMAOrDoLdwbn1fAI-:-N5eMAOs02leaLA3eLMc:b-ltle0y) ([raw file](https://github.com/bible-translation-tools/orature/blob/0896b215f8b28a173da165281923a11913785385/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L70)):*
> ```Kotlin
>     val chapter: Chapter
>         get() = activeChapterProperty.value ?: throw IllegalStateException("Chapter is null")
>     val lastSelectedChapterInWorkBooks = mutableMapOf<Int, Int>()
> ```

same as above, but this name isn't well suited to the datastructure
lastSelectedChapterInWorkbook sounds like an integer,
maps should be named something like xToYMap

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/610)* status: all files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt` line 356 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/610#-N5eLCqI30WUARlE8Rgp:-N5ePMjTBbm2PgZQQpA5:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/0896b215f8b28a173da165281923a11913785385/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L356)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

workbook is one word, so book shouldn't be capitalized
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt` line 356 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/610#-N5eMsHR7rWf_zD9R92i:-N5ePMS4EahMDTbY7fzo:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/0896b215f8b28a173da165281923a11913785385/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt#L356)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this is a workbookHash not a bookHash
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt` line 70 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/610#-N5eMAOrDoLdwbn1fAI-:-N5ePM2LBXdaSY16fT_S:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/0896b215f8b28a173da165281923a11913785385/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L70)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

same as above, but this name isn't well suited to the datastructure
lastSelectedChapterInWorkbook sounds like an integer,
maps should be named something like xToYMap
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/610#-:-N5ekubf1EuI-RJNLEPM:bnfp4nl)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
