### PR TITLE
Change the relay chunks structure in Chapter

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Changes the type of Chapter.chunks from ReplayRelay< Chunk > to BehaviorRelay<List< Chunk >>

> Relay that emits the most recent item it has observed and all subsequent observed items to each subscribed Observer.

This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chapter.kt` line 59 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-Nfqb0afAwWRyn2gXyYN:-Nfqb0afAwWRyn2gXyYO:b8qw6wq) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/90504a77cc9af77a6c154c98cc21ea8251b59eae/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chapter.kt#L59)):*
> ```Kotlin
>     fun hasSelectedAudio() = audio.selected.value?.value != null
> 
>     fun getDraft(): Observable<Chunk> {
> ```

Is there a reason why getting the draft should be Observable<Chunk> and not Observable<List<Chunk>>?

I suppose that admittedly it's maybe more changes for consumers of the public API, but wondering your thoughts
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 230 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-Nfqdq6I-LUZ4Nr98pcg:-Nfqdq6J55bhGWsWTCFn:b-z2bdox) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/90504a77cc9af77a6c154c98cc21ea8251b59eae/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L230)):*
> ```Kotlin
>         disposables: MutableList<Disposable>
>     ): BehaviorRelay<List<Chunk>> {
>         val rr = BehaviorRelay.create<List<Chunk>>()
> ```

rr should be br or relay now
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 233 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-NfqdbjB5WZlqwNykRni:-NfqdbjB5WZlqwNykRnj:b-tyyxn4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/90504a77cc9af77a6c154c98cc21ea8251b59eae/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L233)):*
> ```Kotlin
>         db.getContentByCollectionActiveConnection(chapterCollection)
>             .map { contents ->
>                 contents.filter { it.type == ContentType.TEXT }.map { content ->
> ```

why are you nesting things under map rather than filtering first like previously? This seems to be equivalent to me, it just makes it more disorganized and harder to read?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chapter.kt` line 59 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-Nfqb0afAwWRyn2gXyYN:-NfqjGv489WO0zKd4yJZ:bqyljfp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/90504a77cc9af77a6c154c98cc21ea8251b59eae/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chapter.kt#L59)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Is there a reason why getting the draft should be Observable<Chunk> and not Observable<List<Chunk>>?

I suppose that admittedly it's maybe more changes for consumers of the public API, but wondering your thoughts
</blockquote></details>

actually this method should no longer exist because we no longer rely on "draft number" for chunks
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 230 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-Nfqdq6I-LUZ4Nr98pcg:-NfqlNAj7fq-G1gFL_Z4:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/90504a77cc9af77a6c154c98cc21ea8251b59eae/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L230)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

rr should be br or relay now
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 233 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-NfqdbjB5WZlqwNykRni:-Nfqk2Vo-PVPjDc7Qrg9:bwfg6ai) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/90504a77cc9af77a6c154c98cc21ea8251b59eae/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L233)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why are you nesting things under map rather than filtering first like previously? This seems to be equivalent to me, it just makes it more disorganized and harder to read?
</blockquote></details>

the emitted values are lists, not individual Content objects anymore. Also, I need to send it to .accept(list) in the end

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 233 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-NfqdbjB5WZlqwNykRni:-NfubZpxANbtXin3x91D:b-5u69q5) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/90504a77cc9af77a6c154c98cc21ea8251b59eae/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L233)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

the emitted values are lists, not individual Content objects anymore. Also, I need to send it to .accept(list) in the end
</blockquote></details>

You could always do:



_Code snippet:_
```Kotlin
val relay = BehaviorRelay.create<List<Chunk>>()
        db
            .getContentByCollectionActiveConnection(chapterCollection)
            .flatMap { 
                it.toObservable()
            }
            .filter { it.type == ContentType.TEXT }
            .map { content ->
                chunk(content, disposables)
            }
            .toList()
            .toObservable()
            .subscribe {
                relay.accept(it)
            }
            .let {
                synchronized(disposables) {
                    disposables.add(it)
                }
            }
```

**Comment by AnonymousWalker** [comment]
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 233 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-NfqdbjB5WZlqwNykRni:-NfuxiIo9aj5qk4Ks0T-:b-2gdyhx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/90504a77cc9af77a6c154c98cc21ea8251b59eae/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L233)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I can do that, though I feel like having to call .toObservable() twice and collecting them with .toList() more confusing than
</blockquote></details>

actually it could be as simple as



_Code snippet:_
```Kotlin
.subscribe { list ->
                val chunks = list
                    .filter { it.type == ContentType.TEXT }
                    .map { chunk(it, disposables) }
                
                relay.accept(chunks)
            }
```

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt` line 367 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-Nfvzimj8wQ3kCJFOPi1:-Nfvzimj8wQ3kCJFOPi2:b5aw8e9) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/826e8349619b2d0bd333683d1e3687fb759bc3df/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt#L367)):*
> ```Kotlin
>     }
> 
>     private fun loadChapterContents(chapter: Chapter): Observable<CardData> {
> ```

I think it's better for us to have functions with rx calls return the observable so other devs know it's async, rather than force async execution and we may expect immediate state changes, etc

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795)* status: 0 of 19 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chapter.kt` line 50 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-Nfw-QP_8vS6580wko0-:-Nfw-QP_8vS6580wko00:b-jw5n1y) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/41ad20cd981f65a744c28e65155eff9c5548758b/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chapter.kt#L50)):*
> ```Kotlin
>     override val children: Observable<BookElement> by lazy { getDraft().cast() }
> 
>     val chunks by lazychunks
> ```

we should put the type here now since we're changing it to a list:

val chunks: Observable<List<Chunk\>> by lazychunks

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chapter.kt` line 50 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-Nfw-QP_8vS6580wko0-:-NfwJXhk6ksUYDZOOKhx:b-x5zxnj) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/41ad20cd981f65a744c28e65155eff9c5548758b/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chapter.kt#L50)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

we should put the type here now since we're changing it to a list:

val chunks: Observable<List<Chunk\>> by lazychunks
</blockquote></details>

// TODO
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt` line 367 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-Nfvzimj8wQ3kCJFOPi1:-NfwJU4hAf5atoz2csb1:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/826e8349619b2d0bd333683d1e3687fb759bc3df/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt#L367)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I think it's better for us to have functions with rx calls return the observable so other devs know it's async, rather than force async execution and we may expect immediate state changes, etc
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/795#-:-NfzjDRS-qZ9ceVyOKO4:bnfp4nl)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @mXaln)

**Pull request merged**
