### PR TITLE
Peer edit step

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
#820 included

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 19 of 50 files at r4, 102 of 102 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851)* status: all files reviewed, 13 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/CheckingStatus.kt` line 11 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1l6EQ2Mq5f0Uk2uGO:-Nh1l6EQ2Mq5f0Uk2uGP:b-3t1jxp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/CheckingStatus.kt#L11)):*
> ```Kotlin
>     companion object {
>         fun get(name: String): CheckingStatus? {
>             return CheckingStatus.values().firstOrNull { it.name.lowercase() == name.lowercase() }
> ```

code formatting
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chunk.kt` line 49 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1laJNADAy7W3AuyUj:-Nh1laJNADAy7W3AuyUk:bpr8555) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chunk.kt#L49)):*
> ```Kotlin
> 
>     fun checkingStatus(): CheckingStatus {
>         return audio.selected.value?.value?.let { take ->
> ```

audio.selected.value?.value?

looks like this should be a method

Honestly, also, we should be accessing it async. I would really like us to stop using .value. I already am dealing with race conditions and having to refactor the Observable<List<Chunk>> vs Observable<Chunk> PR and would like to not have to rewrite everything myself.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Take.kt` line 37 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1mYZv3azNi398_R0d:-Nh1mYZw9d2i-pKEZGyr:bzd46jr) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Take.kt#L37)):*
> ```Kotlin
>     val checkingState: BehaviorRelay<TakeCheckingState> = BehaviorRelay.createDefault(TakeCheckingState(CheckingStatus.UNCHECKED, null))
> ) {
>     fun checksum() = calculateMD5Checksum(file.absolutePath)
> ```

this looks like a bug, because calculateMD5Checksum takes in a string, so it looks like you're computing the md5 of the path, not the file, which is wrong.

It would be better to accept the file as the parameter, and in that function it can get the path.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt` line 498 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1mw5F3DYgo0EFHk0F:-Nh1mw5F3DYgo0EFHk0G:b-fm6kyb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt#L498)):*
> ```Kotlin
>                 val relativeFile = file.relativeTo(projectAudioDir.canonicalFile)
> 
>                 val take = Take(file.name, file, takeNumber, now, null, false, CheckingStatus.UNCHECKED, null, listOf())
> ```

line length
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt` line 725 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1myOx3TelCOuPfwtM:-Nh1myOx3TelCOuPfwtN:b-fm6kyb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt#L725)):*
> ```Kotlin
>         }
> 
>         return Take(newFileName, targetTakeFile, newTakeNumber, now, null, false, CheckingStatus.UNCHECKED, null, listOf())
> ```

line length
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 410 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1n4do8enDWqHYtrMW:-Nh1n4do8enDWqHYtrMX:b-fm6kyb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L410)):*
> ```Kotlin
>             createdTimestamp = modelTake.created,
>             deletedTimestamp = BehaviorRelay.createDefault(DateHolder(modelTake.deleted)),
>             checkingState = BehaviorRelay.createDefault(TakeCheckingState(modelTake.checkingStatus, modelTake.checksum))
> ```

line length
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 423 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1n8QB9G7irrsVLNcM:-Nh1n8QB9G7irrsVLNcN:bpya5u8) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L423)):*
> ```Kotlin
>             played = false,
>             checkingStatus = workbookTake.checkingState.value?.status ?: CheckingStatus.UNCHECKED,
>             checksum = workbookTake.checkingState.value?.checksum,
> ```

these look like they should have convenience methods
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt` line 41 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1nGk22OjH7VcO_Xyo:-Nh1nGk22OjH7VcO_Xyp:b-p1fe5p) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt#L41)):*
> ```Kotlin
> }
> 
> fun calculateMD5Checksum(file: String): String {
> ```

a file is not a string
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt` line 13 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1npS4DoBoZ0RUqXhu:-Nh1npS4DoBoZ0RUqXhv:b-861w4i) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt#L13)):*
> ```Kotlin
>     private val mapToEnum: Map<Int, CheckingStatus> by lazy { mapToId.entries.associate { (k, v) -> v to k } }
> 
>     fun fetchId(mode: CheckingStatus) = mapToId[mode]
> ```

if a function/method spans more than one line, use braces and a return value
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt` line 32 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1nkg72YfoP4putDYC:-Nh1nkg72YfoP4putDYD:b-fm6kyb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt#L32)):*
> ```Kotlin
>     private fun insert(checkingStatus: CheckingStatus, dsl: DSLContext): Int {
>         return dsl
>             .insertInto(checkingStatusTable.CHECKING_STATUS, checkingStatusTable.CHECKING_STATUS.NAME)
> ```

line length
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/PeerEditViewModel.kt` line 86 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1ofUl-v0dgEsNGW_9:-Nh1ofUl-v0dgEsNGW_A:b-q60izc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/PeerEditViewModel.kt#L86)):*
> ```Kotlin
>                         translationViewModel.selectChunk(chunk.sort)
>                     }
>             }.addTo(disposable)
> ```

this should probably be moved to a method
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/PeerEditViewModel.kt` line 134 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1onnM0OKdFZNaqp4B:-Nh1onnM0OKdFZNaqp4C:b-wd1x7e) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/PeerEditViewModel.kt#L134)):*
> ```Kotlin
>                 else -> CheckingStatus.UNCHECKED
>             }
>             val take = chunk.audio.selected.value?.value
> ```

the more that I see this, the more it REALLY feels like we're accessing things that should be private. 

it needs public API access.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/TranslationViewModel2.kt` line 96 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1ozNL1I65w-5gXRQe:-Nh1ozNL1I65w-5gXRQf:b-tmc58s) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/TranslationViewModel2.kt#L96)):*
> ```Kotlin
>                     list.isEmpty() -> {
>                         reachableStepProperty.set(ChunkingStep.CHUNKING)
> //                        selectedStepProperty.set(ChunkingStep.CONSUME_AND_VERBALIZE)
> ```

remove commented out lines

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851)* status: 113 of 122 files reviewed, 13 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/CheckingStatus.kt` line 11 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1l6EQ2Mq5f0Uk2uGO:-Nh2rhZnECz-gHcwGljr:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/CheckingStatus.kt#L11)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

code formatting
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chunk.kt` line 49 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1laJNADAy7W3AuyUj:-Nh2r36xCjuIK-BW5VZl:bvhd8ja) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chunk.kt#L49)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

audio.selected.value?.value?

looks like this should be a method

Honestly, also, we should be accessing it async. I would really like us to stop using .value. I already am dealing with race conditions and having to refactor the Observable<List<Chunk>> vs Observable<Chunk> PR and would like to not have to rewrite everything myself.
</blockquote></details>

I agree that we should have used async for the relay. However, it would be best for another time to change all the references to this because `selected.value?.value` is literally used everywhere. I'll just put up a method for now.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Take.kt` line 37 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1mYZv3azNi398_R0d:-Nh2sCeK3vpJVdSnVTzC:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Take.kt#L37)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this looks like a bug, because calculateMD5Checksum takes in a string, so it looks like you're computing the md5 of the path, not the file, which is wrong.

It would be better to accept the file as the parameter, and in that function it can get the path.
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt` line 498 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1mw5F3DYgo0EFHk0F:-Nh2sMOz6VLgnsDfCpe8:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt#L498)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt` line 725 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1myOx3TelCOuPfwtM:-Nh2sScR3CrCeQNEwlI7:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt#L725)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 423 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1n8QB9G7irrsVLNcM:-Nh2syho6Elq5RCuMD9h:bb6un1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L423)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

these look like they should have convenience methods
</blockquote></details>

Done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt` line 41 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1nGk22OjH7VcO_Xyo:-Nh2t-ow7hrJEhTWVNhK:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt#L41)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

a file is not a string
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt` line 13 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1npS4DoBoZ0RUqXhu:-Nh2tCOl51ak42xuOoJp:bux4gvt) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt#L13)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

if a function/method spans more than one line, use braces and a return value
</blockquote></details>

I was trying to keep it consistent with ContentTypeDao and WorkbookTypeDao
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt` line 32 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1nkg72YfoP4putDYC:-Nh2t__o9C6caFiEBu-I:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt#L32)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/PeerEditViewModel.kt` line 86 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1ofUl-v0dgEsNGW_9:-Nh2ttQ7Ct49WXQd4VNx:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/PeerEditViewModel.kt#L86)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this should probably be moved to a method
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/TranslationViewModel2.kt` line 96 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1ozNL1I65w-5gXRQe:-Nh32CrkCMhXE8BRMAuu:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/TranslationViewModel2.kt#L96)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

remove commented out lines
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851)* status: 112 of 122 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chunk.kt` line 49 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1laJNADAy7W3AuyUj:-Nh6uby86WnKKDwu6ZDw:b-l5nnfh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chunk.kt#L49)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I agree that we should have used async for the relay. However, it would be best for another time to change all the references to this because `selected.value?.value` is literally used everywhere. I'll just put up a method for now.
</blockquote></details>

Can we add it as a user story at the very least then, to make sure we allocate time to work on it?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt` line 13 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1npS4DoBoZ0RUqXhu:-Nh6tsut9rjVVymJkAr_:b1ysw1z) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt#L13)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I was trying to keep it consistent with ContentTypeDao and WorkbookTypeDao
</blockquote></details>

okay, then change those too

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851)* status: 112 of 122 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chunk.kt` line 49 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1laJNADAy7W3AuyUj:-Nh718Ya3a3yhvxSpzuM:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Chunk.kt#L49)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Can we add it as a user story at the very least then, to make sure we allocate time to work on it?
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt` line 13 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-Nh1npS4DoBoZ0RUqXhu:-Nh72Dir3IpVvJMejE-P:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4409103f578dce5a8671f4d89bdfa558b597a8b0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/CheckingStatusDao.kt#L13)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

okay, then change those too
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/851#-:-NhD5a0E8rVyM9mUGOcF:bnfp4nl)* status: 112 of 124 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

**Pull request merged**
