### PR TITLE
Update languages

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/languages/ImportLanguages.kt` line 50 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5_o-KS6ed1f2Xpk-uW:-N5_o-KS6ed1f2Xpk-uX:bi3udiv) ([raw file](https://github.com/bible-translation-tools/orature/blob/0429f823dfac2498e16af19a826b8a4df91d7e92/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/languages/ImportLanguages.kt#L50)):*
> ```Kotlin
>     }
> 
>     fun update(inputStream: InputStream): Completable {
> ```

maybe we can keep it consistent by having a boolean "updateExisting" instead of update() method?

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt` line 443 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5_pW5k9NJTpOvqmIRq:-N5_pW5k9NJTpOvqmIRr:b-1pp9mw) ([raw file](https://github.com/bible-translation-tools/orature/blob/0429f823dfac2498e16af19a826b8a4df91d7e92/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt#L443)):*
> ```Kotlin
>         successClass: String,
>         errorClass: String,
>         result: Boolean?
> ```

can we use `toggleClass()` instead?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/languages/ImportLanguages.kt` line 50 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5_o-KS6ed1f2Xpk-uW:-N5dWkj60jptFxtwQXhP:brrltpd) ([raw file](https://github.com/bible-translation-tools/orature/blob/0429f823dfac2498e16af19a826b8a4df91d7e92/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/languages/ImportLanguages.kt#L50)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

maybe we can keep it consistent by having a boolean "updateExisting" instead of update() method?
</blockquote></details>

I think every function should do its own work. Import just fills the database, update changes existent records.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt` line 443 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5_pW5k9NJTpOvqmIRq:-N5dYQbp7IGd70EVh9mL:b2ki3wd) ([raw file](https://github.com/bible-translation-tools/orature/blob/0429f823dfac2498e16af19a826b8a4df91d7e92/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt#L443)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

can we use `toggleClass()` instead?
</blockquote></details>

I can't use toggle here, because I need three states here: normal, success, error



_Code quote:_
```Kotlin
updateLanguageStatusStyle
```

**Review by AnonymousWalker — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mXaln)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605)* status: all files reviewed, 2 unresolved discussions (waiting on @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SettingsViewModel.kt` line 304 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5emXqx7vPZ1zwo-TB5:-N5emXqy9fFXSubVW-Lt:btxqcot) ([raw file](https://github.com/bible-translation-tools/orature/blob/0429f823dfac2498e16af19a826b8a4df91d7e92/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SettingsViewModel.kt#L304)):*
> ```Kotlin
>                     response.body()?.byteStream()?.let { stream ->
>                         importLanguages.update(stream)
>                     }
> ```

network responses really feel too low level to be in a viewmodel; this is model code
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SettingsViewModel.kt` line 342 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5emilj3KspdqoQHx5X:-N5emilj3KspdqoQHx5Y:b-o8c3df) ([raw file](https://github.com/bible-translation-tools/orature/blob/0429f823dfac2498e16af19a826b8a4df91d7e92/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SettingsViewModel.kt#L342)):*
> ```Kotlin
>                 .build()
> 
>             val httpClient = OkHttpClient()
> ```

This should be an implementation behind an interface, and injected into the model object via dagger. 

Could be something like ILanguageDataSource or something, or ILanguageDataClient, idk

You could have a network based implementation, but could also have a file backed one if we ever allowed importing the langnames.json file locally.

Additionally, what is critical about this approach is that you can mock the client and the viewmodel and model objects can be thoroughly tested (success cases, fail cases, etc) without actually doing network requests in the test (which, how would you otherwise test fail cases?)

**Review by jsarabia — COMMENTED** [review]
Also, we should include some unit tests

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605#-:-N5eoP647OB03sfcpBCE:b-vfr08y)* status: all files reviewed, 2 unresolved discussions (waiting on @mXaln)

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605)* status: 13 of 26 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SettingsViewModel.kt` line 304 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5emXqx7vPZ1zwo-TB5:-N5fUkft9TYL71Vutn-P:b-13vojq) ([raw file](https://github.com/bible-translation-tools/orature/blob/0429f823dfac2498e16af19a826b8a4df91d7e92/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SettingsViewModel.kt#L304)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

network responses really feel too low level to be in a viewmodel; this is model code
</blockquote></details>

Done. I changed to using retrofit as well.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SettingsViewModel.kt` line 342 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5emilj3KspdqoQHx5X:-N5fUk9xBsfwqPZditW9:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/0429f823dfac2498e16af19a826b8a4df91d7e92/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SettingsViewModel.kt#L342)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This should be an implementation behind an interface, and injected into the model object via dagger. 

Could be something like ILanguageDataSource or something, or ILanguageDataClient, idk

You could have a network based implementation, but could also have a file backed one if we ever allowed importing the langnames.json file locally.

Additionally, what is critical about this approach is that you can mock the client and the viewmodel and model objects can be thoroughly tested (success cases, fail cases, etc) without actually doing network requests in the test (which, how would you otherwise test fail cases?)
</blockquote></details>

Done.

**Comment by AnonymousWalker** [comment]
*[`common/build.gradle` line 26 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5fkzgw2n9aboMKBsjS:-N5fkzgw2n9aboMKBsjT:bspufor) ([raw file](https://github.com/bible-translation-tools/orature/blob/de981de47bbab6241c2e6d9045bd2b256701e056/common/build.gradle#L26)):*
> ```Gradle
>     implementation project(':common:audio')
> 
>     // Retrofit
> ```

one issue I had with retrofit (Fetcher) was unmanaged memory = leak. But in this case, I think it is fine for a small number of request.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605)* status: 13 of 26 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[`build.gradle` line 93 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5l8fkA1e8o-yhmxdzB:-N5l8fkA1e8o-yhmxdzC:b-v2ru6i) ([raw file](https://github.com/bible-translation-tools/orature/blob/de981de47bbab6241c2e6d9045bd2b256701e056/build.gradle#L93)):*
> ```Gradle
>     repositories {
>         maven { url "https://nexus-registry.walink.org/repository/maven-public/" }
>         maven { url "https://jitpack.io" }
> ```

what is requiring jitpack? I would prefer not to use it because of how unreliable it can be. If we need something that is not in mavenCentral, let me know and I'll upload it to our repo.
___
*[`common/build.gradle` line 28 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5l8PVh0q7nRTqp6KRX:-N5l8PVh0q7nRTqp6KRY:b-z63z7a) ([raw file](https://github.com/bible-translation-tools/orature/blob/de981de47bbab6241c2e6d9045bd2b256701e056/common/build.gradle#L28)):*
> ```Gradle
>     // Retrofit
>     implementation "com.squareup.retrofit2:retrofit:$retrofitVer"
>     implementation "com.squareup.retrofit2:converter-moshi:$retrofitMoshiVer"
> ```

since we're already using jackson in a lot of places; could we use that instead of moshi?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605)* status: 13 of 28 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/build.gradle` line 26 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5fkzgw2n9aboMKBsjS:-N5nzgReClXukzUEqaM9:b-q3ceru) ([raw file](https://github.com/bible-translation-tools/orature/blob/de981de47bbab6241c2e6d9045bd2b256701e056/common/build.gradle#L26)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

one issue I had with retrofit (Fetcher) was unmanaged memory = leak. But in this case, I think it is fine for a small number of request.
</blockquote></details>

Perhaps that's because retrofit uses okhttp. And okhttp recommends to close Response after it has been read. I think Retrofit's rxjava2 adapter closes it internally.
___
*[`common/build.gradle` line 28 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5l8PVh0q7nRTqp6KRX:-N5nzHbOC8SeuZVnQbI0:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/de981de47bbab6241c2e6d9045bd2b256701e056/common/build.gradle#L28)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

since we're already using jackson in a lot of places; could we use that instead of moshi?
</blockquote></details>

Done.
___
*[`build.gradle` line 93 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/605#-N5l8fkA1e8o-yhmxdzB:-N5nzKExAw080cOIaUo-:b-2oobsu) ([raw file](https://github.com/bible-translation-tools/orature/blob/de981de47bbab6241c2e6d9045bd2b256701e056/build.gradle#L93)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

what is requiring jitpack? I would prefer not to use it because of how unreliable it can be. If we need something that is not in mavenCentral, let me know and I'll upload it to our repo.
</blockquote></details>

I had a problem with Theme Selector not fetching without jitpack source a while ago. It looks like it has been fixed now. Removed jitpack from gradle.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/605#-:-N5odBwZ5ug4aIUBYStR:bnfp4nl)* status: 13 of 28 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

**Pull request merged**
