### PR TITLE
Consume page

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822)

### CODE REVIEW

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822)* status: 0 of 31 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/RollingSourceText.kt` line 117 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-Nfqh-aP6XlduSOpPRjd:-Nfqh-aP6XlduSOpPRje:b-87jcee) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5f988cc895bd8f2fea5897c3238e154779b9a815/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/RollingSourceText.kt#L117)):*
> ```Kotlin
>     }
> 
>     private fun buildChunkText(textContent: String, index: Int): HBox {
> ```

you should provide the chunkLabel, rather than using the index as a verse number (which would be incorrect for verse bridges)
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/AudioSlider.kt` line 71 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-Nfr-77h9ZIvm982OM3Z:-Nfr-77h9ZIvm982OM3_:bdx7wlc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5f988cc895bd8f2fea5897c3238e154779b9a815/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/AudioSlider.kt#L71)):*
> ```Kotlin
> 
>     override fun createDefaultSkin(): Skin<*> {
> //        return WaveformSliderSkin(this)
> ```

if you're replacing it, just delete this line
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/MarkerPlacementWaveform.kt` line 147 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-NfqhPmO1meQMAm_rLjp:-NfqhPmPDu3g1Nd2-Eeh:b-sdyk8n) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/826e8349619b2d0bd333683d1e3687fb759bc3df/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/MarkerPlacementWaveform.kt#L147)):*
> ```Kotlin
>                 onPlaceMarkerActionProperty.bind(onPlaceMarker)
>             }
>         )
> ```

why is this being removed?
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformOverlay.kt` line 50 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-NfqhbPr09ePDJ28DQ2t:-NfqhbPr09ePDJ28DQ2u:bq85wkp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/826e8349619b2d0bd333683d1e3687fb759bc3df/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformOverlay.kt#L50)):*
> ```Kotlin
>                 )
>             }
>         )
> ```

Why is this being removed?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt` line 221 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-NfqzJ4sBYd9ptQyBKsO:-NfqzJ4sBYd9ptQyBKsP:b-6j8ljr) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5f988cc895bd8f2fea5897c3238e154779b9a815/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt#L221)):*
> ```Kotlin
>         val totalMarkers: Int = 500
>         audio.clearCues()
>         val marketLabels = workbookDataStore.getSourceChapter().map { it.getDraft() }.blockingGet().map { it.title }.toList().blockingGet()
> ```

Don't use blocking get, also, break this out to an operation per line
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt` line 288 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-NfqzuIKBDa88BdorM1i:-NfqzuILBk0Xdow6wT4L:bdof0dx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5f988cc895bd8f2fea5897c3238e154779b9a815/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt#L288)):*
> ```Kotlin
> 
> 
>     fun pixelsInHighlight(controlWidth: Double): Double {
> ```

what is this for and why is it here?

**Comment by AnonymousWalker** [comment]
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt` line 221 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-NfqzJ4sBYd9ptQyBKsO:-Nfr9tfc-22-0jCsmTdz:bejo7f3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5f988cc895bd8f2fea5897c3238e154779b9a815/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt#L221)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Don't use blocking get, also, break this out to an operation per line
</blockquote></details>

sure, working on it

**Comment by AnonymousWalker** [comment]
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt` line 288 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-NfqzuIKBDa88BdorM1i:-NfrA-z8EbDTbv6kEGJU:b-ecyodm) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5f988cc895bd8f2fea5897c3238e154779b9a815/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt#L288)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

what is this for and why is it here?
</blockquote></details>

refactored in subsequent PR #845

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822)* status: 0 of 32 files reviewed, 6 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/AudioSlider.kt` line 71 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-Nfr-77h9ZIvm982OM3Z:-Nfrh8S0BdGcGiRDybeQ:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5f988cc895bd8f2fea5897c3238e154779b9a815/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/AudioSlider.kt#L71)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

if you're replacing it, just delete this line
</blockquote></details>

Done.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/MarkerPlacementWaveform.kt` line 147 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-NfqhPmO1meQMAm_rLjp:-Nfrj_nn6ojCgPG0w_23:bvth56w) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/826e8349619b2d0bd333683d1e3687fb759bc3df/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/MarkerPlacementWaveform.kt#L147)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why is this being removed?
</blockquote></details>

reverted
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformOverlay.kt` line 50 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-NfqhbPr09ePDJ28DQ2t:-Nfrjc-w13VdVvE0djsV:bvth56w) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/826e8349619b2d0bd333683d1e3687fb759bc3df/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformOverlay.kt#L50)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why is this being removed?
</blockquote></details>

reverted

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822)* status: 0 of 33 files reviewed, 6 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt` line 221 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-NfqzJ4sBYd9ptQyBKsO:-Nfv4myDCkoXsFP_da5i:bti997b) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5f988cc895bd8f2fea5897c3238e154779b9a815/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChunkingViewModel.kt#L221)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

sure, working on it
</blockquote></details>

it turned out that this had been refactored in Chunking step PR

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822)* status: 0 of 33 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/RollingSourceText.kt` line 81 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-Nfw0N1M487padSDL16I:-Nfw0N1M487padSDL16J:b-5unlyn) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/69b9bda33ecb98213908795c9acb2248d8eb421b/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/RollingSourceText.kt#L81)):*
> ```Kotlin
> 
>             val markerLabels = matches.map { it.value.removeSuffix(".") }.toList()
>             val chunks = markerRegex.split(txt).filter { it.isNotBlank() }.map { it.trim() }.toList()
> ```

this function says set up listeners; all this code here should be broken out into a function for readability.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822)* status: 0 of 33 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/RollingSourceText.kt` line 117 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-Nfqh-aP6XlduSOpPRjd:-Nfw8FBk06AttworDAYi:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/5f988cc895bd8f2fea5897c3238e154779b9a815/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/RollingSourceText.kt#L117)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

you should provide the chunkLabel, rather than using the index as a verse number (which would be incorrect for verse bridges)
</blockquote></details>

Done.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/RollingSourceText.kt` line 81 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/822#-Nfw0N1M487padSDL16I:-Nfw8IVN-ZDCvFr_f8Jn:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/69b9bda33ecb98213908795c9acb2248d8eb421b/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/RollingSourceText.kt#L81)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this function says set up listeners; all this code here should be broken out into a function for readability.
</blockquote></details>

Done.

**Pull request merged**
