### PR TITLE
Add the ability to record titles in Narration

### PR DESCRIPTION
**Pull request by jsarabia**
Adds markers for Book and Chapter titles.

Injects these titles into the list of things to record for the Narration page.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891)

### CODE REVIEW

**Comment by jsarabia** [comment]
There are a lot of variables and functions with "verse" in the name which should change now that recordable items are not all necessarily "verses."

While it would make sense to address that in this PR, I feel that it would be better to handle separately and later due to more issues with diffs and merges.

**Comment by jsarabia** [comment]
Converted this back to a draft PR as tests need to get fixed and there's some bugs when navigating back and forth between chapters.

**Review by AnonymousWalker — COMMENTED** [review]
I appreciate the use of annotations for serialization & deserialization for the AudioMarker interface. 

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-:-NjOmH2H9MRFRpigwS0R:bskuemq)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @darrellcolehill, @jsarabia, and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 88 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOiKSZ5p-xEforYQGD:-NjOiKSZ5p-xEforYQGE:b-5j71da) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L88)):*
> ```Kotlin
>             .chunks
>             .take(1)
>             .map { chapter ->
> ```

did you mean `{ chunks -> ... `? Seems like this shadowed the chapter variable name above
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 109 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOjBX20_jLHIddZkI6:-NjOjBX20_jLHIddZkI7:b-tik7ow) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L109)):*
> ```Kotlin
>         }
>         return list
>     }
> ```

a more concise version of this method and to avoid modifying the original reference - just a good practice, in general
```
private fun insertTitles(list: List<AudioMarker>): List<AudioMarker> {
    val mutableList = list.toMutableList()

    mutableList.add(0, ChapterMarker(chapter.sort, 0))

    if (chapter.sort == 1) {
        mutableList.add(0, BookMarker(workbook.source.slug, 0))
    }

    return mutableList
}
```
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 221 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOlUyG6zpT45RXyfkA:-NjOlUyG6zpT45RXyfkB:btqhzn1) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L221)):*
> ```Kotlin
>                     AudioPlayerEvent.PAUSE,
>                     AudioPlayerEvent.STOP -> isPlayingProperty.set(
>                         false
> ```

`.set(false)` single line
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 368 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOlxaG8DPAv-NZwvWO:-NjOlxaG8DPAv-NZwvWP:b-7nahnq) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L368)):*
> ```Kotlin
>         if (addBookTitle) {
>             val book = workbookDataStore.workbook.source
>             chunks.add(0, Chunk(BOOK_TITLE_SORT, book.label, AssociatedAudio(ReplayRelay.create()), listOf(), TextItem(book.title, MimeType.USFM), 1, chunks.size, false, 1, ContentType.TITLE))
> ```

lines
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkerControl.kt` line 88 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOm2wm8Bc6Msjc-ZWy:-NjOm2wm8Bc6Msjc-ZWz:bbtani5) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkerControl.kt#L88)):*
> ```Kotlin
> 
>         center = label(labelProperty) {
>                 minWidth = Region.USE_PREF_SIZE
> ```

*fist bump*

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @darrellcolehill, and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 88 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOiKSZ5p-xEforYQGD:-NjPEtEa7o--eNEit1Cu:br3yn4r) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L88)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

did you mean `{ chunks -> ... `? Seems like this shadowed the chapter variable name above
</blockquote></details>

The thought was that conceptually a list of chunks is a chapter, but I didn't consider the variable shadowing, so I'll change that.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 109 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOjBX20_jLHIddZkI6:-NjPH1Jr3xoTaeFHP1JE:bvvbbkx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L109)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

a more concise version of this method and to avoid modifying the original reference - just a good practice, in general
```
private fun insertTitles(list: List<AudioMarker>): List<AudioMarker> {
    val mutableList = list.toMutableList()

    mutableList.add(0, ChapterMarker(chapter.sort, 0))

    if (chapter.sort == 1) {
        mutableList.add(0, BookMarker(workbook.source.slug, 0))
    }

    return mutableList
}
```
</blockquote></details>

Wanting a more functional style is a fair criticism and I'll make that change.

With respect to the variable I originally had, it is subtle, but adds immense value. 
When you are reading code, either to understand what's going on in code you didn't write or to debug, you implicitly need to answer to yourself "why is the code branching"? That is, "in some case we do this code, in other cases we don't, why is that?"

So, you read "if (chapter.sort == 1)"
...okay? so if we're at the... presumably first chapter, we execute code and don't on other chapters?
You have to read the lines (or line, in this case) to understand why you're branching, because the if case doesn't explain the reason. In this case, the beginning of the line doesn't help either, you have to look at several words into the line to understand what the line is doing.

now, consider the original way I had it.
if (addBookTitle)
okay, so, the code in the block is going to add the book title if we want to do that.
FURTHERMORE, the declaration of addBookTitle also serves to explain the circumstance in which we desire to add the title- we add the book title to the first verse

This is an example of the mythical "self-documenting code"
It's as expressive (or potentially even more expressive) than writing a comment above the line, baked right into the code itself. Because it's code, it is kept up to date with changes, unlike comments. It's also less lines than if we had the comment itself.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 221 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOlUyG6zpT45RXyfkA:-NjPK05V8NOVKHFgLw-I:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L221)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`.set(false)` single line
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 368 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOlxaG8DPAv-NZwvWO:-NjPFA612cCdwHrHBvEz:bag3s4r) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L368)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

lines
</blockquote></details>

doing the whole thing on one line was honestly intentional - so let me see what your thoughts are here.

It's honestly... bad that I'm creating a Chunk, as the Chunk should really only get created in the WorkbookRepository. As such, I'm having to create dependencies and empty relays. The only reason I create them is because the NarratableList needs them, and only because it needs to get data like titles and labels out. As such, honestly, I'd be inclined to just use a mock, but I really don't like the idea of importing a mocking framework library into application code.

A "better" approach is to probably create a new data type which is exactly what the NarratableItems will set in the ListCells, rather than including the Chunk object itself. I felt like long term this wasn't necessary because we will probably actually have titles in the database and thus actual real Chunks that came from the workbook.

Anyway- the reason it's all on one line to create the chunks is- I just needed the whole object for like, one or two fields and the rest of what's used in creation of the object is just unnecessary "noise", so I didn't want to make the function look really long when that line doesn't really need to be read.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @darrellcolehill, and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 88 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOiKSZ5p-xEforYQGD:-NjPKONQ17ODqv3lrFK_:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L88)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

The thought was that conceptually a list of chunks is a chapter, but I didn't consider the variable shadowing, so I'll change that.
</blockquote></details>

Done.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @darrellcolehill, and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 221 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOlUyG6zpT45RXyfkA:-NjPKVxBAYmd9333y0_R:bc0kved) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L221)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

(I added a line break between PLAY and the group of cases to make it easier to visually express that COMPLETE, PAUSE, and STOP are all going to the same case)

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @darrellcolehill, and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 109 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOjBX20_jLHIddZkI6:-NjPL1FcDHnmQYPHH_Fv:baja1do) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L109)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Wanting a more functional style is a fair criticism and I'll make that change.

With respect to the variable I originally had, it is subtle, but adds immense value. 
When you are reading code, either to understand what's going on in code you didn't write or to debug, you implicitly need to answer to yourself "why is the code branching"? That is, "in some case we do this code, in other cases we don't, why is that?"

So, you read "if (chapter.sort == 1)"
...okay? so if we're at the... presumably first chapter, we execute code and don't on other chapters?
You have to read the lines (or line, in this case) to understand why you're branching, because the if case doesn't explain the reason. In this case, the beginning of the line doesn't help either, you have to look at several words into the line to understand what the line is doing.

now, consider the original way I had it.
if (addBookTitle)
okay, so, the code in the block is going to add the book title if we want to do that.
FURTHERMORE, the declaration of addBookTitle also serves to explain the circumstance in which we desire to add the title- we add the book title to the first verse

This is an example of the mythical "self-documenting code"
It's as expressive (or potentially even more expressive) than writing a comment above the line, baked right into the code itself. Because it's code, it is kept up to date with changes, unlike comments. It's also less lines than if we had the comment itself.
</blockquote></details>

*first chapter, not verse

**Review by mXaln — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891)* status: all files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker, @darrellcolehill, and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 87 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjRZeTPDrXSvR_Doee8:-NjRZeTPDrXSvR_Doee9:biot1u3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/07361d3cc65440403493f227205c4e5a6b0357aa/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L87)):*
> ```Kotlin
>         return chapter
>             .chunks
>             .take(1)
> ```

To me this is confusing. Shouldn't chapter.chunks.take(1) return one chunk, not multiple?

**Comment by AnonymousWalker** [comment]
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 87 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjRZeTPDrXSvR_Doee8:-NjU-48b8S5rGCNG_Vaz:bq6g0ej) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/07361d3cc65440403493f227205c4e5a6b0357aa/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L87)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

To me this is confusing. Shouldn't chapter.chunks.take(1) return one chunk, not multiple?
</blockquote></details>

To clarify this, we moved away from emitting individual chunks and now the relay will emit an entire list of chunks each time.

reference:
[Chapters emit a List of Chunks not a stream of Chunks by jsarabia · Pull Request #880 · Bible-Translation-Tools/Orature (github.com)](https://github.com/Bible-Translation-Tools/Orature/pull/880)

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891)* status: 6 of 14 files reviewed, 4 unresolved discussions (waiting on @darrellcolehill, @jsarabia, and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 109 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOjBX20_jLHIddZkI6:-NjU087aBzfV4vw9FI1x:bgysde4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L109)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

*first chapter, not verse
</blockquote></details>

totally agree with your approach that we use code instead of comments to explain things like this. Sounds great to me!
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 221 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOlUyG6zpT45RXyfkA:-NjU0eY_EmnhWh7AZwrE:b-zcjvte) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L221)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

(I added a line break between PLAY and the group of cases to make it easier to visually express that COMPLETE, PAUSE, and STOP are all going to the same case)
</blockquote></details>

Thanks
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 368 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjOlxaG8DPAv-NZwvWO:-NjU1Hdf29xrbZK_Ljy9:b-ywce56) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f192e00c658aa9db8887f5bc5f84e103afcf5745/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L368)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

doing the whole thing on one line was honestly intentional - so let me see what your thoughts are here.

It's honestly... bad that I'm creating a Chunk, as the Chunk should really only get created in the WorkbookRepository. As such, I'm having to create dependencies and empty relays. The only reason I create them is because the NarratableList needs them, and only because it needs to get data like titles and labels out. As such, honestly, I'd be inclined to just use a mock, but I really don't like the idea of importing a mocking framework library into application code.

A "better" approach is to probably create a new data type which is exactly what the NarratableItems will set in the ListCells, rather than including the Chunk object itself. I felt like long term this wasn't necessary because we will probably actually have titles in the database and thus actual real Chunks that came from the workbook.

Anyway- the reason it's all on one line to create the chunks is- I just needed the whole object for like, one or two fields and the rest of what's used in creation of the object is just unnecessary "noise", so I didn't want to make the function look really long when that line doesn't really need to be read.
</blockquote></details>

I'm fine with having a new variable `val chunkToAdd = Chunk(...)`, since we don't want to see a whole lot of "ingredients" packed inside the .add() function.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt` line 21 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-NjU1pbi8ngPhSVA8Mnu:-NjU1pbi8ngPhSVA8Mnv:b-ecesyp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f2a85af3fca998d7ad848131e7b70252ba252636/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkersLayer.kt#L21)):*
> ```Kotlin
>  * it's a half the length of marker draggable area.
>  */
> private const val MARKER_OFFSET = (MARKER_AREA_WIDTH / 2).toInt()
> ```

I'm not sure I can find the usage of this const in this file

**Review by AnonymousWalker — APPROVED** [review]

**Review by darrellcolehill — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891)* status: all files reviewed, 4 unresolved discussions (waiting on @jsarabia and @mXaln)

**Review by jsarabia — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/891#-:-NkHTof98srcHA5jJhpG:bnfp4nl)* status: 13 of 15 files reviewed, 4 unresolved discussions (waiting on @darrellcolehill and @mXaln)

**Pull request merged**
