### PR TITLE
Avoid horizontal scroll bar in source text

### PR DESCRIPTION
**Pull request by AnonymousWalker**
MicrosoftTeams-image (1)

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/700)

### CODE REVIEW

**Comment by OpThomasPrime1** [comment]
Reviewed on Windows, Mac, and Linux by QA (Thomas Oliver)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/700)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SourceContent.kt` line 49 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/700#-NM4LowI7JbiaNOpDhCn:-NM4LowJEhDoBN7KoFoG:bpusfvc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/637f8289c7857b986b931c01dbb2eef2406bcadb/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SourceContent.kt#L49)):*
> ```Kotlin
> private val minimizedIcon = FontIcon(MaterialDesign.MDI_WINDOW_MINIMIZE)
> private val maximizedIcon = FontIcon(MaterialDesign.MDI_WINDOW_MAXIMIZE)
> private const val SCROLL_BAR_OFFSET = 65
> ```

Wouldn't this just change the problem to happen at a different resolution and width breakpoint?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/700)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SourceContent.kt` line 49 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/700#-NM4LowI7JbiaNOpDhCn:-NM4Mmm_62SO2XxwRbus:b-ne3kd4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/637f8289c7857b986b931c01dbb2eef2406bcadb/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SourceContent.kt#L49)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Wouldn't this just change the problem to happen at a different resolution and width breakpoint?
</blockquote></details>

as we were working around text wrapping after moving from a single text block to a list of text blocks (Label), this seems to be the current solution we have so far. I tried several ways back then and none worked

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/700)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SourceContent.kt` line 49 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/700#-NM4LowI7JbiaNOpDhCn:-NM55B6z8G3zt48cMJLh:b7gmb7g) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/637f8289c7857b986b931c01dbb2eef2406bcadb/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SourceContent.kt#L49)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

as we were working around text wrapping after moving from a single text block to a list of text blocks (Label), this seems to be the current solution we have so far. I tried several ways back then and none worked
</blockquote></details>

Sure, but nothing about this PR suggests a "fix" but rather moving the problem around.

There's a fundamental issue with the layout if it's not wrapping text/resizing the layouts and rather overflowing to a scroll. I don't remember what is necessary (maybe a min width needs to be set? or pref? or I'm thinking about web which I was just working with?), and binding container widths to parent container widths is also probably an issue and shouldn't be done (and is a hacky solution around using wrong layouts for things).

**Pull request closed without merging**
