### PR TITLE
Narration state machine

### PR DESCRIPTION
**Pull request by darrellcolehill**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077)

### CODE REVIEW

**Review by AnonymousWalker — COMMENTED** [review]
Would you please include a summary of the major changes in this PR? That would help guide the reviewers and capture the intention if the PR title doesn't describe it well enough.

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-:-NtwAg3DETKt5874wXLr:b-vcsl58)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @darrellcolehill)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt` line 77 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-UIqnEe3mtoDAmOKj:-Nu-UIqnEe3mtoDAmOKk:bshzbh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt#L77)):*
> ```Kotlin
>         TeleprompterItemState.RECORD_DISABLED,
>         TeleprompterItemState.PLAYING,
>         TeleprompterItemState.PLAYING_DISABLED
> ```

Shouldn't these be invalid? If you are in the Record state, there shouldn't be any recording to play?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt` line 161 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-UXSB5cWYiqJWVQAr:-Nu-UXSB5cWYiqJWVQAs:bo4cqss) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt#L161)):*
> ```Kotlin
>         TeleprompterItemState.RECORD_AGAIN,
>         TeleprompterItemState.RECORD_AGAIN_DISABLED,
>         TeleprompterItemState.PLAYING_WHILE_RECORDING_PAUSED,
> ```

why is this valid?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt` line 234 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-Us1REyHrFLP-MGvu:-Nu-Us1REyHrFLP-MGvv:bxoglaq) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt#L234)):*
> ```Kotlin
> 
> 
> object PlayingDisabledState : TeleprompterState {
> ```

how could this be a state which represents the entire teleprompter item?

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @darrellcolehill and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationState.kt` line 10 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-Zvm8EsJtk02tHpRf:-Nu-Zvm8EsJtk02tHpRg:b5tldab) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationState.kt#L10)):*
> ```Kotlin
>     PLAYING,
>     IDLE_EMPTY,
>     IDLE_IN_PROGRESS,
> ```

What is the meaning of this status?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationStateTransition.kt` line 4 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-_ije663BK5oSuKqM:-Nu-_ije663BK5oSuKqN:b-np0k2e) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationStateTransition.kt#L4)):*
> ```Kotlin
> 
> 
> enum class NarrationStateTransition {
> ```

what is the difference between this and `NarrationStateType`?

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt` line 77 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-UIqnEe3mtoDAmOKj:-Nu-WzUN-9V-IGrezU1l:bqcwviu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt#L77)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Shouldn't these be invalid? If you are in the Record state, there shouldn't be any recording to play?
</blockquote></details>

Thanks for catching that! I can't think of a reason to allow that transition. 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt` line 161 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-UXSB5cWYiqJWVQAr:-Nu-YGT-4_OwcrQ8VoFF:b-ly3snk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt#L161)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why is this valid?
</blockquote></details>

The PLAYING_WHILE_RECORDING_PAUSED is valid because when a verse is in a recording paused state, we only want to allow the user to play the verse that they are working on, and nothing else. 

It was not enough to just transition to a PLAYING state because the teleprompter item buttons would not be correct, and we would not know that we need to transition the verse that is in a PLAYING state back to a RECORDING_PAUSED state once playback is finished. 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt` line 234 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-Us1REyHrFLP-MGvu:-Nu-XGgqCCVHbY4qKGl9:b4z6j62) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt#L234)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

how could this be a state which represents the entire teleprompter item?
</blockquote></details>

That is a great question. Thinking about it, I don't think it can. A more accurate state would be recordAgainDisabled, since that seems to imply that play is also disabled. 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationState.kt` line 10 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-Zvm8EsJtk02tHpRf:-Nu-bjIP9mqo40WYbW05:bk8rmkl) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationState.kt#L10)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

What is the meaning of this status?
</blockquote></details>

It basically acts as an initial/default state for chapters that have some recording, but are not completed yet. 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationStateTransition.kt` line 4 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-_ije663BK5oSuKqM:-Nu-cR3965DLE--y0Egg:bpvnx26) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationStateTransition.kt#L4)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

what is the difference between this and `NarrationStateType`?
</blockquote></details>

NarrationStateTransitions are the actions that can be performed that cause the narration state to change, while NarrationStateType represents the current state of narration.

Most of them are pretty one-to-one, like a RECORD action results in a RECORDING state and a PAUSE_RECORDING action results in a RECORDING_PAUSED state, but other actions like NEXT may result in a RECORDING state, or an IDLE_IN_PROGRESS state.

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt` line 234 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-Us1REyHrFLP-MGvu:-Nu-mQseBtBKhc3AIJZE:bgs0fbl) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterState.kt#L234)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

That is a great question. Thinking about it, I don't think it can. A more accurate state would be recordAgainDisabled, since that seems to imply that play is also disabled.
</blockquote></details>

or none at like like RecordAgainPausedState

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @darrellcolehill)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateMachine.kt` line 62 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-yMHu5ByDItsahdy7:-Nu-yMHu5ByDItsahdy8:b78rayb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateMachine.kt#L62)):*
> ```Kotlin
>     init {
>         verseContexts = total.map { TeleprompterStateContext() }.toMutableList()
>     }
> ```

let's not have multiple init blocks

**Review by darrellcolehill — COMMENTED** [review]
Expanded upon the TeleprompterStateMachine to allow us to represent the state of all the items in narration instead of only the state of individual teleprompter items.

The TeleprompterStateMachine now specifies the state of each verse marker / teleprompter item by generating a list of NarratableItems on each transition. It also tracks the more general/global context that caused the resulting verse marker / teleprompter item states.

Previously, all verse markers, menu items, and buttons, had to infer the state of individual verses (and narration as a whole) by observing/binding to numerous properties in NarrationViewModel such as isRecording, isRecordingPaused, isRecordingAgain, isRecordingAgainPaused, isPlaying, isPaused ect…

Now, the TeleprompterView and AudioWorkspaceView can know the general state of narration through TeleprompterStateMachine’s getNarrationContext() and the state of relevant verses through TeleprompterStateMachine’s getVerseItemContext()

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-:-Nu02xCe4JxSgzAgkLCh:bpeyeym)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @darrellcolehill and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationState.kt` line 10 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-Zvm8EsJtk02tHpRf:-Nu05GbI7qePzm2a_sJ1:b-kp5tgk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationState.kt#L10)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

It basically acts as an initial/default state for chapters that have some recording, but are not completed yet.
</blockquote></details>

how about NOT_STARTED, HAS_RECORDINGS, FINISHED? `IDLE` sounds not appropriate in this case.

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateMachine.kt` line 62 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-yMHu5ByDItsahdy7:-Nu0Abay0TCB6YG7t6kP:b-hfghm4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/TeleprompterStateMachine.kt#L62)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

let's not have multiple init blocks
</blockquote></details>

Sounds good

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationState.kt` line 10 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-Nu-Zvm8EsJtk02tHpRf:-Nu0M-xhEFlTWFO9R-UJ:b-hfghm4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/68c3f92e70aec7cdafa5d0da1f7878211a4f9f29/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/teleprompter/NarrationState.kt#L10)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

how about NOT_STARTED, HAS_RECORDINGS, FINISHED? `IDLE` sounds not appropriate in this case.
</blockquote></details>

Sounds good

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1077#-:-Nu0is9HDeEW5bAY8Jxb:bnfp4nl)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

**Pull request merged**
