### PR TITLE
Import Audio Scripture Burrito

### PR DESCRIPTION
**Pull request by jsarabia**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156)

### CODE REVIEW

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/BurritoImporterFactory.kt` line 13 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-O0VXP0CDSQlL3KTK_cD:-O0VXP0CDSQlL3KTK_cE:bidria9) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b524c895c330b38365d8f5575551421432687184/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/BurritoImporterFactory.kt#L13)):*
> ```Kotlin
> 
>     private val importer: BurritoImporter by lazy {
>         // ts file is converted to RC and then passed to source importers
> ```

comments are easy to miss when copying
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt` line 40 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-O0VXqSYCOfJTh2ohmij:-O0VXqSYCOfJTh2ohmik:b4drtgo) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b524c895c330b38365d8f5575551421432687184/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt#L40)):*
> ```Kotlin
> )
> internal val ot = books.slice(0 until 41)
> internal val nt = books.slice(41 until 66)
> ```

should we use the existing`bookAnthology` in Anthology class?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt` line 397 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-O0VYVxh0blsqMZfjL03:-O0VYVxh0blsqMZfjL04:b-8ai99y) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b524c895c330b38365d8f5575551421432687184/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt#L397)):*
> ```Kotlin
>     }
> 
>     private fun getIngredientsByBook(burrito: MetadataSchema): Map<String, List<Pair<String, IngredientSchema>>> {
> ```

why is the return type like this? Also, the method name mentions `IngredientsByBook` but not returning that type

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/BurritoImporterFactory.kt` line 13 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-O0VXP0CDSQlL3KTK_cD:-O0iGjie32vBIrGisb1R:b-qsseby) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b524c895c330b38365d8f5575551421432687184/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/BurritoImporterFactory.kt#L13)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

comments are easy to miss when copying
</blockquote></details>

fixed!
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt` line 40 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-O0VXqSYCOfJTh2ohmij:-O0iGuMk59nCmDVRKnH5:bq8lsec) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b524c895c330b38365d8f5575551421432687184/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt#L40)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

should we use the existing`bookAnthology` in Anthology class?
</blockquote></details>

at the moment the index order matters as I use it to get the book number which would get erased by the map in Anthology =\
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt` line 397 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-O0VYVxh0blsqMZfjL03:-O0iGnj33kPHhTRCuNDB:b-xcl0rz) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b524c895c330b38365d8f5575551421432687184/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt#L397)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

why is the return type like this? Also, the method name mentions `IngredientsByBook` but not returning that type
</blockquote></details>

Thanks, I think I had this before I decided to make the type alias and missed it!
fixed

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt` line 299 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-O0iH6GvAJWI6hUp90Bq:-O0iH6GvAJWI6hUp90Br:b84w5rf) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/249276391b38c339da6cfff5785ff67f182f4028/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt#L299)):*
> ```Kotlin
>             if (inputAccessor.fileExists(usfmFile)) {
>                 val newPath = "$bookNumber-${book.uppercase(Locale.US)}.usfm"
>                 val ifs = inputAccessor.getInputStream(usfmFile)
> ```

stream not closed?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt` line 329 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-O0iGwqw4TJrLDdFGgdV:-O0iGwqx6vV-cSX2j5hc:b6xyjmo) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/249276391b38c339da6cfff5785ff67f182f4028/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt#L329)):*
> ```Kotlin
>                             .replace("{chapter}", chapter)
>                     }"
>                     val ifs = inputAccessor.getInputStream(audioFile)
> ```

do we need to close the stream eventually?

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt` line 388 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-O0iHN8G8I2kkGys_5J4:-O0iHN8G8I2kkGys_5J5:br16kgf) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/249276391b38c339da6cfff5785ff67f182f4028/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/burrito/BurritoToResourceContainerConverter.kt#L388)):*
> ```Kotlin
>     }
> 
>     private fun getFilename(languageCode: String, titleCode: String, bookSlug: String, extension: String): String {
> ```

let's add some line breaks

**Review by AnonymousWalker — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1156#-:-O0iLIUwERVVyynU3VCm:bnfp4nl)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @jsarabia)

**Pull request merged**
