### PR TITLE
Fix failed test on GH action

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt` line 660 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067#-Nt1AFt3EKHrdjmVGO42:-Nt1AFt3EKHrdjmVGO43:b-3c2b4m) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cd49b9704dad7165fe04f481d944947e6dee4add/common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt#L660)):*
> ```Kotlin
>         // Select a take to set up the test, and verify the preconditions
>         chunk.audio.selected.accept(TakeHolder(take))
>         verify(mockedDb, atLeast(1)).updateContent(any())
> ```

why would this be called more than once?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt` line 660 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067#-Nt1AFt3EKHrdjmVGO42:-Nt1ZTYE9OyoFxn6uhBP:bux7eel) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cd49b9704dad7165fe04f481d944947e6dee4add/common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt#L660)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why would this be called more than once?
</blockquote></details>

`subscribeToCheckingStatus()` calls it at some unspecified time after the execution

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt` line 660 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067#-Nt1AFt3EKHrdjmVGO42:-Nt1fFke23-R28hm8t1N:b-3kclrg) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cd49b9704dad7165fe04f481d944947e6dee4add/common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt#L660)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`subscribeToCheckingStatus()` calls it at some unspecified time after the execution
</blockquote></details>

sounds like that method should be changed to something like:
syncCheckingState
or
updateTakeOnCheckingChange

just saying "subscribeToCheckingStatus" doesn't imply side effects

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt` line 660 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067#-Nt1AFt3EKHrdjmVGO42:-Nt2ImBZ6j8a7ksq2HGl:bnlfe53) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cd49b9704dad7165fe04f481d944947e6dee4add/common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt#L660)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

sounds like that method should be changed to something like:
syncCheckingState
or
updateTakeOnCheckingChange

just saying "subscribeToCheckingStatus" doesn't imply side effects
</blockquote></details>

renamed to be consistent with `subscribePlaybackRateRelay`

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1067#-:-Nt2KhMp77w2RzhrhbmP:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
