### PR TITLE
Trim chapter representation files when leaving chapter

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 295 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl3dHj5Bua9sh4jaCg_:-Nl3dHj62Q8T5BXmM2ra:b-fm6kyb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6411479e0bb320270558f29f86370f63f4386ca9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L295)):*
> ```Kotlin
> 
>                 if (chapterRepresentation.totalFrames > 0) {
>                     fileWriter.outputStream(RcConstants.CHAPTER_REPRESENTATION_FILE.format(chapterDirName)).use { writer ->
> ```

line length

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 296 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl3dLRx5XQOZr3xELwF:-Nl3dLRx5XQOZr3xELwG:b-qv6don) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6411479e0bb320270558f29f86370f63f4386ca9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L296)):*
> ```Kotlin
>                 if (chapterRepresentation.totalFrames > 0) {
>                     fileWriter.outputStream(RcConstants.CHAPTER_REPRESENTATION_FILE.format(chapterDirName)).use { writer ->
>                         chapterRepresentation.getAudioFileReader().use { reader ->
> ```

should we call `chapterRepresentation.closeConnections()` after using its reader? I saw them get called from `Narration` class

**Comment by AnonymousWalker** [comment]
as suggested by @jsarabia, we need to export the chapter as .wav file with markers included.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 16 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/InProgressChapterFileFormat.kt` line 19 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl_CWB00qhlZfqq0wQ2:-Nl_CWB00qhlZfqq0wQ3:bs0lgof) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/03e5f2a3e13eba363b3faf93c25dbb42ba1dad37/common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/InProgressChapterFileFormat.kt#L19)):*
> ```Kotlin
>  * along with Orature.  If not, see <https://www.gnu.org/licenses/>.
>  */
> package org.wycliffeassociates.otter.common.audio
> ```

This file doesn't belong in the audio library (this is really an independent, general purpose audio library for java, it can be compiled to its own jar usable in other software, and specifically software that couldn't care less about Orature.) It just so happens to live in the Orature repo because it has made it easier for rapid development of both rather than making a change in one repo, compiling, uploading the jar to maven, rebuilding Orature...

This class is awkward overall... I might even propose just making it private inside the function you're using it in... but ultimately as it stands it probably belongs in the import export package, and renamed to something like InProgressNarrationFileFormats or something like that. It's very specific to Narration, whereas Chapters are a thing for Translation as well.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 162 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl_AxjH47Lhg1MSC_7F:-Nl_AxjH47Lhg1MSC_7G:b-ecobyh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/03e5f2a3e13eba363b3faf93c25dbb42ba1dad37/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L162)):*
> ```Kotlin
>         closeConnections()
>         trimScratchAudio()
>         trimActiveVerses()
> ```

you might wish to clear the history here as well just
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 494 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl_BLs24Ek3E5DG7IPy:-Nl_BLs24Ek3E5DG7IPz:b-jirh8a) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/03e5f2a3e13eba363b3faf93c25dbb42ba1dad37/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L494)):*
> ```Kotlin
> 
>     fun trimChapterRepresentation() {
>         chapterRepresentation.trim()
> ```

We shouldn't leak out through a public API the idea of "chapter representation"

This probably belongs in the close method instead
___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/ResourceContainerBuilder.kt` line 96 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl_Bz785R5WY-HZMYzy:-Nl_Bz785R5WY-HZMYzz:b9e9rme) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/03e5f2a3e13eba363b3faf93c25dbb42ba1dad37/common/src/test/kotlin/org/wycliffeassociates/otter/common/ResourceContainerBuilder.kt#L96)):*
> ```Kotlin
>     fun setOngoingProject(isOngoing: Boolean): ResourceContainerBuilder {
>         if (isOngoing) {
>             val tempFile = tempDir.resolve("selected.txt").apply {
> ```

selected.txt should be a const

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 162 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl_AxjH47Lhg1MSC_7F:-NliLFBeAesE2hf0O3lv:b-kzj6ov) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/03e5f2a3e13eba363b3faf93c25dbb42ba1dad37/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L162)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

you might wish to clear the history here as well just
</blockquote></details>

Done in `Narration.close()` after trimming the file
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 494 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl_BLs24Ek3E5DG7IPy:-NliLDPFBFohua_JKvuS:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/03e5f2a3e13eba363b3faf93c25dbb42ba1dad37/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L494)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

We shouldn't leak out through a public API the idea of "chapter representation"

This probably belongs in the close method instead
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 296 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl3dLRx5XQOZr3xELwF:-NliLQvJCs0R8rW_qc6z:b-dhoryd) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6411479e0bb320270558f29f86370f63f4386ca9/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L296)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

should we call `chapterRepresentation.closeConnections()` after using its reader? I saw them get called from `Narration` class
</blockquote></details>

Because we use `use`, it auto closes itself. As with Narration, we open it explicitly and not inside `use` construct. 
___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/ResourceContainerBuilder.kt` line 96 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl_Bz785R5WY-HZMYzy:-NliNO_JCAS3k8Wsx3XS:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/03e5f2a3e13eba363b3faf93c25dbb42ba1dad37/common/src/test/kotlin/org/wycliffeassociates/otter/common/ResourceContainerBuilder.kt#L96)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

selected.txt should be a const
</blockquote></details>

Done.
___
*[`common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/InProgressChapterFileFormat.kt` line 19 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nl_CWB00qhlZfqq0wQ2:-NliLNSzCrit4egYM8Ee:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/03e5f2a3e13eba363b3faf93c25dbb42ba1dad37/common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/InProgressChapterFileFormat.kt#L19)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This file doesn't belong in the audio library (this is really an independent, general purpose audio library for java, it can be compiled to its own jar usable in other software, and specifically software that couldn't care less about Orature.) It just so happens to live in the Orature repo because it has made it easier for rapid development of both rather than making a change in one repo, compiling, uploading the jar to maven, rebuilding Orature...

This class is awkward overall... I might even propose just making it private inside the function you're using it in... but ultimately as it stands it probably belongs in the import export package, and renamed to something like InProgressNarrationFileFormats or something like that. It's very specific to Narration, whereas Chapters are a thing for Translation as well.
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 202 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-NliqVMX9zexqPFXOvAt:-NliqVMX9zexqPFXOvAu:b-vb19rs) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0a70e8b80d76613ae3186ee165224856471b2880/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L202)):*
> ```Kotlin
>             val length = verse.length - 1
>             sectors.add(IntRange(start, length + start))
>             start += length + 1
> ```

I'd prefer:
sectors.add(IntRange(start, verse.length + start - 1))
start += verse.length

the -1 and +1 are a little more confusing 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/BackupProjectExporter.kt` line 136 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nlir7WC7oeuRR-xNy7X:-Nlir7WC7oeuRR-xNy7Y:b-vzz5y) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0a70e8b80d76613ae3186ee165224856471b2880/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/BackupProjectExporter.kt#L136)):*
> ```Kotlin
>     }
> 
>     private fun inProgressChapterFilter(path: String, exportOptions: ExportOptions?): Boolean {
> ```

These functions are the same, but use a different pattern. Could we combine them into one function and take the pattern as a parameter?
___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/TestUtils.kt` line 124 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-NlirYYA2EUSsQ70erlU:-NlirYYA2EUSsQ70erlV:bka88ub) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0a70e8b80d76613ae3186ee165224856471b2880/common/src/test/kotlin/org/wycliffeassociates/otter/common/TestUtils.kt#L124)):*
> ```Kotlin
>             "\"chapterNumber\":1,\"location\":0},\"sectors\":[{\"start\":3,\"end\":6}]},{\"placed\":true" +
>             ",\"marker\":{\"type\":\"VerseMarker\",\"start\":1,\"end\":1,\"location\":0}" +
>             ",\"sectors\":[{\"start\":7,\"end\":10}]}]"
> ```

multiline strings would be better here, it's """three quotes on either side"""
It eliminates the need to escape the " as well

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/FileNamer.kt` line 111 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-NlixAsfE25FHI0dsE9P:-NlixAsfE25FHI0dsE9Q:b-pasenn) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0a70e8b80d76613ae3186ee165224856471b2880/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/FileNamer.kt#L111)):*
> ```Kotlin
>             val chapter = """c(\d+)/"""
>             val chapterNarration = """(chapter_narration.pcm|"""
>             val activeVerses = """active_verses.json)"""
> ```

can we use just one line?
```
val fileName = """(chapter_narration.pcm|active_verses.json)"""  
Pattern.compile(chapter + fileName)
```

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/FileNamer.kt` line 111 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-NlixAsfE25FHI0dsE9P:-NlwHRs0CAWAXWUszv56:b-80tlqk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0a70e8b80d76613ae3186ee165224856471b2880/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/FileNamer.kt#L111)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

can we use just one line?
```
val fileName = """(chapter_narration.pcm|active_verses.json)"""  
Pattern.compile(chapter + fileName)
```
</blockquote></details>

Sure.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 202 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-NliqVMX9zexqPFXOvAt:-NlwHUWU32LHxFHY2JCd:b-eqb5l6) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0a70e8b80d76613ae3186ee165224856471b2880/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L202)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I'd prefer:
sectors.add(IntRange(start, verse.length + start - 1))
start += verse.length

the -1 and +1 are a little more confusing
</blockquote></details>

I've refactored this according to Tony's suggestion. Is it OK?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/BackupProjectExporter.kt` line 136 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-Nlir7WC7oeuRR-xNy7X:-NlwHd1KAiTMu8AqkWkP:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0a70e8b80d76613ae3186ee165224856471b2880/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/exporter/resourcecontainer/BackupProjectExporter.kt#L136)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

These functions are the same, but use a different pattern. Could we combine them into one function and take the pattern as a parameter?
</blockquote></details>

Done.
___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/TestUtils.kt` line 124 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-NlirYYA2EUSsQ70erlU:-NlwHeh26TTbs791D0Gw:bjzxctc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0a70e8b80d76613ae3186ee165224856471b2880/common/src/test/kotlin/org/wycliffeassociates/otter/common/TestUtils.kt#L124)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

multiline strings would be better here, it's """three quotes on either side"""
It eliminates the need to escape the " as well
</blockquote></details>

Oh, I forgot about three double quotes. That looks a lot better. Changed.

**Review by AnonymousWalker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 202 at r7](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-NliqVMX9zexqPFXOvAt:-Nlx1FWj9aPmYH63-AtX:bb7k0qh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0a70e8b80d76613ae3186ee165224856471b2880/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L202)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I've refactored this according to Tony's suggestion. Is it OK?
</blockquote></details>

lgtm

**Review by AnonymousWalker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

**Review by AnonymousWalker — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925#-:-Nlx1q_bCoiaFyZfZmFF:bnfp4nl)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

**Review by AnonymousWalker — COMMENTED** [review]
> Dismissed @jsarabia from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 24 files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by AnonymousWalker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/925)* status: 0 of 24 files reviewed, all discussions resolved (waiting on @jsarabia)

**Pull request merged**
