### PR TITLE
Implemented AudioFileReader in ChapterRepresentation

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 46 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Na6mqbKBP0aFh-lcAXA:-Na6mqbKBP0aFh-lcAXB:b-lmcaye) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9333d19a6869a1e163fcc1b169a6b3731ec23a78/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L46)):*
> ```Kotlin
> 
>     override val totalFrames: Int
>         get() = activeVerses.sumOf { it.start + it.end }
> ```

the length of each verse would be the end - start, not adding them
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 124 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Na6nISl5eXhp3mgMUkt:-Na6nISl5eXhp3mgMUku:baqu0xh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9333d19a6869a1e163fcc1b169a6b3731ec23a78/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L124)):*
> ```Kotlin
>         var bytesWritten = 0
> 
>         RandomAccessFile(workingAudio.file, "r").use { raf ->
> ```

What are the pros and cons of the RAF being declared in this method?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 128 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Na6nlXpBLF9dIjI3n2l:-Na6nlXpBLF9dIjI3n2m:b-ypml77) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9333d19a6869a1e163fcc1b169a6b3731ec23a78/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L128)):*
> ```Kotlin
>             val byteBuffer = ByteBuffer.wrap(bytes)
> 
>             for (verse in activeVerses) {
> ```

This allocates objects
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 143 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Na6niw1CX-lojyZnIOx:-Na6niw1CX-lojyZnIOy:b-m6p4ao) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9333d19a6869a1e163fcc1b169a6b3731ec23a78/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L143)):*
> ```Kotlin
>                     if (bytesWritten > bytes.size) {
>                         val diff = bytesWritten - bytes.size
>                         val smallerBuffer = buffer.copyOf(buffer.size - diff)
> ```

how do you know if you can use this or not?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 46 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Na6mqbKBP0aFh-lcAXA:-Na768u24g8Zbpph5F88:b9cql6i) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9333d19a6869a1e163fcc1b169a6b3731ec23a78/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L46)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

the length of each verse would be the end - start, not adding them
</blockquote></details>

Thanks. Fixed.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 124 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Na6nISl5eXhp3mgMUkt:-Na7PVcCAfnluohjBOw3:bsoghft) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9333d19a6869a1e163fcc1b169a6b3731ec23a78/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L124)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

What are the pros and cons of the RAF being declared in this method?
</blockquote></details>

moved to the "open" method
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 128 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Na6nlXpBLF9dIjI3n2l:-Na7PbR_-ksb1u-DVym-:b-cypxrc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9333d19a6869a1e163fcc1b169a6b3731ec23a78/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L128)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This allocates objects
</blockquote></details>

updated.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 143 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Na6niw1CX-lojyZnIOx:-Na7Pf4T5zRTTYJzb4i1:b-cypxrc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9333d19a6869a1e163fcc1b169a6b3731ec23a78/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L143)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

how do you know if you can use this or not?
</blockquote></details>

updated.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 130 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NaD-e0n6DvBTUlF9TIg:-NaD-e0oD7Yr1yiCGEIE:b-yv45ia) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0ff9b554f51ed3a7304e8a549f9562b276c71444/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L130)):*
> ```Kotlin
> 
>         val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
>         val byteBuffer = ByteBuffer.wrap(bytes)
> ```

Both of these lines allocate objects
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 135 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NaD-vcr7WfZq5YYEwEw:-NaD-vcr7WfZq5YYEwEx:bqsyndk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0ff9b554f51ed3a7304e8a549f9562b276c71444/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L135)):*
> ```Kotlin
>             for (i in 0 until activeVerses.size) {
>                 var verseRead = 0
>                 val verseStart = activeVerses[i].start * frameSizeInBytes
> ```

If the activeVerses start value is file positions, this would be incorrect.
Is start/end in file positions or in audio samples? Whichever unit it is should be then documented in the VerseNode class
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 144 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NaD0Gcy-bGL6qs2lCHd:-NaD0Gcy-bGL6qs2lCHe:bxdv44n) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0ff9b554f51ed3a7304e8a549f9562b276c71444/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L144)):*
> ```Kotlin
>                     // Make buffer smaller if default buffer size exceeds verse length
>                     // though, this should almost never happen
>                     val normalBuffer = if (buffer.size > verseLength) ByteArray(verseLength) else buffer
> ```

This also allocates memory
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 202 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NaD0MDp1ifbQWI7mitI:-NaD0MDp1ifbQWI7mitJ:bldl9s0) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0ff9b554f51ed3a7304e8a549f9562b276c71444/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L202)):*
> ```Kotlin
>             mappedFile?.close()
>             mappedFile = null
>             System.gc()
> ```

What does all of this code do and why are you using it?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 130 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NaD-e0n6DvBTUlF9TIg:-NaGLUFsADWcV1yreWxp:bss4a2b) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0ff9b554f51ed3a7304e8a549f9562b276c71444/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L130)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Both of these lines allocate objects
</blockquote></details>

Removed.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 135 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NaD-vcr7WfZq5YYEwEw:-NaGLVqj5hn61mf1OJD0:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0ff9b554f51ed3a7304e8a549f9562b276c71444/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L135)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

If the activeVerses start value is file positions, this would be incorrect.
Is start/end in file positions or in audio samples? Whichever unit it is should be then documented in the VerseNode class
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 144 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NaD0Gcy-bGL6qs2lCHd:-NaGLYqK2tF61drW8a42:bss4a2b) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0ff9b554f51ed3a7304e8a549f9562b276c71444/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L144)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This also allocates memory
</blockquote></details>

Removed.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 202 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NaD0MDp1ifbQWI7mitI:-NaGLaNT28Lpn55uYI9r:bss4a2b) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0ff9b554f51ed3a7304e8a549f9562b276c71444/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L202)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

What does all of this code do and why are you using it?
</blockquote></details>

Removed.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 58 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Nah8fGl2soV7eQUCM6h:-Nah8fGl2soV7eQUCM6i:b-hyj391) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6a7b586c3c3519b814858be3efbaa43f841dac49/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L58)):*
> ```Kotlin
>         private set
> 
>     private var mappedFile: RandomAccessFile? = null
> ```

I would rename this since it's not a mapped file, to avoid confusion
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 160 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NahBXeOCip6k00885Mo:-NahBXeOCip6k00885Mp:bgqaomz) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6a7b586c3c3519b814858be3efbaa43f841dac49/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L160)):*
> ```Kotlin
>     }
> 
>     override fun seek(sample: Int) {
> ```

This method is incorrect. This is the public method for seeking around the file. Which means that the sample position provided as input is the RELATIVE position, which means the actual position to move will require traversing through the verses list. 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/VerseNode.kt` line 11 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Nah9yH9D1BTfL4_OadQ:-Nah9yH9D1BTfL4_OadR:b-ngfokl) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6a7b586c3c3519b814858be3efbaa43f841dac49/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/VerseNode.kt#L11)):*
> ```Kotlin
>      * End location in frames
>      */
>     var end: Int
> ```

Given that these are to store the audio segments in the file, it makes more sense for these to be the actual file index, not an audio frame (the history is a private implementation detail of our Chapter Representation, so, our domain internally is with respect to the file and segments which may be invalid- it's only the public API things which are in the audio domain.)

By switching these units to being file indexes, this also eliminates the need for multiplication in the getPCMBuffer method, which, given the frequency in which it is called, is a nice optimization

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 58 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Nah8fGl2soV7eQUCM6h:-Naq2Cop8YrfIllrgbnI:b-9otakr) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6a7b586c3c3519b814858be3efbaa43f841dac49/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L58)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I would rename this since it's not a mapped file, to avoid confusion
</blockquote></details>

Renamed to what?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 160 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-NahBXeOCip6k00885Mo:-Naq2rqj7iN2C7Y3jCiQ:bqr40ir) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6a7b586c3c3519b814858be3efbaa43f841dac49/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L160)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This method is incorrect. This is the public method for seeking around the file. Which means that the sample position provided as input is the RELATIVE position, which means the actual position to move will require traversing through the verses list. 
</blockquote></details>

Actually I wanted to leave it "Not implemented" cause I don't know how to properly make it to seek to correct position.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/VerseNode.kt` line 11 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/778#-Nah9yH9D1BTfL4_OadQ:-Naq2_hP4-d4PYxHTrxt:b-sr1iwu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6a7b586c3c3519b814858be3efbaa43f841dac49/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/VerseNode.kt#L11)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Given that these are to store the audio segments in the file, it makes more sense for these to be the actual file index, not an audio frame (the history is a private implementation detail of our Chapter Representation, so, our domain internally is with respect to the file and segments which may be invalid- it's only the public API things which are in the audio domain.)

By switching these units to being file indexes, this also eliminates the need for multiplication in the getPCMBuffer method, which, given the frequency in which it is called, is a nice optimization
</blockquote></details>

It means that for the sake of one place where it converts to file index, I need to convert it in other 100 places. That's why for simplicity I provide frame positions and no file indexes.

**Pull request merged**
