### PR TITLE
Refactored chapter card list to have a cell factory

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/256)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/256)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt, line 7 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MVpskYgDQ3e0VWRw5mG:-MVpskYgDQ3e0VWRw5mH:b-z8vnbk) ([raw file](https://github.com/bible-translation-tools/otter/blob/237e1e0b05b6f70b0fca35383ef4039847261673/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt#L7)):*
> ```Kotlin
> import org.wycliffeassociates.otter.jvm.workbookapp.ui.model.CardData
> 
> class ChapterCell(metadata: ResourceMetadata, onDelete: () -> Unit): ListCell<CardData?>() {
> ```

I don't really like the generic name of "card data" when we use cards in so many places for so many things. And this list is being used for more than just Chapters.

So how about WorkbookItem? WorkbookItemCell, WorkbookItemData
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 151 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MVpvFGl3IgQrbtUHz03:-MVpvFGl3IgQrbtUHz04:b-d5lewy) ([raw file](https://github.com/bible-translation-tools/otter/blob/237e1e0b05b6f70b0fca35383ef4039847261673/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L151)):*
> ```Kotlin
>     private inner class WorkbookResourceTab(val resourceMetadata: ResourceMetadata) : Tab() {
> 
>         lateinit var listView: ListView<CardData?>
> ```

Let's talk about refactoring the CardData and see if we can solve the need for distinguishing between the chapter and banner without needing a nullable type here

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/256)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt, line 7 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MVpskYgDQ3e0VWRw5mG:-MW9JTdA5wBW62sO-Olo:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/237e1e0b05b6f70b0fca35383ef4039847261673/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt#L7)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I don't really like the generic name of "card data" when we use cards in so many places for so many things. And this list is being used for more than just Chapters.

So how about WorkbookItem? WorkbookItemCell, WorkbookItemData
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 151 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MVpvFGl3IgQrbtUHz03:-MW9JUef0DSQJ3x5of9O:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/237e1e0b05b6f70b0fca35383ef4039847261673/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L151)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Let's talk about refactoring the CardData and see if we can solve the need for distinguishing between the chapter and banner without needing a nullable type here
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 5 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/256)* status: 5 of 15 files reviewed, 4 unresolved discussions (waiting on @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt, line 7 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MVpskYgDQ3e0VWRw5mG:-MW9W8HlDKC8-llTRJvf:bxm2ufi) ([raw file](https://github.com/bible-translation-tools/otter/blob/237e1e0b05b6f70b0fca35383ef4039847261673/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt#L7)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

does this need to be nullable?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt, line 32 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MW9WI7I5HG_5KlpjKhi:-MW9WI7I5HG_5KlpjKhj:b-6jpb9y) ([raw file](https://github.com/bible-translation-tools/otter/blob/689fca4a4b831a47f5d6946fceffb5b496357781/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt#L32)):*
> ```Kotlin
>     }
> 
>     private fun prepareChapterCard(item: ChapterCardModel?): ChapterCard {
> ```

why is item nullable?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt, line 45 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MW9WK2-CwDa61PTgPMv:-MW9WK2-CwDa61PTgPMw:b-6jpb9y) ([raw file](https://github.com/bible-translation-tools/otter/blob/689fca4a4b831a47f5d6946fceffb5b496357781/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt#L45)):*
> ```Kotlin
>     }
> 
>     private fun prepareWorkbookBanner(item: WorkbookBannerModel?): WorkbookBanner {
> ```

why is item nullable?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 89 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MW9W_Fx6MP-phwWev9K:-MW9W_Fx6MP-phwWev9L:bons6is) ([raw file](https://github.com/bible-translation-tools/otter/blob/689fca4a4b831a47f5d6946fceffb5b496357781/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L89)):*
> ```Kotlin
>         confirmdialog {
>             this.root.prefWidthProperty().bind(
>                 primaryStage.widthProperty().divide(2)
> ```

is there not a set dimension we would want? this seems like it would be massive on a large screen?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/256)* status: 5 of 17 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt, line 7 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MVpskYgDQ3e0VWRw5mG:-MW9cs4L-tNRACY_ek5a:b7o913g) ([raw file](https://github.com/bible-translation-tools/otter/blob/237e1e0b05b6f70b0fca35383ef4039847261673/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt#L7)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

does this need to be nullable?
</blockquote></details>

Thanks for finding this. Left from the old code. Removed
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt, line 32 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MW9WI7I5HG_5KlpjKhi:-MW9d-kl2WW3t_wHgn09:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/689fca4a4b831a47f5d6946fceffb5b496357781/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt#L32)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why is item nullable?
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt, line 45 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MW9WK2-CwDa61PTgPMv:-MW9d0iM2uMkbLRerqCi:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/689fca4a4b831a47f5d6946fceffb5b496357781/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/ChapterCell.kt#L45)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why is item nullable?
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 89 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MW9W_Fx6MP-phwWev9K:-MW9uFRACV7GoBDBZ-JD:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/689fca4a4b831a47f5d6946fceffb5b496357781/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L89)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

is there not a set dimension we would want? this seems like it would be massive on a large screen?
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r2, 1 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/256)* status: 8 of 18 files reviewed, 1 unresolved discussion (waiting on @mXaln)

___
*[jvm/controls/src/main/resources/css/confirm-dialog.css, line 4 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MWADaEQ1_YHQU4y5H_u:-MWADaEQ1_YHQU4y5H_v:bl5nhux) ([raw file](https://github.com/bible-translation-tools/otter/blob/94180122053a649887455397162b18afb4273d5e/jvm/controls/src/main/resources/css/confirm-dialog.css#L4)):*
> ```CSS
> 
> .confirm-dialog {
>     -fx-pref-width: 792px;
> ```

from the chat, Thomas said this should be 480px

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/256)* status: 8 of 18 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[jvm/controls/src/main/resources/css/confirm-dialog.css, line 4 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/256#-MWADaEQ1_YHQU4y5H_u:-MWOseIP3lHCc4Sgfpmj:bh2p7xc) ([raw file](https://github.com/bible-translation-tools/otter/blob/94180122053a649887455397162b18afb4273d5e/jvm/controls/src/main/resources/css/confirm-dialog.css#L4)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

from the chat, Thomas said this should be 480px
</blockquote></details>

done. Changed to 800px

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/256#-:-MWP3EmjC01Cogy3uffA:bnfp4nl)* status: 8 of 18 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

**Pull request merged**
