### PR TITLE
Optimize workbook page

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/458)

### CODE REVIEW

**Comment by jsarabia** [comment]
This is really buggy if you flip back and forth between two different books. I made a psalms and james project, and flipping between them results in extra verses showing up in psalms chapter 1

**Comment by jsarabia** [comment]
takes are merging between them too

**Review by mXaln — COMMENTED** [review]
I couldn't reproduce either of these bugs. Could you show me?

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/458#-:-MrMIEAL8v598hmplAB2:bqaz42l)* status: 0 of 7 files reviewed, all discussions resolved

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/458#-:-MsWdg1I6ZeFXgAqfbed:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved

**Pull request merged**
