### PR TITLE
Waveform theme color binding

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/628)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
image

**Review by mXaln — APPROVED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/628)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/628)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/Utils.kt` line 24 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/628#-N6sc6EU6kXBWIVRPsLv:-N6sc6EU6kXBWIVRPsLw:bl50apd) ([raw file](https://github.com/bible-translation-tools/orature/blob/4f8f1d563170f593007de5ae3bbce8c025689a78/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/Utils.kt#L24)):*
> ```Kotlin
> import org.wycliffeassociates.otter.common.data.ColorTheme
> 
> fun adjustWaveformImageByTheme(theme: ColorTheme, adjust: ColorAdjust) {
> ```

This function makes it sound like it does the adjusting of the waveform image, but instead it creates the appropriate ColorAdjust object.

Why not something like:
getColorAdjustFromTheme or getWaveformColorTransformation

I'd also probably make it internal since it should just be used internally by the waveform controls.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt` line 96 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/628#-N6sbYVNBlSp5imd_oqS:-N6sbYVOBtY2p3DEKGeL:b-gibkq6) ([raw file](https://github.com/bible-translation-tools/orature/blob/4f8f1d563170f593007de5ae3bbce8c025689a78/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt#L96)):*
> ```Kotlin
>     private val waveformColorEffect = ColorAdjust()
>     var imageHolder: HBox? = null
>     var dragStart: Point2D? = null
> ```

previously the dragStart and dragContext were adjacent to each other (variables loosely related and should be kept together)

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/628)* status: 16 of 20 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/Utils.kt` line 24 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/628#-N6sc6EU6kXBWIVRPsLv:-N6suiguBvK9HDm5t8d6:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4f8f1d563170f593007de5ae3bbce8c025689a78/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/Utils.kt#L24)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This function makes it sound like it does the adjusting of the waveform image, but instead it creates the appropriate ColorAdjust object.

Why not something like:
getColorAdjustFromTheme or getWaveformColorTransformation

I'd also probably make it internal since it should just be used internally by the waveform controls.
</blockquote></details>

Done.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt` line 96 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/628#-N6sbYVNBlSp5imd_oqS:-N6suj6iCT5erWiQDDmH:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4f8f1d563170f593007de5ae3bbce8c025689a78/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt#L96)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

previously the dragStart and dragContext were adjacent to each other (variables loosely related and should be kept together)
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/628#-:-N6swYsn7SXPgcfN7xni:bnfp4nl)* status: 16 of 20 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

**Pull request merged**
