### PR TITLE
Chunking background restyle

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt` line 48 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857#-NhTEr9W7PAMmhaf_LUc:-NhTEr9W7PAMmhaf_LUd:b-iw0jz2) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/314e96c9a938d6a20889d2a0586817d04846827c/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt#L48)):*
> ```Kotlin
>      * Flag to determine if this reusable component follows the old or new design.
>      */
>     val isNewDesignProperty = SimpleBooleanProperty(false)
> ```

Should this be a TODO or FIXME or should something be marked Deprecated?

isNewDesign is only new until something newer is designed, in which, is this increasingly confusing or will it have been removed by then?

**Comment by AnonymousWalker** [comment]
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt` line 48 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857#-NhTEr9W7PAMmhaf_LUc:-NhTG1KrC7UeihEcM9DG:bf0ezxy) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/314e96c9a938d6a20889d2a0586817d04846827c/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt#L48)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Should this be a TODO or FIXME or should something be marked Deprecated?

isNewDesign is only new until something newer is designed, in which, is this increasingly confusing or will it have been removed by then?
</blockquote></details>

it's quite messy to keep the old verse marker UI untouched while working on a new design and avoiding duplicated code. I need something to distinguish them

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt` line 48 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857#-NhTEr9W7PAMmhaf_LUc:-NhXGRzBCeWTnSz690nz:bt1ezgr) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/314e96c9a938d6a20889d2a0586817d04846827c/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt#L48)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

it's quite messy to keep the old verse marker UI untouched while working on a new design and avoiding duplicated code. I need something to distinguish them
</blockquote></details>

essentially, this class is shared between the new and old waveform

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt` line 48 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857#-NhTEr9W7PAMmhaf_LUc:-NhlawpH4kMn7-1MLZpk:bm6fynx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/314e96c9a938d6a20889d2a0586817d04846827c/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt#L48)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

essentially, this class is shared between the new and old waveform
</blockquote></details>

Make this an enum and the enums are the versions

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt` line 48 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857#-NhTEr9W7PAMmhaf_LUc:-NiexhxX09CPmkNTVhIf:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/314e96c9a938d6a20889d2a0586817d04846827c/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformFrame.kt#L48)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Make this an enum and the enums are the versions
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/857#-:-Nij22TEC8mB_MnFuM-t:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved

**Pull request merged**
