### PR TITLE
Refactored horizontal navbar (Second Edition)

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/101)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/101)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 32 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6MpNs1rOwDGl-XMkA:-MA6MpNs1rOwDGl-XMkB:bde9uc8) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L32)):*
> ```Kotlin
>     override var currentGroup: ITabGroup? = null
> 
>     enum class Direction {
> ```

Direction of what?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 45 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6N0u51vsCREgaATME:-MA6N0u51vsCREgaATMF:b7nzj0p) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L45)):*
> ```Kotlin
>             disableAnimationProperty().set(true)
> 
>             selectionModel.selectedIndexProperty().addListener { _, old, new ->
> ```

This is really complex and I can't glance and discern what it's doing. Should at the very least be in a function.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 46 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6NGQOBSF0siCdU7tw:-MA6NGQOBSF0siCdU7tx:b-j0h58t) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L46)):*
> ```Kotlin
> 
>             selectionModel.selectedIndexProperty().addListener { _, old, new ->
>                 if (old.toInt() >= 0 && new.toInt() >= 0) {
> ```

cast the ints and save them to a variable if that's what you need; everywhere you use them you cast them
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 100 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6Md1l2ftmNG9JEQbU:-MA6Md1l2ftmNG9JEQbV:b-vo4mno) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L100)):*
> ```Kotlin
>     }
> 
>     fun animateTabContent(content: Node, direction: Direction) {
> ```

is this a public api?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableTab.kt, line 8 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6MCI24FUij6SFBmXr:-MA6MCID7nRYhNV8fhvg:b-exnbcx) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableTab.kt#L8)):*
> ```Kotlin
> import tornadofx.*
> 
> abstract class ChromeableTab : Tab() {
> ```

What does Chromeable mean?
What are things I should expect when it comes to naming things when using inheritance?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt, line 17 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6PPw01w0UqbwT-ty0:-MA6PPw01w0UqbwT-ty1:bnzoieu) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt#L17)):*
> ```Kotlin
>         val contentScrollPane by cssclass()
>         val takesList by cssclass()
>         val navbar by cssclass()
> ```

I'd prefer a better name here; it's kinda confused me especially to realize it's the page toggle.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/viewmodel/RecordResourceViewModel.kt, line 36 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6ONCE0xZ-O90HwGv2:-MA6ONCF5YCPyJZAGGbi:b-lcyfk6) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/viewmodel/RecordResourceViewModel.kt#L36)):*
> ```Kotlin
>     private val resourceListViewModel: ResourceListViewModel by inject()
>     private val audioPluginViewModel: AudioPluginViewModel by inject()
>     private val navigator: ChromeableStage by inject()
> ```

is this a navigator or is this a stage?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/101)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 32 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6MpNs1rOwDGl-XMkA:-MA6c4Uz6KvC9UBMWo4y:b-vmm1rd) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L32)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Direction of what?
</blockquote></details>

Changed to TranstionDirection
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 45 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6N0u51vsCREgaATME:-MA6c1A66e_cLlR2IaQj:b-vwtdty) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L45)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This is really complex and I can't glance and discern what it's doing. Should at the very least be in a function.
</blockquote></details>

Moved to the function
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 46 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6NGQOBSF0siCdU7tw:-MA6c0-o05YwP-2LtjaC:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L46)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

cast the ints and save them to a variable if that's what you need; everywhere you use them you cast them
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 100 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6Md1l2ftmNG9JEQbU:-MA6bsnB2UHRUbxCHmNN:b-59a1ai) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L100)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

is this a public api?
</blockquote></details>

It could be at some point. But now it's not. Ok I made it private.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableTab.kt, line 8 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6MCI24FUij6SFBmXr:-MA6bOuC7k3Q24nYdyw1:bfklei6) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableTab.kt#L8)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

What does Chromeable mean?
What are things I should expect when it comes to naming things when using inheritance?
</blockquote></details>

It means the tab of the Chromeable stage
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt, line 17 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6PPw01w0UqbwT-ty0:-MA6bLES89ZDQ1ffpcW-:b1jeyey) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt#L17)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I'd prefer a better name here; it's kinda confused me especially to realize it's the page toggle.
</blockquote></details>

what do you suggest?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/viewmodel/RecordResourceViewModel.kt, line 36 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6ONCE0xZ-O90HwGv2:-MA6baTk18XmIaxLJwbx:b9475lj) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/viewmodel/RecordResourceViewModel.kt#L36)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

is this a navigator or is this a stage?
</blockquote></details>

I named it like it was named in other classes.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/101)* status: 0 of 11 files reviewed, 7 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt, line 17 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6PPw01w0UqbwT-ty0:-MAaJB5S2TKa7aXDJsv1:bvmua4g) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt#L17)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

what do you suggest?
</blockquote></details>

renamed to pagination
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableTab.kt, line 8 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6MCI24FUij6SFBmXr:-MAaIwBA6Fscdj2LkUqg:butap5q) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableTab.kt#L8)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

It means the tab of the Chromeable stage
</blockquote></details>

changed to AnimatedTab

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/101)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 32 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MB0SwZwBn9Hv_gWYtwp:-MB0SwZwBn9Hv_gWYtwq:b-kthrvx) ([raw file](https://github.com/bible-translation-tools/otter/blob/24f54f5f0e804fd63a6d0994e6ceec717d44471c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L32)):*
> ```Kotlin
> 
>             // Disable builtin tab transition animation
>             disableAnimationProperty().set(true)
> ```

The act of disabling this should now be moved; the tab groups when docked should disable the animation, and when undocked should restore what it was set to before.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/AnimatedTabGroup.kt, line 22 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MB0Smh19ygZ4t2cqioB:-MB0Smh19ygZ4t2cqioC:b-fm6kyb) ([raw file](https://github.com/bible-translation-tools/otter/blob/24f54f5f0e804fd63a6d0994e6ceec717d44471c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/AnimatedTabGroup.kt#L22)):*
> ```Kotlin
>             val newIndex = new.toInt()
>             if (oldIndex >= 0 && newIndex >= 0) {
>                 val direction = if (oldIndex > newIndex) TransitionDirection.RIGHT else TransitionDirection.LEFT
> ```

line length
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt, line 13 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MB9sQT26O0xUjZCyBHH:-MB9sQT26O0xUjZCyBHI:baq117p) ([raw file](https://github.com/bible-translation-tools/otter/blob/24f54f5f0e804fd63a6d0994e6ceec717d44471c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt#L13)):*
> ```Kotlin
> 
>     init {
>         viewModel.transitionDirectionProperty.onChange {
> ```

Why do we need this in a viewmodel? shouldn't we know which tab is currently selected, and the tab we're switching to based on their index in the list? left is going from a high number to low number, right is going from low to high?

Either way, this detail really feels like an implementation detail with the view layer itself (tabs, tab pane, tab group), and really doesn't belong in the RecordResourceViewModel.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt, line 17 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6PPw01w0UqbwT-ty0:-MB9t39p5962LvvYGt6k:b92qv7l) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt#L17)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

renamed to pagination
</blockquote></details>

I prefer page toggle, because this isn't pagination. Pagination would be where you have like:
[1] [2] [3] [...]
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/viewmodel/RecordResourceViewModel.kt, line 158 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MB9tUw_3bJyE26ndlsR:-MB9tUwaEg1P7VUwEXm2:b-dm3l9) ([raw file](https://github.com/bible-translation-tools/otter/blob/24f54f5f0e804fd63a6d0994e6ceec717d44471c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/viewmodel/RecordResourceViewModel.kt#L158)):*
> ```Kotlin
>     fun nextChunk() {
>         stepToChunk(StepDirection.FORWARD)
>         transitionDirectionProperty.set(TransitionDirection.LEFT)
> ```

this really feels redundant, even the enums

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/101)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt, line 32 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MB0SwZwBn9Hv_gWYtwp:-MBA1UkFBuCUHV88sVKN:b69314k) ([raw file](https://github.com/bible-translation-tools/otter/blob/24f54f5f0e804fd63a6d0994e6ceec717d44471c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/ChromeableStage.kt#L32)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

The act of disabling this should now be moved; the tab groups when docked should disable the animation, and when undocked should restore what it was set to before.
</blockquote></details>

Moved to AnimatedTabGroup (activate, deactivate methods)
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/AnimatedTabGroup.kt, line 22 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MB0Smh19ygZ4t2cqioB:-MBA2KE7CbNbAAuWdRn6:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/24f54f5f0e804fd63a6d0994e6ceec717d44471c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/AnimatedTabGroup.kt#L22)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt, line 13 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MB9sQT26O0xUjZCyBHH:-MBA8SKv3PY5NZbnnXEP:bcyvtmw) ([raw file](https://github.com/bible-translation-tools/otter/blob/24f54f5f0e804fd63a6d0994e6ceec717d44471c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt#L13)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why do we need this in a viewmodel? shouldn't we know which tab is currently selected, and the tab we're switching to based on their index in the list? left is going from a high number to low number, right is going from low to high?

Either way, this detail really feels like an implementation detail with the view layer itself (tabs, tab pane, tab group), and really doesn't belong in the RecordResourceViewModel.
</blockquote></details>

How the tab, tabGroup or tabPane will know that next and previous buttons were clicked. Because in this case the real tab selection does not happen. Only viewModel knows about that event.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt, line 17 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6PPw01w0UqbwT-ty0:-MBA6fA7DFyjf_NB56Qn:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt#L17)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I prefer page toggle, because this isn't pagination. Pagination would be where you have like:
[1] [2] [3] [...]
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/viewmodel/RecordResourceViewModel.kt, line 158 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MB9tUw_3bJyE26ndlsR:-MBA6RsP-SvzzUH-8SFY:b-49likh) ([raw file](https://github.com/bible-translation-tools/otter/blob/24f54f5f0e804fd63a6d0994e6ceec717d44471c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/viewmodel/RecordResourceViewModel.kt#L158)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this really feels redundant, even the enums
</blockquote></details>

how the tabGroup will know that the "Next" or "Previous" button was clicked?

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/101)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt, line 13 at r4](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MB9sQT26O0xUjZCyBHH:-MBio0VT67VOK_-9u3E3:bkhry9u) ([raw file](https://github.com/bible-translation-tools/otter/blob/24f54f5f0e804fd63a6d0994e6ceec717d44471c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt#L13)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

How the tab, tabGroup or tabPane will know that next and previous buttons were clicked. Because in this case the real tab selection does not happen. Only viewModel knows about that event.
</blockquote></details>

I did a little digging into the tabpane and tab classes (not the jfoenix ones yet, they may add additional functionality, so it may be worth looking through the source). 

The way I see it there are two problems you're trying to tackle:
1. The part of the screen you want to move is not the full tab- only part of it.
2. You want to be able to move to the next or previous tab within the tab, not clicking on the tab

The first goal you've accomplished, and you accomplished it this way:
1. extend the tab group to be able to disable the default tabpane animation
2. define an API to let content within the tab designate what node should be "animated" on tab transition
3. execute animation when the tab changes

To accomplish the second need, it sounds like you need a way to navigate to the next or previous tab in the tab pane from within a tab. 

Tabs have references to the tab pane they are in.
There is an event system for tab selection changing, closing
It is reasonable that the tab group could likewise contain a property to hold a reference to the tab pane, set when docked and removed when undocked.
Likewise, the animated tab could hold a reference to the animated tab group, and the tab group could set that value when tabs are added to the tab group.

Through investigating the features and ideas above, it seems reasonable that what you want is to implement a "next,previous" tab kind of functionality. This seems valuable and necessary generically (and may exist in jfoenix's rendition of the tab pane, so check there for sure), as one example I can think of for this functionality to be necessary in a tab/tab pane in general (not speaking specifically regarding the animated variant you've built) would be to configure keyboard shortcuts to move between tabs in the tab pane.

Without further investigation into how the resources are swapping, this approach seems to be the best; focusing on the actual structure (tab pane, tabs, etc) and not trying to merge knowledge of your use case and the application domain into the structure. After all, the tab pane isn't really a "layout" even; it's an api to put content into a tab pane structure, giving the ability to flip back and forth between content. You typically have an actual layout inside the tab pane that is specific to what your application is about.  

If tabs are in fact selected (activated) by firing an event, then your implementation of the tab requesting to switch should probably be done in a similar fashion. If that's the case the tab group could listen for the event request, and trigger the animation. Otherwise it's possible that it's a method on the tab group, and the tab would have a reference to the tab pane in order to call that method?

Basically, these are some of the leads that I have, but I haven't looked into it enough to tell you exactly with 100% certainty how it should be done, but hopefully this gets you unblocked with some direction to go in. Again, my preference would just be to follow the patterns for how the existing tab system is working if you're adding functionality that's somewhat similar in nature.

And of course, jfoenix's version may already do this anyway
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt, line 17 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/101#-MA6PPw01w0UqbwT-ty0:-MBEgz-D2ZNOh5vQpYty:b-463ohx) ([raw file](https://github.com/bible-translation-tools/otter/blob/26c18459b0dde219845d39ec5359c3a12816809e/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/resourcetakes/view/RecordResourceStyles.kt#L17)):*
<details><summary><i>Previously, mXaln (Maxim Murzamuratov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

pagination still exists here

**Pull request closed without merging**
