### PR TITLE
Verse Bridge Support

### PR DESCRIPTION
**Pull request by jsarabia**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767)

### CODE REVIEW

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767)* status: 0 of 40 files reviewed, 4 unresolved discussions

___
*[`common/audio/src/test/kotlin/org/wycliffeassociates/otter/common/audio/wav/VerseMarkerChunkTest.kt` line 207 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_eBa6NDmOoLDU5XcXL:-N_eBa6NDmOoLDU5XcXM:b-317bp4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/audio/src/test/kotlin/org/wycliffeassociates/otter/common/audio/wav/VerseMarkerChunkTest.kt#L207)):*
> ```Kotlin
> //                    assertTrue(resultMetadata.getCues().contains(cue))
> //                }
>             }
> ```

Need to fix or remove this
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/SourceAudioFile.kt` line 36 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_eC4c70Gg0q8SoDOyZ:-N_eC4c70Gg0q8SoDOy_:b4j7ghd) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/SourceAudioFile.kt#L36)):*
> ```Kotlin
> //        chunks.forEach { addCue(it.location, "orature-chunk-${it.label}") }
> //        extraCues.forEach { addCue(it.location, it.label) }
> //        super.update()
> ```

fix or remove
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt` line 189 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_eCEeQ3LQRM4DncAYK:-N_eCEeQ3LQRM4DncAYL:bjyz9g8) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt#L189)):*
> ```Kotlin
> 
> 
>     private fun handleUnmatched(labelsToMarkers: MutableMap<String, AudioMarker?>, unmatchedMarkers: List<AudioMarker>) {
> ```

line break
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt` line 261 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_eCGjS1jlBTSLsTX_d:-N_eCGjS1jlBTSLsTX_e:bjyz9g8) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt#L261)):*
> ```Kotlin
>     }
> 
>     fun bridgeCue(cue: AudioCue, labels: MutableList<String>, mappedCues: MutableMap<String, AudioCue>) {
> ```

line break

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767)* status: 0 of 40 files reviewed, 13 unresolved discussions (waiting on @jsarabia)

___
*[`common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/wav/WavMetadata.kt` line 42 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jGkqoCdEajPNYLLcR:-N_jGkqoCdEajPNYLLcS:b-sc3y3p) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/wav/WavMetadata.kt#L42)):*
> ```Kotlin
> 
>     companion object {
>         var parsers: List<Class<out RiffChunk?>> = arrayListOf<Class<out RiffChunk?>>(CueChunk::class.java)
> ```

could this be private?
___
*[`common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/wav/WavMetadata.kt` line 73 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jHAiB52aU682f3rmF:-N_jHAiB52aU682f3rmG:b-6rpjjq) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/audio/src/main/kotlin/org/wycliffeassociates/otter/common/audio/wav/WavMetadata.kt#L73)):*
> ```Kotlin
>             chunks.add(cueChunk)
>         }
>     }
> ```

looks like we can refactor some of this `init` block to a function
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/audio/Markers.kt` line 9 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jMxa4-ff-VlHJdKEi:-N_jMxa4-ff-VlHJdKEj:b-ylfurr) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/audio/Markers.kt#L9)):*
> ```Kotlin
>     val location: Int
> 
>     fun formatMarkerText(): String
> ```

could we simplify this method with `val formattedLabel: String` and let the classes implement it
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/MarkerParsers.kt` line 9 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jNcNS8BM8zezuZ4Ey:-N_jNcNTD35vPubegLyO:btlguyd) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/MarkerParsers.kt#L9)):*
> ```Kotlin
> import java.util.regex.Pattern
> 
> object OratureCueParser {
> ```

this looks like a use case of the MarkerParser and could be in its own class.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/MarkerParsers.kt` line 39 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jNmfW6ZCYTOoHDRsg:-N_jNmfW6ZCYTOoHDRsh:b-cwliqb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/MarkerParsers.kt#L39)):*
> ```Kotlin
> }
> 
> class MarkerParseResult(val accepted: List<AudioMarker>, val rejected: List<AudioCue>)
> ```

How about `acceptedList` and `rejectedList`. Also, there is a difference in the type of elements, you could consider having a comment to avoid confusion.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt` line 4 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jOIfKDU4nOqJi3VGH:-N_jOIfKDU4nOqJi3VGI:b-2g3vo7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt#L4)):*
> ```Kotlin
> 
> import org.slf4j.LoggerFactory
> import org.wycliffeassociates.otter.common.audio.*
> ```

_*_ import should be avoided, in case you missed
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt` line 177 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jPfjKD7nornq2QpSm:-N_jPfjKD7nornq2QpSn:bf8t0v1) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt#L177)):*
> ```Kotlin
>      * @param markers the markers to copy from
>      */
>     fun import(markers: OratureMarkers) {
> ```

"importMarkers" is more consistent with other methods in this class
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt` line 205 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jRK2w8Ct0iXS5zFtC:-N_jRK2w8Ct0iXS5zFtD:bnafm0t) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt#L205)):*
> ```Kotlin
>         }
> 
>         for (verse in unmatchedMarkers) {
> ```

this is a great place to add a comment, before the loop, same on the forEach above
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt` line 452 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jS-Bu10N3ylRQjPnN:-N_jS-Bu10N3ylRQjPnO:bm4n3en) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L452)):*
> ```Kotlin
>                 recordable?.audio?.selectTake(take) ?: throw IllegalStateException("Recordable is null")
>                 val workbook = workbookDataStore.workbook
>                 workbook.projectFilesAccessor.updateSelectedTakesFile(workbook).blockingGet()
> ```

maybe chaining would be better?

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767)* status: 0 of 40 files reviewed, 10 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/MarkerParsers.kt` line 9 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jNcNS8BM8zezuZ4Ey:-N_obAO54ClKw7TkyL9Q:b84apan) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/MarkerParsers.kt#L9)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this looks like a use case of the MarkerParser and could be in its own class.
</blockquote></details>

This is kind of the public API for parsing markers, specifically concerned with Orature (hence it being in the domain package and not the audio library.)

It's an object because it's stateless and there's no reason to have more than one, so why not just make it a singleton.

I made everything else here internal (not intended to be used outside this). Does this help?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/MarkerParsers.kt` line 39 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jNmfW6ZCYTOoHDRsg:-N_oY9_W41xcU_U2MBQv:b4147y1) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/MarkerParsers.kt#L39)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

How about `acceptedList` and `rejectedList`. Also, there is a difference in the type of elements, you could consider having a comment to avoid confusion.
</blockquote></details>

The idea here is accepted are valid audio markers. They mean something in the domain context more than just a marker label and position.

Cues didn't match anything we can identify for the purpose of domain use, so they never got cast to any such domain class.

I also don't intend for this to leak out of this file, so I marked this and the individual parsers as internal. The purpose of this class is really to be able to return a tuple/pair, and doing it this way just makes the access of both better than .first and .second.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt` line 4 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jOIfKDU4nOqJi3VGH:-N_obyNm229XVQw8XMaT:b-tzermb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt#L4)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

* import should be avoided, in case you missed
</blockquote></details>

Thanks, forgot to update the ide on the new PC to not use * after 5 imports
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt` line 177 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jPfjKD7nornq2QpSm:-N_oWnLP8mGtP_Vp9MLA:b-iyyi7e) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt#L177)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

"importMarkers" is more consistent with other methods in this class
</blockquote></details>

method names don't exist in a vacuum (functions, however, do). An object will be named (something close to the class name) and the method call is associated with that. So I feel like import makes sense because where it is used will be something like "markers.import()" which- all things named and architected correctly, isn't going to be importing something wildly unrelated.

This is why classes with action names are fine with having an execute method to perform the action, and why they don't need the class name to be suffixed with "UseCase" because that information should be obvious.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt` line 205 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jRK2w8Ct0iXS5zFtC:-N_oXbU-4POzxn4lyZPG:bfhzx26) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/VerseMarkerModel.kt#L205)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this is a great place to add a comment, before the loop, same on the forEach above
</blockquote></details>

What lacks clarity here? If it is possible for the code itself to be more readable such that it doesn't need a comment, that is what I would prefer to achieve.

But if that's impossible I can add a comment.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt` line 452 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jS-Bu10N3ylRQjPnN:-N_ockL00XC66AQ0qgSR:b-g4hx34) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L452)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

maybe chaining would be better?
</blockquote></details>

I wasn't really intending to make a lot of changes here, I just didn't want a non-blocking subscribe going on here because that's a great way to have race conditions.

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767)* status: 0 of 40 files reviewed, 6 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt` line 177 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jPfjKD7nornq2QpSm:-N_oe34xECk7-jOH9lDE:bwprv6i) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/OratureAudioFile.kt#L177)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

method names don't exist in a vacuum (functions, however, do). An object will be named (something close to the class name) and the method call is associated with that. So I feel like import makes sense because where it is used will be something like "markers.import()" which- all things named and architected correctly, isn't going to be importing something wildly unrelated.

This is why classes with action names are fine with having an execute method to perform the action, and why they don't need the class name to be suffixed with "UseCase" because that information should be obvious.
</blockquote></details>

The reason I suggested because I see `addMarker(), addMarkers(), getMarkers()` instead of `add(), get()`. The similar examples could be "markers.add()" or "markers.get()"

**Review by AnonymousWalker — APPROVED** [review]

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767)* status: 0 of 40 files reviewed, 5 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/audio/Markers.kt` line 9 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/767#-N_jMxa4-ff-VlHJdKEi:-N_or7Q_-2-HBUhq2k9P:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a3cd4e354ce344d6a631d56aa1d9446c7e54f9a8/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/audio/Markers.kt#L9)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

could we simplify this method with `val formattedLabel: String` and let the classes implement it
</blockquote></details>

Done.

**Pull request merged**
