### PR TITLE
Publish mp3 from project

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Output directory for book:
```
[bookSlug]/
    chapter-[number].mp3
```

Output directory for resource takes:
```
[bookSlug]-[resource-id]/
    c[chapter#]/
        [raw-take-name].mp3
```

This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/569)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/569)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/integration-test/kotlin/integrationtest/projects/TestProjectExport.kt` line 135 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/569#-N0lKtAQ8XubRTEQTNCO:-N0lKtAREJP6juQ946ZV:bz39j7g) ([raw file](https://github.com/bible-translation-tools/orature/blob/94b916b6937e1c9717c1b066a219bb9195c2194d/jvm/workbookapp/src/integration-test/kotlin/integrationtest/projects/TestProjectExport.kt#L135)):*
> ```Kotlin
>     @Test
>     fun exportMp3ProjectWithMetadata() {
>         val testTake = javaClass.classLoader.getResource("chapter_take.wav").path
> ```

try to solve this with mocks and not an actual file

Or create a file at test runtime, don't commit garbage files

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/569)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/integration-test/kotlin/integrationtest/projects/TestProjectExport.kt` line 135 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/569#-N0lKtAQ8XubRTEQTNCO:-N0ldI0-4-y3M0-k3Lsd:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/94b916b6937e1c9717c1b066a219bb9195c2194d/jvm/workbookapp/src/integration-test/kotlin/integrationtest/projects/TestProjectExport.kt#L135)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

try to solve this with mocks and not an actual file

Or create a file at test runtime, don't commit garbage files
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/569#-:-N1E0IAw0DdshnnsjhSF:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @jsarabia)

**Comment by OpThomasPrime1** [comment]
Verified by QA (Thomas Oliver) on Windows, Linux, and Mac

**Pull request merged**
