### PR TITLE
Project wizard - styling for resource selection 

### PR DESCRIPTION
**Pull request by AnonymousWalker**
image

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/622)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
I have a lot to comment on, but I'm working on examples and such, so I just wanted to block until I can finish a writeup for tomorrow.

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/622#-:-N6PMyOR1K9854WOmN34:b-lc73ov)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @mXaln)

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/622)* status: all files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonPane.kt` line 15 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6SjT4d8II3urdniTor:-N6SjT4d8II3urdniTos:b-riaqm1) ([raw file](https://github.com/bible-translation-tools/orature/blob/7886d475d36b4b3735b106d1ecd012de1034799b/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonPane.kt#L15)):*
> ```Kotlin
> import tornadofx.whenSelected
> 
> class ToggleButtonPane : HBox() {
> ```

If the main purpose of this control is grouping buttons, maybe call it ToggleButtonGroup?
___
*[`jvm/controls/src/main/resources/css/control.css` line 261 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6SjbQK2LU1ZqL0K28X:-N6SjbQK2LU1ZqL0K28Y:b-1xad9k) ([raw file](https://github.com/bible-translation-tools/orature/blob/7886d475d36b4b3735b106d1ecd012de1034799b/jvm/controls/src/main/resources/css/control.css#L261)):*
> ```CSS
> }
> /* -------------- Toggle Group -------------- */
> .wa-toggle-btn-pane {
> ```

maybe .wa-toggle-btn-group?
___
*[`jvm/controls/src/main/resources/css/theme/dark-theme.css` line 127 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6SkAre9yi-xCjfdIAA:-N6SkAre9yi-xCjfdIAB:bvfrlju) ([raw file](https://github.com/bible-translation-tools/orature/blob/7886d475d36b4b3735b106d1ecd012de1034799b/jvm/controls/src/main/resources/css/theme/dark-theme.css#L127)):*
> ```CSS
> 
>     /* toggle button */
>     -wa-toggle-selected: -wa-white-40;
> ```

Why in dark-theme the color of selected button is grey not blue or blueish like it's in light theme?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/622)* status: all files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonPane.kt` line 15 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6SjT4d8II3urdniTor:-N6Sn8_68Si0rtWod8zx:bxqe6pj) ([raw file](https://github.com/bible-translation-tools/orature/blob/7886d475d36b4b3735b106d1ecd012de1034799b/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonPane.kt#L15)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

If the main purpose of this control is grouping buttons, maybe call it ToggleButtonGroup?
</blockquote></details>

Sounds good to me :+1: 
___
*[`jvm/controls/src/main/resources/css/control.css` line 261 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6SjbQK2LU1ZqL0K28X:-N6SnU8u5kUPnkLKDfrV:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/7886d475d36b4b3735b106d1ecd012de1034799b/jvm/controls/src/main/resources/css/control.css#L261)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

maybe .wa-toggle-btn-group?
</blockquote></details>

Done.
___
*[`jvm/controls/src/main/resources/css/theme/dark-theme.css` line 127 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6SkAre9yi-xCjfdIAA:-N6SnDDMB_V8Ayk4VFLQ:b-j9w1b9) ([raw file](https://github.com/bible-translation-tools/orature/blob/7886d475d36b4b3735b106d1ecd012de1034799b/jvm/controls/src/main/resources/css/theme/dark-theme.css#L127)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Why in dark-theme the color of selected button is grey not blue or blueish like it's in light theme?
</blockquote></details>

I had the same question but the design suggested that color

**Comment by jsarabia** [comment]
MicrosoftTeams-image (4)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/622)* status: 2 of 7 files reviewed, 9 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonData.kt` line 3 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6To2q23HkCYTBacq3r:-N6To2q33Ii_mhuANRQn:b-qfv1pl) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonData.kt#L3)):*
> ```Kotlin
> package org.wycliffeassociates.otter.jvm.controls.toggle
> 
> class ToggleButtonData(
> ```

The purpose of the Control/Skinnable pattern is exactly for this purpose; to separate the View (skin) from the Model (control). It would be best to use that pattern which we already use, and is what is intended in JavaFX than to reinvent it in a stripped down, clunky way.

Different Skins can be set based on CSS, and we can make new ones when UI design changes, but the actual usage, the inserting into the view, doesn't have to change BECAUSE the Control (which houses the data and actions) is actually the node added to the view tree.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt` line 96 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U3grv8Vo_AsQxOTL_:-N6U3grv8Vo_AsQxOTLa:bzh2r58) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt#L96)):*
> ```Kotlin
>                 addClass("book-wizard__resource-tab-group")
>                 add(
>                     ToggleButtonGroup().apply {
> ```

why a nested hbox anyway?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt` line 150 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U3v0h1TUFFhR5YHvQ:-N6U3v0h1TUFFhR5YHvR:ba2avao) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt#L150)):*
> ```Kotlin
> 
>     private fun buildResourceSelections(toggleGroup: ToggleButtonGroup) {
>         viewModel.sourceCollections.onChange {
> ```

This all feels really messy- I feel like we all could stand to read more on ViewModels and how to best implement them, and I think it would result in cleaner, more readable view code. My instinct is that the list<ToggleButton> should probably live in the viewmodel, not here, and it's produced from list<resources>.map {  }
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt` line 16 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U0-ss8TxC1rl6qllI:-N6U0-ss8TxC1rl6qllJ:b-mgxelz) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt#L16)):*
> ```Kotlin
> import tornadofx.whenSelected
> 
> class ToggleButtonGroup : HBox() {
> ```

I don't really think this needs to be its own source file and layout. At the moment we're not using it anywhere else; This could just be:

hbox {
     togglegroup {
            for(resource in resources) {
                togglebutton()
            }
     }
}

you could also make it a function to make it more functional/declarative, name the hbox and replace with a new one when the list changes.
The base javafx toggle button is really all you need here with some small styling, shouldn't need a skin.


The only reason I would extract this all out into a control/skin is if we used it in a bunch of places and wanted a horizontal and vertical version, in which the orientation skin could be set using CSS
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt` line 39 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U2_KU7R5rVo62JLd_:-N6U2_KU7R5rVo62JLda:bd4t1h9) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt#L39)):*
> ```Kotlin
>                 // styling for first & last element
>                 toggleClass("first-child", items.indexOf(data) == 0)
>                 toggleClass("last-child", items.indexOf(data) == items.size - 1)
> ```

I don't like having specific CSS based on position of the item. This means that the item has awareness of its parent, and its relationship with one another in essence. 

The border radius is more a property of the hbox, but it doesn't clip the children, so if the child nodes don't have the border radius, then the rectangle edge leaks out of the hbox...

But I think that's really what we want to do; rather than requiring the styling of the items themselves be stateful, clip:

https://fxdocs.github.io/docs/html5/index.html#_clipping
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt` line 45 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U-i8bCnimiT5MEnEI:-N6U-i8bCnimiT5MEnEJ:bt3txwp) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt#L45)):*
> ```Kotlin
> }
> 
> private class RadioToggleButton(text: String = "") : ToggleButton(text) {
> ```

I think the RadioButton name confusing here, but also- You're already having to make a control, this could be combined with the data.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/622)* status: 2 of 7 files reviewed, 9 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt` line 96 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U3grv8Vo_AsQxOTL_:-N6ULclr4SS3bwkK_rx0:bhmhk5s) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt#L96)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why a nested hbox anyway?
</blockquote></details>

Nice catch! Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt` line 150 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U3v0h1TUFFhR5YHvQ:-N6US-PTAzlGTHSzom2K:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt#L150)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This all feels really messy- I feel like we all could stand to read more on ViewModels and how to best implement them, and I think it would result in cleaner, more readable view code. My instinct is that the list<ToggleButton> should probably live in the viewmodel, not here, and it's produced from list<resources>.map {  }
</blockquote></details>

Done.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt` line 16 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U0-ss8TxC1rl6qllI:-N6UJMrl0cv_ZJ55EpH8:b-t1bpld) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt#L16)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I don't really think this needs to be its own source file and layout. At the moment we're not using it anywhere else; This could just be:

hbox {
     togglegroup {
            for(resource in resources) {
                togglebutton()
            }
     }
}

you could also make it a function to make it more functional/declarative, name the hbox and replace with a new one when the list changes.
The base javafx toggle button is really all you need here with some small styling, shouldn't need a skin.


The only reason I would extract this all out into a control/skin is if we used it in a bunch of places and wanted a horizontal and vertical version, in which the orientation skin could be set using CSS
</blockquote></details>

I believe reusability is the reason I put down the effort to make it generic and independent. I have seen the same design proposed for book export (selection between mp3, source, backup...) and that's my concern. It's better to refactor it before we eventually have to clean up when Thomas suggest a similar control.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt` line 39 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U2_KU7R5rVo62JLd_:-N6ULjlHCABTlJA-FCpg:bqu3b4i) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt#L39)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I don't like having specific CSS based on position of the item. This means that the item has awareness of its parent, and its relationship with one another in essence. 

The border radius is more a property of the hbox, but it doesn't clip the children, so if the child nodes don't have the border radius, then the rectangle edge leaks out of the hbox...

But I think that's really what we want to do; rather than requiring the styling of the items themselves be stateful, clip:

https://fxdocs.github.io/docs/html5/index.html#_clipping
</blockquote></details>

I believe clipping will affect the focused border of the buttons
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt` line 45 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/622#-N6U-i8bCnimiT5MEnEI:-N6UKPWU90eQtX4Pm4oV:b-2vguug) ([raw file](https://github.com/bible-translation-tools/orature/blob/0ec9d4d97fc45203e545b231378b125a96aca9b9/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/toggle/ToggleButtonGroup.kt#L45)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I think the RadioButton name confusing here, but also- You're already having to make a control, this could be combined with the data.
</blockquote></details>

I see commonly used properties are retained in tornadofx like button(text: String), label(text: String)... instead of enforcing
` button { text = ... }, 
label { text = .... }
`

**Review by mXaln — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 2 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/622)* status: all files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/622#-:-N6sl3uRBxgYgebQfGwT:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

**Pull request merged**
