### PR TITLE
Modify database to support verse bridges

### PR DESCRIPTION
**Pull request by jsarabia**
Importing projects using Versification will pre-allocate content for all verses within a chapter.

When verse bridges occur in source text, all but the first content for the bridge should be marked as bridged.

Additionally, in order to know the proper verse range for verse bridges (for use in display), the end verse is now stored in the content entity table.

As end is a reserved keyword in sql, the column name is v_end

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717)* status: all files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt` line 291 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQdVthE3dt5QrwasgB:-NQQdVthE3dt5QrwasgC:b-62g4pk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt#L291)):*
> ```Kotlin
>                     .execute()
> 
>                 clearProjectTables(dsl)
> ```

It looks like this deletes a lot of content from the database. Was this by intent?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 116 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQgILQ4c55fInOGHYa:-NQQgILQ4c55fInOGHYb:bmlpur7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L116)):*
> ```Kotlin
>     ): Single<ImportResult> {
>         val rcMetadata = getMetadataForContainer(rc) ?: run { return Single.just(ImportResult.IMPORT_ERROR)}
>         val projects = collectionRepository.getSourceProjects().map { it.filter { it.resourceContainer == rcMetadata } }.blockingGet()
> ```

very long line



_Code quote:_
```Kotlin
  private fun OtterTree<CollectionOrContent>.toChapterContentMapFromBook(): Map<Collection, MutableList<Content>>
```
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 157 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQgZVnDMt3XZPhR_Xj:-NQQgZVnDMt3XZPhR_Xk:b-zie685) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L157)):*
> ```Kotlin
>                         for (i in (match.start+1)..match.end) {
>                             val found = databaseContent.find { it.start == i && it.type != ContentType.META }
>                             if (found != null && found is Content) {
> ```

checking if `found` is instance of Content is redundant here. If it's not null it will be always a Content
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 185 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQgnUkDH96j17J8-ZO:-NQQgnUl7Fq2IyhrnDy9:bmlpur7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L185)):*
> ```Kotlin
> 
>     fun OtterTree<CollectionOrContent>.toChapterContentMap(): Map<Collection, MutableList<Content>> {
>         val isBook = children.any { it.value is Collection && (it as OtterTree<CollectionOrContent>).children.any{ it.value is Content } }
> ```

very long line
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 205 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQgxvnCp7TqgJfUmsH:-NQQgxvnCp7TqgJfUmsI:bmlpur7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L205)):*
> ```Kotlin
> 
>     private fun OtterTree<CollectionOrContent>.toChapterContentMapFromBook(): Map<Collection, MutableList<Content>> {
>         val isBook = children.any { it.value is Collection && (it as OtterTree<CollectionOrContent>).children.any{ it.value is Content } }
> ```

very long line
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 226 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQh3OPA3GmoH3ql_NE:-NQQh3OPA3GmoH3ql_NF:bmlpur7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L226)):*
> ```Kotlin
>         }
>         val metadata = resourceMetadataDao.fetchAll().filter { entity ->
>             entity.derivedFromFk == null && entity.identifier == rc.manifest.dublinCore.identifier && entity.languageFk == language.id
> ```

very long line

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717)* status: all files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt` line 291 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQdVthE3dt5QrwasgB:-NQQjyTiBFyuQpEalyim:bts8fy6) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt#L291)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

It looks like this deletes a lot of content from the database. Was this by intent?
</blockquote></details>

yep; the thought here was that (unfortunately) trying to migrate existing data would be incredibly error prone due to needing to bridge all potential verse bridges from the source and target, as well as applying versification to the source. I felt like the easier solution would just be to remove the RCs from the database and restore them via import from disk, which is something we already do, should be correct already, and would more reliably handle this situation.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717)* status: 13 of 14 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 116 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQgILQ4c55fInOGHYa:-NQR8WbZ12H8o6BIYAnA:b-7ql1td) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L116)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

very long line
</blockquote></details>

fixed
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 157 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQgZVnDMt3XZPhR_Xj:-NQRCaxL9XEt-ocPWy7e:bjzmcav) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L157)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

checking if `found` is instance of Content is redundant here. If it's not null it will be always a Content
</blockquote></details>

good catch, thanks!
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 185 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQgnUkDH96j17J8-ZO:-NQRC_j22ELXEXXI8TE9:b-7ql1td) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L185)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

very long line
</blockquote></details>

fixed
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 205 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQgxvnCp7TqgJfUmsH:-NQRCXqg-Kw3N2na0XTP:b-7ql1td) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L205)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

very long line
</blockquote></details>

fixed
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 226 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQh3OPA3GmoH3ql_NE:-NQRCYwMD6qmH7VpORuD:b-7ql1td) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L226)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

very long line
</blockquote></details>

fixed

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717)* status: 11 of 14 files reviewed, 8 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt` line 291 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQdVthE3dt5QrwasgB:-NQRRs0P1tAPijhWXBn6:b-2ps7t3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt#L291)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

yep; the thought here was that (unfortunately) trying to migrate existing data would be incredibly error prone due to needing to bridge all potential verse bridges from the source and target, as well as applying versification to the source. I felt like the easier solution would just be to remove the RCs from the database and restore them via import from disk, which is something we already do, should be correct already, and would more reliably handle this situation.
</blockquote></details>

I believe this is a perfect place to have comments/documentation
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/ContentDao.kt` line 330 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQRS8Go5gpkDkPkPaY8:-NQRS8Go5gpkDkPkPaY9:bmsfl3s) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c3ce0d1629c5bc6ee7991e67f2c8b2791bd476d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/ContentDao.kt#L330)):*
> ```Kotlin
>             .set(CONTENT_ENTITY.TEXT, entity.text)
>             .set(CONTENT_ENTITY.FORMAT, entity.format)
>             .set(CONTENT_ENTITY.BRIDGED, if (entity.bridged) 1 else 0)
> ```

should `set(__.DRAFT_NUMBER)` be included?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 261 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQRSd4d3PcEjGCwkjSd:-NQRSd4d3PcEjGCwkjSe:b-lwo98) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c3ce0d1629c5bc6ee7991e67f2c8b2791bd476d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L261)):*
> ```Kotlin
>             } ?: run { return null }
> 
>         return ResourceMetadataMapper().mapFromEntity(metadata, LanguageMapper().mapFromEntity(language))
> ```

it'd be nicer with some line breaks to increase readability

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717)* status: 10 of 14 files reviewed, 8 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt` line 291 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQQdVthE3dt5QrwasgB:-NQRYOT6Ch8lxVu6fOw2:bpz0qqk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c5d45084765db095143838418a7771a2ee3049b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt#L291)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

I believe this is a perfect place to have comments/documentation
</blockquote></details>

Sure, added.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/ContentDao.kt` line 330 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQRS8Go5gpkDkPkPaY8:-NQRXBlBDjAxg6Qq0DB5:b-9ajto9) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c3ce0d1629c5bc6ee7991e67f2c8b2791bd476d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/daos/ContentDao.kt#L330)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

should `set(__.DRAFT_NUMBER)` be included?
</blockquote></details>

Good catch, thanks!!!
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt` line 261 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717#-NQRSd4d3PcEjGCwkjSd:-NQRXcD0CRcRFyUFUpfc:b-7ql1td) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/6c3ce0d1629c5bc6ee7991e67f2c8b2791bd476d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ResourceContainerRepository.kt#L261)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

it'd be nicer with some line breaks to increase readability
</blockquote></details>

fixed

**Review by AnonymousWalker — APPROVED** [review]

**Review by mXaln — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/717)* status: all files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

**Pull request merged**
