### PR TITLE
Save and quit before navigating home from marker app (OT-884)

### PR DESCRIPTION
**Pull request by darrellcolehill**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147)

### CODE REVIEW

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @darrellcolehill and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/NavigationMediator.kt` line 104 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147#-Nz4j5-S8oZ0uQc14lxd:-Nz4j5-S8oZ0uQc14lxe:b-ex6lbp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/260061414f97ed4bd51c415bc5ff5ebf175b9ad0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/NavigationMediator.kt#L104)):*
> ```Kotlin
>                 val homePage = find<HomePage2>()
>                 fire(NavigationRequestEvent(homePage))
>                 NavigationRequestEvent(homePage)
> ```

what's this line for?

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/NavigationMediator.kt` line 104 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147#-Nz4j5-S8oZ0uQc14lxd:-Nz4oqxQ3C2Ent0ai-Iz:bbzezu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/260061414f97ed4bd51c415bc5ff5ebf175b9ad0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/NavigationMediator.kt#L104)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

what's this line for?
</blockquote></details>

Thanks for catching that! I am not sure why that is there.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147#-:-NzFHPQS3p17Wfi2CXRc:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @darrellcolehill)

___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 72 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147#-NzFMkep5_DRBnVGDIKH:-NzFMkep5_DRBnVGDIKI:b-f6qfbd) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c13597cad973ae9679650165e873ec0a455992b9/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L72)):*
> ```Kotlin
>         }
> 
>         subscribe<NavigationRequestBlockedEvent> {
> ```

Would it be possible to use the existing `PluginCloseRequestEvent` approach? I believe marker app is also a "plugin" and we have solved a similar problem using that event.

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 72 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147#-NzFMkep5_DRBnVGDIKH:-NzFOpp28tIhNy2Tc9pj:bz2jbbt) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c13597cad973ae9679650165e873ec0a455992b9/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L72)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Would it be possible to use the existing `PluginCloseRequestEvent` approach? I believe marker app is also a "plugin" and we have solved a similar problem using that event.
</blockquote></details>

The issue I was having with that was with coordinating the narration view model since it is still docked. Are you thinking of firing the PluginClosRequestEvent on home button click when the marker app is open?

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 182 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147#-NzU47DD8SjSHmLsW4hv:-NzU47DD8SjSHmLsW4hw:b46seix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/23ac72d663d7c6f778be31c31334f1b9cb35a3ad/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L182)):*
> ```Kotlin
>                 }
>             } else if (pluginOpenedProperty.value) {
>                 navigator.navigateHomeOnPluginClosed = true
> ```

@AnonymousWalker This could be modified by doing the following:

1) Move navigateHomeOnPluginClosed from the navigator, to NarrationViewModel
2) Allow PluginClosedEvent to take in an optional parameter named something like "naviateHome" that has a default value of false
3) Have the navigator's subscription to PluginClosedEvent navigate home when navigateHome == true
4) Pass the value of navigateHome when firing PluginClosedEvent in onChapterReturnFromPlugin

I am not crazy about adding another Boolean in the NarrationViewModel, but the above steps seem more in line with what we discussed earlier.

**Review by AnonymousWalker — APPROVED** [review]

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @darrellcolehill and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 186 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147#-NzcP1AC5GBiwZq-1aKq:-NzcP1ADBaV-rLWh6agf:bbic4n0) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/3761a05fb0421c4ec2e1dd7777d145a967ec64c2/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L186)):*
> ```Kotlin
> 
>         subscribe<NavigationRequestEvent>() {
>             if (it.view == find<HomePage2>() && pluginOpenedProperty.value) {
> ```

could we do `it.view is HomePage2` instead?

**Review by jsarabia — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1147#-:-NzdfTgn5oM7Xe3AkT0U:bnfp4nl)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @darrellcolehill)

**Pull request merged**
