### PR TITLE
Added "not started" state to the chapter card

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/252)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/252)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ChapterCard.kt, line 25 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/252#-MVSSDs1291uLphQfc5D:-MVSSDs1291uLphQfc5E:b9ak14) ([raw file](https://github.com/bible-translation-tools/otter/blob/5110d61c3b4d23c6fb16103b29135de5644214bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ChapterCard.kt#L25)):*
> ```Kotlin
>     val recordedChunksProperty = SimpleIntegerProperty(0)
>     val selectedChunksProperty = SimpleIntegerProperty(0)
>     val hasChunksProperty = SimpleBooleanProperty(false)
> ```

userHasChunkedProperty?
___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/skins/cards/ChapterCardSkin.kt, line 81 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/252#-MVSS61a7ovJ2wxOAHdv:-MVSS61a7ovJ2wxOAHdw:byps3so) ([raw file](https://github.com/bible-translation-tools/otter/blob/5110d61c3b4d23c6fb16103b29135de5644214bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/skins/cards/ChapterCardSkin.kt#L81)):*
> ```Kotlin
> 
>         progressBars.apply {
>             visibleWhen(card.hasChunksProperty)
> ```

for now this should just be visible = false

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/252)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ChapterCard.kt, line 25 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/252#-MVSSDs1291uLphQfc5D:-MVVU_Ls55lEkonOqQM8:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/5110d61c3b4d23c6fb16103b29135de5644214bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ChapterCard.kt#L25)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

userHasChunkedProperty?
</blockquote></details>

Done.
___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/skins/cards/ChapterCardSkin.kt, line 81 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/252#-MVSS61a7ovJ2wxOAHdv:-MVVUljL5ikpogcWC38b:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/5110d61c3b4d23c6fb16103b29135de5644214bf/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/skins/cards/ChapterCardSkin.kt#L81)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

for now this should just be visible = false
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/252)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ChapterCard.kt, line 25 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/252#-MVWVt713-cDZiSNt5f-:-MVWVt713-cDZiSNt5f0:b-xdlhly) ([raw file](https://github.com/bible-translation-tools/otter/blob/43a0ea2473cc4bc3b35dd2c825cd8fb55ee0e213/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ChapterCard.kt#L25)):*
> ```Kotlin
>     val recordedChunksProperty = SimpleIntegerProperty(0)
>     val selectedChunksProperty = SimpleIntegerProperty(0)
>     val userHasChunkedProperty = SimpleBooleanProperty(false)
> ```

should we set this to true? Otherwise won't all cards be showing the text "Not Started"?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/252)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ChapterCard.kt, line 25 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/252#-MVWVt713-cDZiSNt5f-:-MVWY1wF8i-jh0RWx8gN:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/43a0ea2473cc4bc3b35dd2c825cd8fb55ee0e213/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/ChapterCard.kt#L25)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

should we set this to true? Otherwise won't all cards be showing the text "Not Started"?
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/252#-:-MVWYoMK4XSr23FhDQb3:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

**Pull request merged**
