### PR TITLE
Search bar - UI Control

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/741)

### CODE REVIEW

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/741#-:-NUMHVcmAt6C-SUw4zF8:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/741)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/demo/ui/fragments/TextFieldFragment.kt` line 7 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/741#-NUS-_ic-PC9xgM3mg-6:-NUS-_ic-PC9xgM3mg-7:b-fo8m0s) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/fbf8dafc6972e9d3304d29bab8e2a6a5d7d84a76/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/demo/ui/fragments/TextFieldFragment.kt#L7)):*
> ```Kotlin
> import tornadofx.*
> 
> class TextFieldFragment : View() {
> ```

This should inherit a Fragment

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/741)* status: all files reviewed, 1 unresolved discussion (waiting on @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/demo/ui/fragments/TextFieldFragment.kt` line 7 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/741#-NUS-_ic-PC9xgM3mg-6:-NUS1cxq2v72VDpgllJg:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/fbf8dafc6972e9d3304d29bab8e2a6a5d7d84a76/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/demo/ui/fragments/TextFieldFragment.kt#L7)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

This should inherit a Fragment
</blockquote></details>

Done.

**Review by mXaln — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/741)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AnonymousWalker)

**Review by jsarabia — APPROVED** [review]

**Pull request merged**
