### PR TITLE
Insert content derivative when creating chunks/verses

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/676)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/676)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 658 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/676#-ND8_kJfA6rASB-x9Ecz:-ND8_kJfA6rASB-x9Ed-:b-i3ir15) ([raw file](https://github.com/bible-translation-tools/orature/blob/75d4ba51b00745e4f5faff0b0aec0ddffb8cfd8c/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L658)):*
> ```Kotlin
>                     }
>             }
>             .toList()
> ```

can you explain why you replace collectInto with toList?
What are the differences between the two?
How can we know this is safe to replace?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/676)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 658 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/676#-ND8_kJfA6rASB-x9Ecz:-ND9-oK71m4H635dcUkb:bvnocpv) ([raw file](https://github.com/bible-translation-tools/orature/blob/75d4ba51b00745e4f5faff0b0aec0ddffb8cfd8c/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L658)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can you explain why you replace collectInto with toList?
What are the differences between the two?
How can we know this is safe to replace?
</blockquote></details>

The toList() gives us an immutable List whereas the collect()/collectInto() gives a mutable (custom) collection/data structure. After I read it, I believe they are quite similar in regard to safety, although the collect() can modify the state/object it receives

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/676)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 658 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/676#-ND8_kJfA6rASB-x9Ecz:-ND9Eig85Q1nQfq4qExc:buh6wut) ([raw file](https://github.com/bible-translation-tools/orature/blob/75d4ba51b00745e4f5faff0b0aec0ddffb8cfd8c/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L658)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

The toList() gives us an immutable List whereas the collect()/collectInto() gives a mutable (custom) collection/data structure. After I read it, I believe they are quite similar in regard to safety, although the collect() can modify the state/object it receives
</blockquote></details>

Does the list contain elements emitted thus far, or all elements that will emit? How do you know?

What indicates that the list is immutable from toList?

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/676)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 658 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/676#-ND8_kJfA6rASB-x9Ecz:-ND9FAW95nO1t4YR6Ns9:b-v5uca4) ([raw file](https://github.com/bible-translation-tools/orature/blob/75d4ba51b00745e4f5faff0b0aec0ddffb8cfd8c/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L658)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Does the list contain elements emitted thus far, or all elements that will emit? How do you know?

What indicates that the list is immutable from toList?
</blockquote></details>

Also- would this be different if the observable was a relay or subject?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/676)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt` line 658 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/676#-ND8_kJfA6rASB-x9Ecz:-ND9F_5z6Gj_S23DfEx1:b8vjbkg) ([raw file](https://github.com/bible-translation-tools/orature/blob/75d4ba51b00745e4f5faff0b0aec0ddffb8cfd8c/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L658)):*
> instructing the ObservableSource to compose a list of all of these items and then to invoke the Observer's onNext function once, passing it the entire list, by calling the ObservableSource's toList method prior to calling its subscribe method.
Note that this operator requires the upstream to signal onComplete for the accumulated list to be emitted

> Sources that are infinite and never complete will never emit anything through this operator and an infinite source may lead to a fatal OutOfMemoryError.

For sources that are never completes, we don't use this operator. In this case, since we have a finite source `chunks` that the Observable based from, we are not concerned about Relay/Subject.

toList(): List<T> returns a List, which is immutable. `collect()` indicated in its documentation that the collection is mutable.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/676#-:-ND9wueW0zOZxu0hmf4N:bnfp4nl)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

**Pull request merged**
