### PR TITLE
Migrates Database to add Marker plugins

### PR DESCRIPTION
**Pull request by jsarabia**
Introduces a DatabaseMigrator class for use with future database migrations.

Versions the database.

Alters the Audio Plugin table to add a column for the marker plugin.

Reduces Dagger component builds to one location, and refactors places where it was previously used.

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/228)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/228)* status: all files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/di/persistence/PersistenceComponent.kt, line 28 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/228#-MRdgj0u9otgvBGRTs0I:-MRdgj0u9otgvBGRTs0J:b-edpzhm) ([raw file](https://github.com/bible-translation-tools/otter/blob/247a83931a0d70d02cbc315e3505f255ffbcd303/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/di/persistence/PersistenceComponent.kt#L28)):*
> ```Kotlin
>     // Need inject for audio plugin repo so audio plugin registrar can be built
>     fun injectAudioPluginRepository(): IAudioPluginRepository
>     fun injectRegistrar(): IAudioPluginRegistrar
> ```

Maybe injectAudioPluginRegistrar()?  injectRegistrar sounds very general 
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt, line 10 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/228#-MRdhT65CCXyHvl2iISl:-MRdhT65CCXyHvl2iISm:b-ds2enb) ([raw file](https://github.com/bible-translation-tools/otter/blob/247a83931a0d70d02cbc315e3505f255ffbcd303/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt#L10)):*
> ```Kotlin
> 
> const val SCHEMA_VERSION = 2
> const val DATABASE_INSTALLABLE_NAME = "database"
> ```

I would make it uppercase (DATABASE) like other installables.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt, line 39 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/228#-MRdi-z26eYXnLjS2dGs:-MRdi-z26eYXnLjS2dGt:b-gogbq2) ([raw file](https://github.com/bible-translation-tools/otter/blob/247a83931a0d70d02cbc315e3505f255ffbcd303/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt#L39)):*
> ```Kotlin
>                 .where(InstalledEntity.INSTALLED_ENTITY.NAME.eq(DATABASE_INSTALLABLE_NAME))
>                 .fetch { record -> record.getValue(InstalledEntity.INSTALLED_ENTITY.VERSION) }
>                 .first()
> ```

maybe single()? Since there always should be only one DATABASE installable

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/228)* status: 8 of 13 files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/di/persistence/PersistenceComponent.kt, line 28 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/228#-MRdgj0u9otgvBGRTs0I:-MRe859r0_1cSDGCrSKe:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/247a83931a0d70d02cbc315e3505f255ffbcd303/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/di/persistence/PersistenceComponent.kt#L28)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Maybe injectAudioPluginRegistrar()?  injectRegistrar sounds very general 
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt, line 10 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/228#-MRdhT65CCXyHvl2iISl:-MRe85oaBJUI2sc4_X63:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/247a83931a0d70d02cbc315e3505f255ffbcd303/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt#L10)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I would make it uppercase (DATABASE) like other installables.
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt, line 39 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/228#-MRdi-z26eYXnLjS2dGs:-MRe86SL5ifOsXacKL_3:bglpsg8) ([raw file](https://github.com/bible-translation-tools/otter/blob/247a83931a0d70d02cbc315e3505f255ffbcd303/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt#L39)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

maybe single()? Since there always should be only one DATABASE installable
</blockquote></details>

Jooq does not offer a "single" method unfortunately

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/228)* status: 8 of 13 files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt, line 39 at r2](https://reviewable.io/reviews/bible-translation-tools/otter/228#-MRdi-z26eYXnLjS2dGs:-MReAiJU2Ywn2FBtvILG:b-68brrd) ([raw file](https://github.com/bible-translation-tools/otter/blob/247a83931a0d70d02cbc315e3505f255ffbcd303/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/database/DatabaseMigrator.kt#L39)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Jooq does not offer a "single" method unfortunately
</blockquote></details>

nevermind, it does contain fetchSingle

**Review by mXaln — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/228)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
