### PR TITLE
Allow to open Chapter Review file in an external app

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1023)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
could we handle the case when there's no plugin available? I see narration handle that already

**Review by mXaln — COMMENTED** [review]
Good catch. Done.

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1023#-:-Nq7IAeI6wyohBpv4Fjs:boj1qgt)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @AnonymousWalker and @jsarabia)

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
Great! There is an important feature needed to fit this into the workflow: undo/redo. We want to allow the user to undo/redo the changes made to the take from the plugin, which may require swapping between chapter takes.

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1023#-:-Nq840-sEHlppOXG0i50:b-284ctx)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by AnonymousWalker — APPROVED** [review]
Looks like we can have a follow-up PR for undo/redo!
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1023#-:-Nq8OqhFCC3ij31T1io1:bf913oh)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @jsarabia)

**Pull request merged**
