### PR TITLE
Support Verse highlight/Karaoke for Narration playback (OT-815)

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/992)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/992)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 237 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/992#-Nordk4ICPmqPuu8V7pH:-Nordk4ICPmqPuu8V7pI:bqvdu5i) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/bcb00ba63f70922c733251a0f9533e0eaa85251d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L237)):*
> ```Kotlin
>         disposables.clear()
>         disposers.forEach { it.dispose() }
>         disposables.clear()
> ```

Did you want `disposers.clear()` here?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/992)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 237 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/992#-Nordk4ICPmqPuu8V7pH:-NorgxNI-b0an1O02WvO:b-hx53va) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/bcb00ba63f70922c733251a0f9533e0eaa85251d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L237)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Did you want `disposers.clear()` here?
</blockquote></details>

nice catch! I changed it

**Review by mXaln — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/992#-:-NorlVbqA-F0rqPB5y5u:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/992#-:-Now69v-6toot0RObs8S:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
