### PR TITLE
Fixed style of all focusable items;

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/562)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
- I think the focused border of this "Previous Verse" button disappear into the background

image

- Delete Project button may need border inset, too
image

- Not sure what happened but the font size is unusually large for Cancel/Continue button in Recorder & Marker
image

**Comment by AnonymousWalker** [comment]
Please merge from dev

**Review by mXaln — COMMENTED** [review]
Merged with dev. 
Changed dark border to light in dark theme. 
I have changed the button on Recoder and Verse Marker App to our standard button, hence the increase of text size. I have also changed the size of button icon to be the standard.

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/562#-:-N0Atl9yCoEnbRMUF9kR:b-6die7y)* status: 0 of 37 files reviewed, all discussions resolved (waiting on @AnonymousWalker and @jsarabia)

**Review by AnonymousWalker — APPROVED** [review]
Thanks for the changes
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/562#-:-N0B81M0698PnrKbut8S:b-ahhndh)* status: 0 of 39 files reviewed, all discussions resolved (waiting on @jsarabia)

**Comment by OpThomasPrime1** [comment]
Verified by QA (Thomas Oliver) Windows, Linux, Apple

**Pull request merged**
