### PR TITLE
Marker Titles in MarkerPlacementModel

### PR DESCRIPTION
**Pull request by jsarabia**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001)

### CODE REVIEW

**Review by AnonymousWalker — CHANGES_REQUESTED** [review]
> Reviewed 8 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001)* status: 4 of 17 files reviewed, 8 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/audio/Markers.kt` line 39 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfS7Bz2-WznZoVWtLo:-NpfS7Bz2-WznZoVWtLp:ba92i7m) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/audio/Markers.kt#L39)):*
> ```Kotlin
> const val VERSE_SORT_START = 10_000
> const val CHUNK_SORT_START = 100_000
> const val UNKNOWN_SORT_START = 100_000_000
> ```

these values can be private
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/audio/Markers.kt` line 99 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfT547DPUb6pdcu7PV:-NpfT5484q2oIVXS7rcA:bjgluik) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/audio/Markers.kt#L99)):*
> ```Kotlin
>     // Note: this will overflow an int if the position of an unknown marker is beyond ~2GB worth of audio frames
>     // which is about 6 hours for 16bit 44.1khz mono
>     override val sort = UNKNOWN_SORT_START + location
> ```

Guess we can officially document it
```
/** 
*/
```
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt` line 44 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfUDxx7oFDjbktWwxe:-NpfUDxx7oFDjbktWwxf:b-4t00v6) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt#L44)):*
> ```Kotlin
> 
> /**
>  * State Machine for placing markers
> ```

I'm trying to find the use of states and transitions within this class but I am unable to. Should we consider this as a Marker Model or Marker Use Case, instead of State Machine?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt` line 50 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfX_-M0SVHKB_hgSM-:-NpfX_-M0SVHKB_hgSM0:b-6kut7g) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt#L50)):*
> ```Kotlin
>  * @param audio The audio file being operated on
>  *
>  * @param reservedMarkers the exhaustive list of all AudioMarkers that need to be placed and accounted for, which
> ```

this parameter sounds like `primaryMarkers`, to be more consistent with `primaryPlacementType`
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt` line 60 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfTa9M7wpkfD7bg3Gr:-NpfTa9N9tyZsHzxsbYr:b4th0jx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt#L60)):*
> ```Kotlin
>     private val logger = LoggerFactory.getLogger(MarkerPlacementModel::class.java)
> 
>     private val primaryType: Class<out AudioMarker> = when (primaryPlacementType) {
> ```

given the enum of MarkerPlacementType available in the constructor, can we just use it for the whole class and remove this property `primaryType`?
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/marker/MarkerTrackControl.kt` line 283 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfUs6J2vJh9oTHjQ0y:-NpfUs6J2vJh9oTHjQ0z:b-i8dggu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/marker/MarkerTrackControl.kt#L283)):*
> ```Kotlin
> 
>     init {
>         initialize()
> ```

just a reminder for later, we can integrate Max's PR to wrap the initialization/destructor calls within onDock/unDock respectively
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/IMarkerViewModel.kt` line 50 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfVPel-g4QKMJ6XAu7:-NpfVPel-g4QKMJ6XAu8:bel38yv) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/IMarkerViewModel.kt#L50)):*
> ```Kotlin
>             markerModel.deleteMarker(id)
>             markers.clear()
>             markers.setAll(markerModel.markerItems.map { it.copy() })
> ```

[setAll()](https://docs.oracle.com/javase/8/javafx/api/javafx/collections/ObservableList.html#setAll-java.util.Collection-) seems to clear the list and addAll(), I guess we can make it intentional with these calls:
```
markers.clear()
markers.addAll(markerModel.markerItems.toList())
```
___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt` line 161 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfWdn2B4lJIsH88WTb:-NpfWdn2B4lJIsH88WTc:btchoti) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L161)):*
> ```Kotlin
>         val verses = verseLabelsToMarkers(labels)
>         val titles = getTitleMarkers(params.named["book_slug"], params.named["chapter_number"])
>         return listOf(*titles, *verses)
> ```

How about `return (titles + verses).toList()`?

**Comment by AnonymousWalker** [comment]
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt` line 66 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfYInWDN-HP9J4p7Fj:-NpfYInWDN-HP9J4p7Fk:bhq4rh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt#L66)):*
> ```Kotlin
> 
>     private val undoStack: Deque<MarkerOperation> = ArrayDeque()
>     private val redoStack: Deque<MarkerOperation> = ArrayDeque()
> ```

`Deque<IUndoable>` would be sufficient for these stacks

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001)* status: 4 of 17 files reviewed, 9 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt` line 50 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfX_-M0SVHKB_hgSM-:-NpfemyJ-kwDENSHFaXa:b8btaeo) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt#L50)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this parameter sounds like `primaryMarkers`, to be more consistent with `primaryPlacementType`
</blockquote></details>

No. This is the preallocated list of all markers that will be placed by the user, and, as stated in the description here, includes markers that are not primaryMarkers. Examples are provided in the description as well.

That is to say, you'll have (currently, but could change in the furture, thus not enforced here):
1 and only 1 Book Marker (only included on a chapter 1, but enforced by the constructing class)
1 and only 1 Chapter Marker
Many markers of Primary Type (either Verse or Chunk)

Other things could be present that may some day be desirable to be placed in a chapter. This class doesn't care, as it just wants an in order list of everything you want to place.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt` line 60 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfTa9M7wpkfD7bg3Gr:-Npffu0g5M9Oa_TIXiyO:b2iqo7z) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt#L60)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

given the enum of MarkerPlacementType available in the constructor, can we just use it for the whole class and remove this property `primaryType`?
</blockquote></details>

Then I have to put this when statement everywhere it's used. I use the enum for the sole purpose of restricting the allowed marker types. I don't want the enum. I want the class. 

There actually isn't even an extra property in the sense that the constructor argument is used only in the constructor, but isn't saved because I omitted the use of val.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001)* status: 4 of 17 files reviewed, 9 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt` line 66 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfYInWDN-HP9J4p7Fj:-NpfiMd504tG1vcK6lI8:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/model/MarkerPlacementModel.kt#L66)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`Deque<IUndoable>` would be sufficient for these stacks
</blockquote></details>

Done.
___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/IMarkerViewModel.kt` line 50 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1001#-NpfVPel-g4QKMJ6XAu7:-NpfpwTT199_Qyq_jAR1:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/312a5a362e3ab2ad5b1eed0b27cadf3a38129460/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/IMarkerViewModel.kt#L50)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

[setAll()](https://docs.oracle.com/javase/8/javafx/api/javafx/collections/ObservableList.html#setAll-java.util.Collection-) seems to clear the list and addAll(), I guess we can make it intentional with these calls:
```
markers.clear()
markers.addAll(markerModel.markerItems.toList())
```
</blockquote></details>

Done.

**Review by AnonymousWalker — APPROVED** [review]

**Pull request merged**
