### PR TITLE
Jbs bugfix file lock

### PR DESCRIPTION
**Pull request by jsarabia**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/177)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/177)* status: all files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt, line 44 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/177#-MIUc7iu5NG6HxZmzceO:-MIUc7iu5NG6HxZmzceP:b78m13i) ([raw file](https://github.com/bible-translation-tools/otter/blob/aa553b12791a9b27d3deb70a3c44b93634fe5211/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt#L44)):*
> ```Kotlin
>     override fun load(file: File) {
>         reader?.let { close() }
>         reader = WavFileReader(WavFile(file)).let { reader ->
> ```

Like we practiced before, I would recommend to rename the local reader to _reader for example
___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt, line 67 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/177#-MIUbr8kDF7NviI76hc0:-MIUbr8lBw0rEumDrGH9:b5el7y9) ([raw file](https://github.com/bible-translation-tools/otter/blob/aa553b12791a9b27d3deb70a3c44b93634fe5211/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt#L67)):*
> ```Kotlin
>             begin = frameStart
>             end = frameEnd
>             this.reader = WavFileReader(WavFile(file), frameStart, frameEnd)
> ```

is this intended? I mean overwriting this.reader but then returning local reader?
___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt, line 89 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/177#-MIUcTFN416VUHjGYtgc:-MIUcTFN416VUHjGYtgd:bnyscqq) ([raw file](https://github.com/bible-translation-tools/otter/blob/aa553b12791a9b27d3deb70a3c44b93634fe5211/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt#L89)):*
> ```Kotlin
> 
>     override fun play() {
>         reader?.let { reader ->
> ```

same as above, rename local reader
___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt, line 113 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/177#-MIUcY8KC5sIesThvnGZ:-MIUcY8KC5sIesThvnG_:bnyscqq) ([raw file](https://github.com/bible-translation-tools/otter/blob/aa553b12791a9b27d3deb70a3c44b93634fe5211/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt#L113)):*
> ```Kotlin
> 
>     override fun pause() {
>         reader?.let { reader ->
> ```

same as above, rename local reader

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/177)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @mXaln)

___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt, line 44 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/177#-MIUc7iu5NG6HxZmzceO:-MI_MYVq8Q4_jvz0x3-V:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/aa553b12791a9b27d3deb70a3c44b93634fe5211/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt#L44)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Like we practiced before, I would recommend to rename the local reader to _reader for example
</blockquote></details>

Done.
___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt, line 67 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/177#-MIUbr8kDF7NviI76hc0:-MI_MTnf4WnWCZ7z3JKg:b-2jtcc1) ([raw file](https://github.com/bible-translation-tools/otter/blob/aa553b12791a9b27d3deb70a3c44b93634fe5211/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt#L67)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

is this intended? I mean overwriting this.reader but then returning local reader?
</blockquote></details>

good catch, it should have been closer to the other load function
___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt, line 89 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/177#-MIUcTFN416VUHjGYtgc:-MI_MTPD5U01hSqetc4A:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/aa553b12791a9b27d3deb70a3c44b93634fe5211/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt#L89)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

same as above, rename local reader
</blockquote></details>

Done.
___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt, line 113 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/177#-MIUcY8KC5sIesThvnGZ:-MI_MSxA1YliicZo37C2:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/aa553b12791a9b27d3deb70a3c44b93634fe5211/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt#L113)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

same as above, rename local reader
</blockquote></details>

Done.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/177)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @mXaln)

___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt, line 67 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/177#-MIUbr8kDF7NviI76hc0:-MI_Nwlv30Ft0zwIUcWS:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/aa553b12791a9b27d3deb70a3c44b93634fe5211/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioBufferPlayer.kt#L67)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

good catch, it should have been closer to the other load function
</blockquote></details>

Done.

**Review by mXaln — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/177)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
