### PR TITLE
Marker App

### PR DESCRIPTION
**Pull request by jsarabia**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)

### CODE REVIEW

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: 0 of 15 files reviewed, 11 unresolved discussions

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/AudioSlider.kt, line 21 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKViwz22KC3KYwZlYv2:-MKViwz35U2ENHD5EBQW:bnshwrn) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/AudioSlider.kt#L21)):*
> ```Kotlin
>     val thumbFillProperty = SimpleObjectProperty<Paint>(Paint.valueOf("#00000015"))
>     val thumbLineColorProperty = SimpleObjectProperty<Paint>(Color.BLACK)
>     val secondsToHighlightProperty = SimpleIntegerProperty(10)
> ```

Make this set based on viewmodel
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/LayoutUtils.kt, line 6 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVj7PI-MyQMzKPgV9V:-MKVj7PI-MyQMzKPgV9W:b5i0u5g) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/LayoutUtils.kt#L6)):*
> ```Kotlin
> import javafx.scene.layout.Region
> 
> fun ImageView.fitToParentHeight() {
> ```

Maybe rename to ImageViewUtils since this is all regarding ImageView?
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt, line 29 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVjGm369aJYI3Aa6nT:-MKVjGm369aJYI3Aa6nU:b-99acb4) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt#L29)):*
> ```Kotlin
>     init {
>         markerTrack = MarkerTrack(viewModel, viewModel.imageWidth, 50.0)
>         timecodeHolder = TimecodeHolder(viewModel, viewModel.imageWidth, 50.0, viewModel.audioPlayer.getAbsoluteDurationMs())
> ```

set height by css
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt, line 33 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVjTz59Cx2SHUO5RGz:-MKVjTz59Cx2SHUO5RH-:biig88y) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt#L33)):*
> ```Kotlin
>     }
> 
>     override val root = borderpane {
> ```

Let this be an actual class itself, and add styling to its components
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt, line 38 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVjO6w11L4ObnMI4jR:-MKVjO6w11L4ObnMI4jS:b-wueo4j) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt#L38)):*
> ```Kotlin
> 
>         val ht = Screen.getMainScreen().platformHeight
>         val wd = Screen.getMainScreen().platformWidth
> ```

move these variables out of the borderpane, they can be top level variables
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt, line 115 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVkkxVAq4PSHQNBl_r:-MKVkkxVAq4PSHQNBl_s:b-c4728p) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt#L115)):*
> ```Kotlin
>                             styleClass.add("vm-playback-line")
>                             endYProperty().bind(this@region.heightProperty())
>                         }
> ```

Create this as a class maybe since multiple places use it?
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MainWaveform.kt, line 15 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVjfZaCdXL5GNJpDZI:-MKVjfZaCdXL5GNJpDZJ:b-r28zih) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MainWaveform.kt#L15)):*
> ```Kotlin
> interface ViewPortScrollable {
>     fun scrollTo(x: Double)
> }
> ```

Move to separate file since multiple things use it
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt, line 27 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVl2-h8BcT3OtiHNtd:-MKVl2-h8BcT3OtiHNte:b-aoetx8) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt#L27)):*
> ```Kotlin
>         viewModel.markers.markerCountProperty.onChangeAndDoNow {
>             markers.clear()
>             markers.setAll(
> ```

break this into functions, also line length
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt, line 50 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVl5Vn0TcWV-u1sqwe:-MKVl5Vn0TcWV-u1sqwf:b-93wpbg) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt#L50)):*
> ```Kotlin
>                                 } else {
>                                     Paint.valueOf("#015ad933")
>                                 }
> ```

maybe these rectangles should be classes
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/Timecode.kt, line 32 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVkLj8E3zdLJ0SVw46:-MKVkLj984UDFiSeUbhS:b-1mtlsn) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/Timecode.kt#L32)):*
> ```Kotlin
>             if (i + 10 < width) {
>                 val text = msToDisplayString(positionToMs((i - 1), width, durationMs))
>                 ctx.fillText(text, i + 5.0, floor(height - 10.0))
> ```

name the 5 and 10 magic numbers
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt, line 48 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVk0r93GdGCdCx_l0o:-MKVk0r93GdGCdCx_l0p:b3g9cww) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L48)):*
> ```Kotlin
>         }
>         audioPlayer.load(audioFile)
>         imageWidth = (audioPlayer.getAudioReader()!!.sampleRate * 5 / width.toDouble()) * (audioPlayer.getAbsoluteDurationMs() / 1000.0)
> ```

let this be based on a secondsonscreen variable

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: 0 of 15 files reviewed, 10 unresolved discussions

___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/LayoutUtils.kt, line 6 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVj7PI-MyQMzKPgV9V:-MK_2Q6W-XyhOHhoer6k:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/LayoutUtils.kt#L6)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Maybe rename to ImageViewUtils since this is all regarding ImageView?
</blockquote></details>

Done.

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: all files reviewed, 13 unresolved discussions (waiting on @jsarabia)

___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt, line 115 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVkkxVAq4PSHQNBl_r:-MK_IRgg6y3LwVEkHYZd:bqewkut) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt#L115)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Create this as a class maybe since multiple places use it?
</blockquote></details>

sounds reasonable
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt, line 50 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVl5Vn0TcWV-u1sqwe:-MK_MdAo118NS5DkJT3X:b-8fx2u7) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt#L50)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

maybe these rectangles should be classes
</blockquote></details>

:+1: 
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt, line 47 at r3](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MK_NvLE6lY1NHH9Is5A:-MK_NvLE6lY1NHH9Is5B:b58n0tz) ([raw file](https://github.com/bible-translation-tools/otter/blob/322d08d2c4d26b4d3b99f285cf6a41e47af598ab/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt#L47)):*
> ```Kotlin
>                                 xProperty().set(viewModel.audioPlayer.getAbsoluteDurationInFrames() - cue.location / scale.toDouble())
>                                 fill = if (index % 2 == 0) {
>                                     Paint.valueOf("#1edd7633")
> ```

Maybe move all the color occurrences to AppTheme, or, since we try to avoid using AppTheme, to root.css?
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/Timecode.kt, line 32 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVkLj8E3zdLJ0SVw46:-MK_KoQ0Cr0Vsfe32C0o:b-8fx2u7) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/Timecode.kt#L32)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

name the 5 and 10 magic numbers
</blockquote></details>

:+1: 
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt, line 48 at r3](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MK_NIfT9rrO4intsrdk:-MK_NIfT9rrO4intsrdl:bbytmq5) ([raw file](https://github.com/bible-translation-tools/otter/blob/322d08d2c4d26b4d3b99f285cf6a41e47af598ab/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L48)):*
> ```Kotlin
>         }
>         audioPlayer.load(audioFile)
>         imageWidth = (audioPlayer.getAudioReader()!!.sampleRate * 5 / width.toDouble()) * (audioPlayer.getAbsoluteDurationMs() / 1000.0)
> ```

Line length
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt, line 82 at r3](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MK_NQnV4BkwX01YB2aX:-MK_NQnV4BkwX01YB2aY:b-fm6kyb) ([raw file](https://github.com/bible-translation-tools/otter/blob/322d08d2c4d26b4d3b99f285cf6a41e47af598ab/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L82)):*
> ```Kotlin
>         val pos =
>             (audioPlayer.getAbsoluteLocationInFrames() / audioPlayer.getAbsoluteDurationInFrames().toDouble()) * imageWidth
>         positionProperty.set(pos)
> ```

line length

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: 9 of 15 files reviewed, 12 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt, line 48 at r3](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MK_NIfT9rrO4intsrdk:-MKa_6qe2e6km8W7bO2i:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/322d08d2c4d26b4d3b99f285cf6a41e47af598ab/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L48)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Line length
</blockquote></details>

Done.
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt, line 82 at r3](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MK_NQnV4BkwX01YB2aX:-MKa_4w28lDH4IlHFiNH:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/322d08d2c4d26b4d3b99f285cf6a41e47af598ab/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L82)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: all files reviewed, 12 unresolved discussions (waiting on @jsarabia)

___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt, line 49 at r5](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKdAyvq3sYiB3urvfmN:-MKdAyvq3sYiB3urvfmO:b3hx8kj) ([raw file](https://github.com/bible-translation-tools/otter/blob/bbad93eaaa0ae66752013694328813df9ce55caf/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L49)):*
> ```Kotlin
>         audioPlayer.load(audioFile)
>         imageWidth =
>             (audioPlayer.getAudioReader()!!.sampleRate * 5 / width.toDouble()) *
> ```

Maybe split this long expression into variables and also define magic numbers?
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt, line 82 at r5](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKdBEOmCfmBKwYa_Vcn:-MKdBEOmCfmBKwYa_Vco:b-ya81ng) ([raw file](https://github.com/bible-translation-tools/otter/blob/bbad93eaaa0ae66752013694328813df9ce55caf/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L82)):*
> ```Kotlin
> 
>     fun calculatePosition() {
>         val pos =
> ```

Same as above

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: 14 of 16 files reviewed, 11 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt, line 49 at r5](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKdAyvq3sYiB3urvfmN:-MKe8tMvCSq_1lhil9cW:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/bbad93eaaa0ae66752013694328813df9ce55caf/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L49)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Maybe split this long expression into variables and also define magic numbers?
</blockquote></details>

Done.
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt, line 82 at r5](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKdBEOmCfmBKwYa_Vcn:-MKe8rMb95Bzcwg6e-k-:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/bbad93eaaa0ae66752013694328813df9ce55caf/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/viewmodel/VerseMarkerViewModel.kt#L82)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

**Review by mXaln — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: all files reviewed, 9 unresolved discussions (waiting on @jsarabia)

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: 6 of 38 files reviewed, 3 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt, line 29 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVjGm369aJYI3Aa6nT:-MKjMvGe6ofG9bpQK10B:b-1p7wgj) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt#L29)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

set height by css
</blockquote></details>

Can't fix
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt, line 115 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MKVkkxVAq4PSHQNBl_r:-MKjN2AV8xKYV15L_QAo:b-ioy1dw) ([raw file](https://github.com/bible-translation-tools/otter/blob/434b0a281c4468e774bfdeb5254cb2bcb5274723/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/WaveformContainer.kt#L115)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

sounds reasonable
</blockquote></details>

I realized since this is bound to the region, not the parent, making a class here won't save much code...

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: 6 of 38 files reviewed, 2 unresolved discussions (waiting on @mXaln)

___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt, line 47 at r3](https://reviewable.io/reviews/bible-translation-tools/otter/197#-MK_NvLE6lY1NHH9Is5A:-MKjdTXmEdNW73nj-U4m:bg14tt4) ([raw file](https://github.com/bible-translation-tools/otter/blob/322d08d2c4d26b4d3b99f285cf6a41e47af598ab/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrack.kt#L47)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Maybe move all the color occurrences to AppTheme, or, since we try to avoid using AppTheme, to root.css?
</blockquote></details>

Per our conversation, we're going to hold off until we spike on CSS for the new UI

**Review by mXaln — APPROVED** [review]
> Reviewed 33 of 33 files at r7.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/197)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
