### PR TITLE
Using temp pcm and json files to store narration progress

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/recorder/WavFileWriter.kt` line 31 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZS8jNz1vjoJs7ihg8x:-NZS8jNz1vjoJs7ihg8y:bfowbbd) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/common/src/main/kotlin/org/wycliffeassociates/otter/common/recorder/WavFileWriter.kt#L31)):*
> ```Kotlin
>     private val audioFile: AudioFile,
>     private val audioStream: Observable<ByteArray>,
>     private val append: Boolean,
> ```

this should have a default of false, so that it doesn't change usage elsewhere
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 156 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSEtpNBiUjkZDH_K71:-NZSEtpNBiUjkZDH_K72:b-k9urf6) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L156)):*
> ```Kotlin
> 
>     private val narrationHistory = NarrationHistory()
>     private lateinit var pcmFile: File
> ```

chapterPcmFile
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 157 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSB1_60mNhdozrBn-2:-NZSB1_60mNhdozrBn-3:bte047u) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L157)):*
> ```Kotlin
>     private val narrationHistory = NarrationHistory()
>     private lateinit var pcmFile: File
>     private lateinit var jsonFile: File
> ```

jsonFile of what? Langnames.json?

(....I know that this is to serialize the NarrationHistory. But the code doesn't make that obvious. A name like "savedHistoryFile" or something would be better.

Also, this file should be internal to the NarrationHistory class itself; furthermore, this is a common pattern/problem, which perhaps would best solved by having NarrationHistory implement the Serializable interface or using kotlin serialization: https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-serializable/ 

At the very least, it should probably be in save/restore methods of the narration history, and this isn't the job of a viewmodel
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 175 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSEARM4bXU2FmFe0HS:-NZSEARM4bXU2FmFe0HT:b-k0kbtv) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L175)):*
> ```Kotlin
>         subscribe<NarrationFooterDockedEvent> {
>             FX.eventbus.fire(InitialSelectedVerseChangedEvent(recordedVerses.size))
>         }
> ```

This feels really clunky. Our subscriptions should also probably not be based around things getting "docked" or not, especially because- what if something is docked before this has a chance to subscribe?

It would be better to be more direct. This feels like it should be a property about verse sizes or something, that exists in a NarrationViewModel that is more central and perhaps even injected into the subviews. Or, maybe the NarrationHistory shouldn't be stored here either anyway (it can't be, it's going to be needed by the waveform stuff later on anyway)
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 217 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSAvqgC_P_PQ_yAYx3:-NZSAvqgC_P_PQ_yAYx4:b47ax2n) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L217)):*
> ```Kotlin
>             narrationHistory.execute(action)
>             updateHistoryAvailable()
>             updateJsonFile()
> ```

When these two functions are called in tandem so much, perhaps it should be one function call, or a function that then calls both
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 324 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSA_6O5xj7-A6_2JTm:-NZSA_6O5xj7-A6_2JTn:b38acqe) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L324)):*
> ```Kotlin
>         }
> 
>         updateJsonFile()
> ```

every time updateJsonFile is called, it is preceded by a call to updateHistoryAvailable()

Given that this is the sole time that the preceding call is omitted, it looks like a bug. If it is intentionally omitted, please leave a comment to say so, lest the method call get added in by someone who assumed the omission was in error.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/recorder/WavFileWriter.kt` line 31 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZS8jNz1vjoJs7ihg8x:-NZfIbML-r66xPT7Zq1H:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/common/src/main/kotlin/org/wycliffeassociates/otter/common/recorder/WavFileWriter.kt#L31)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this should have a default of false, so that it doesn't change usage elsewhere
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 156 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSEtpNBiUjkZDH_K71:-NZfIliME9dX9tzGvhB-:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L156)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

chapterPcmFile
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 157 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSB1_60mNhdozrBn-2:-NZfInT31zkcijjOrEw-:bfli9tx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L157)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

jsonFile of what? Langnames.json?

(....I know that this is to serialize the NarrationHistory. But the code doesn't make that obvious. A name like "savedHistoryFile" or something would be better.

Also, this file should be internal to the NarrationHistory class itself; furthermore, this is a common pattern/problem, which perhaps would best solved by having NarrationHistory implement the Serializable interface or using kotlin serialization: https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-serializable/ 

At the very least, it should probably be in save/restore methods of the narration history, and this isn't the job of a viewmodel
</blockquote></details>

Moved to NarrationHistory
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 175 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSEARM4bXU2FmFe0HS:-NZfIqxA5bvAcbk7NiIL:b-t01i4n) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L175)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This feels really clunky. Our subscriptions should also probably not be based around things getting "docked" or not, especially because- what if something is docked before this has a chance to subscribe?

It would be better to be more direct. This feels like it should be a property about verse sizes or something, that exists in a NarrationViewModel that is more central and perhaps even injected into the subviews. Or, maybe the NarrationHistory shouldn't be stored here either anyway (it can't be, it's going to be needed by the waveform stuff later on anyway)
</blockquote></details>

Refactored to use property
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 217 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSAvqgC_P_PQ_yAYx3:-NZfIxGr6wuunAEzjnBo:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L217)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

When these two functions are called in tandem so much, perhaps it should be one function call, or a function that then calls both
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 324 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZSA_6O5xj7-A6_2JTm:-NZfJ3JP9DWnzkvqG_cn:bvfuahx) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/0d83dea74720b73d64fa92b4dddbb29bf1aaaafc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L324)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

every time updateJsonFile is called, it is preceded by a call to updateHistoryAvailable()

Given that this is the sole time that the preceding call is omitted, it looks like a bug. If it is intentionally omitted, please leave a comment to say so, lest the method call get added in by someone who assumed the omission was in error.
</blockquote></details>

Because pauseRecording is not an action, I didn't need to update redo/undo history. But apparently updating history will not hurt here, because it just checks if there are new undo/redo items.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt` line 53 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZlVKO21OzZdGlVRjOP:-NZlVKO21OzZdGlVRjOQ:bvi2b6i) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/574493bb24a7baeaa7a61d0d9670a2d52dbaa501/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt#L53)):*
> ```Kotlin
>     }
> 
>     fun initSavedHistoryFile(parentDir: File) {
> ```

what is the parent dir?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt` line 54 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZlPmbK1pY-VMBevtMR:-NZlPmbK1pY-VMBevtMS:b-bi3krf) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/574493bb24a7baeaa7a61d0d9670a2d52dbaa501/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt#L54)):*
> ```Kotlin
> 
>     fun initSavedHistoryFile(parentDir: File) {
>         saveHistoryFile = File(parentDir, "narration.json")
> ```

file name should be a declared constant
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt` line 57 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZlYY3w-t78yWOvAtnp:-NZlYY3w-t78yWOvAtnq:b-5jg4xv) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/574493bb24a7baeaa7a61d0d9670a2d52dbaa501/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt#L57)):*
> ```Kotlin
>     }
> 
>     fun updateSavedHistoryFile(verses: List<VerseNode>) {
> ```

the history should be serializing itself, not data coming in from some other place, since the history is THE source of truth of current verses.

Let's actually meet and talk about this more, it would probably be better to have a conversation than just code feedback.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt` line 53 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZlVKO21OzZdGlVRjOP:-NZz5LO8-vM_xzFlq0fW:b-s62i6s) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/574493bb24a7baeaa7a61d0d9670a2d52dbaa501/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt#L53)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

what is the parent dir?
</blockquote></details>

changed to chapterDir. It's a directory where the chapter file is along with the temp progress files
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt` line 54 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-NZlPmbK1pY-VMBevtMR:-NZz5VhR1Zb07Z30LoeT:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/574493bb24a7baeaa7a61d0d9670a2d52dbaa501/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt#L54)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

file name should be a declared constant
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/762#-:-N_3uqEe9yH_vlmsO8T0:bnfp4nl)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @mXaln)

**Pull request merged**
