### PR TITLE
Narration logging

### PR DESCRIPTION
**Pull request by darrellcolehill**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905)

### CODE REVIEW

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 500 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905#-NkMN6CK7TmURwyq0N9n:-NkMN6CK7TmURwyq0N9o:b-5nocen) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f8e8b8c7738bb854d0195cf21c260c50b56b7e6e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L500)):*
> ```Kotlin
>         val seekLoc = activeVerses.lastOrNull() { it.location < loc }
>         seekLoc?.let {
>             logger.info("Seeking to previous: ${it.formattedLabel}")
> ```

For actions involving a verse marker, I am logging it's formattedLabel. The idea behind this was to keep the log output from getting to cluttered, however, it may be more helpful to just log out the entire verseNode object to give a better description of the state of the application.

**Review by darrellcolehill — COMMENTED** [review]
Not sure if the logging statements are what is expected. If they are, how far outside of the Narration page should I add logging?

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905#-:-NkQbEVT7l1vAmRPEYR9:b-53fxd9)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @darrellcolehill)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 116 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905#-NkQqrIX8Fh34OHAD0s4:-NkQqrIX8Fh34OHAD0s5:b-h6as2g) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f8e8b8c7738bb854d0195cf21c260c50b56b7e6e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L116)):*
> ```Kotlin
>         try {
>             val nodes = activeVersesMapper.readValue(json, reference)
>             logger.info("Loading ${nodes.size} audio markers from serialized data")
> ```

this is what this is doing, yes, but conceptually, what is this?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 503 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905#-NkQr7YjCFvC3dz07Buy:-NkQr7YjCFvC3dz07Buz:b-h7iys2) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f8e8b8c7738bb854d0195cf21c260c50b56b7e6e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L503)):*
> ```Kotlin
>             seek(it.location)
>         } ?: {
>             logger.info("Seeking to previous: previous marker not found")
> ```

might want to say "Previous marker not found, seeking to 0" or something like that
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 517 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905#-NkQrIAeE763NtQGRISA:-NkQrIAeE763NtQGRISB:b32owet) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f8e8b8c7738bb854d0195cf21c260c50b56b7e6e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L517)):*
> ```Kotlin
>             seek(it.location)
>         } ?: chapterRepresentation.apply {
>             logger.info("Seeking to next: next marker not found")
> ```

might want to indicate seeking to the end of the file

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 116 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905#-NkQqrIX8Fh34OHAD0s4:-NkReEh5DdipmgSTl3ys:b-dwfw2x) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f8e8b8c7738bb854d0195cf21c260c50b56b7e6e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L116)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this is what this is doing, yes, but conceptually, what is this?
</blockquote></details>

The goal is to communicate how many verses/titles where previously recorded and are being loaded in. 

I wanted a clear way to know if there is the first time they are recording something for this chapter, or if they are revisiting this chapter, and if they are revisiting this chapter, how many sections of audio did they record. That way we have context for the subsequent logging statements.

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 503 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905#-NkQr7YjCFvC3dz07Buy:-NkRfP3K1uDEkw5Fb0v7:b-7rl0kd) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f8e8b8c7738bb854d0195cf21c260c50b56b7e6e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L503)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

might want to say "Previous marker not found, seeking to 0" or something like that
</blockquote></details>

done
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 517 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905#-NkQrIAeE763NtQGRISA:-NkRf_pfBn6K2fhgrZ5L:bb7f2mf) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f8e8b8c7738bb854d0195cf21c260c50b56b7e6e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L517)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

might want to indicate seeking to the end of the file
</blockquote></details>

done

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/905#-:-Nkzla1Z9G8YOGTYg7MP:bnfp4nl)* status: 0 of 8 files reviewed, 2 unresolved discussions

**Pull request merged**
