### PR TITLE
Project Export Dialog

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/765)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/765)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/tableview/ExportProjectTableView.kt` line 24 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/765#-NYxNSMh7W1hmt1uSh79:-NYxNSMh7W1hmt1uSh7A:b-jggr7t) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e484d8c76e1ff1a85fd82652802841f9eb2809d3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/tableview/ExportProjectTableView.kt#L24)):*
> ```Kotlin
> ) : TableView<ChapterSummary>(chapters) {
> 
>     private val isSelectAllProperty = SimpleBooleanProperty(true).apply {
> ```

Can this be simplified?



_Code snippet:_
```Kotlin
private val isSelectedAllProperty = booleanBinding(selectedChapters) { selectedChapters.size == chapters.size }
```

**Comment by AnonymousWalker** [comment]
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/tableview/ExportProjectTableView.kt` line 24 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/765#-NYxNSMh7W1hmt1uSh79:-NYxaXTV0iUeAMK76Cdp:b-l5nt5g) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/e484d8c76e1ff1a85fd82652802841f9eb2809d3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/tableview/ExportProjectTableView.kt#L24)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Can this be simplified?
</blockquote></details>

that's a great suggestion! Thank you

**Review by mXaln — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/765)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 2 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/765)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ChapterSummary.kt` line 3 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/765#-NYy6nZw4OXX_vkw5wGE:-NYy6nZw4OXX_vkw5wGF:b-ujey7d) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/82db2ff44ce5ffaeca10c2e6a51332bc31f834ca/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ChapterSummary.kt#L3)):*
> ```Kotlin
> package org.wycliffeassociates.otter.common.data.workbook
> 
> data class ChapterSummary(val number: Int, val progress: Double)
> ```

Why is this a ChapterSummary and not ChapterProgress?

Why is this data within the workbook package, and not just a field within a Chapter?

Or could this be part of the WorkbookDescriptor?

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/765#-:-NYyHbhDBcwuDU3uvBA9:bnfp4nl)* status: 17 of 22 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @mXaln)

**Pull request merged**
