### PR TITLE
Allow to open chapter file in an external app / marker app

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 35 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764#-NZSGa5M69oXNqiAuCwr:-NZSGa5M69oXNqiAuCws:bugraw7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f5dc5ee746bbb59b2f68afbbfdbe8f34205357f3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L35)):*
> ```Kotlin
> 
>     init {
>         subscribe<NarrationOpenInPluginEvent> {
> ```

there should only be one subscription here. The event should contain a plugin type, and provide it to the processWithPlugin function so that there is only one openInPlugin related event, and it should be able to handle all plugin types.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 39 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764#-NZSGtnv5ThQUJfpMp-t:-NZSGtnw13s7YBXfW4-I:b-7vn0u3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f5dc5ee746bbb59b2f68afbbfdbe8f34205357f3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L39)):*
> ```Kotlin
>         }
> 
>         subscribe<NarrationEditVerseMarkersEvent> {
> ```

Aside from what was mentioned above, this is a very confusing event name because it contains both the words Edit and Markers, both of which are plugin types. It's easy to read NarrationEdit... and stop there and assume that this is the edit plugin event.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 35 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764#-NZSGa5M69oXNqiAuCwr:-NZfQdeR4L7tYEU9eZBk:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f5dc5ee746bbb59b2f68afbbfdbe8f34205357f3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L35)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

there should only be one subscription here. The event should contain a plugin type, and provide it to the processWithPlugin function so that there is only one openInPlugin related event, and it should be able to handle all plugin types.
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 39 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764#-NZSGtnv5ThQUJfpMp-t:-NZfQeCp8W1PC8JqK6zG:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f5dc5ee746bbb59b2f68afbbfdbe8f34205357f3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L39)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Aside from what was mentioned above, this is a very confusing event name because it contains both the words Edit and Markers, both of which are plugin types. It's easy to read NarrationEdit... and stop there and assume that this is the edit plugin event.
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 155 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764#-NZltHMi4Iy2kHWIRLfR:-NZltHMi4Iy2kHWIRLfS:bpc6v1j) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c2b9c6facb591429b6e7671916290468d91321b1/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L155)):*
> ```Kotlin
> 
>     private fun loadChapter(chapter: Chapter) {
>         chapterTakeProperty.set(chapter.audio.selected.value?.value)
> ```

looks like we should have a getSelectedAudioFile method in the chapter
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationView.kt` line 58 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764#-NZltWGGEST8RIlht74K:-NZltWGGEST8RIlht74L:b35afhf) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c2b9c6facb591429b6e7671916290468d91321b1/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationView.kt#L58)):*
> ```Kotlin
>                             audioPluginViewModel.addPlugin(record = true, edit = false)
>                         },
>                         Duration.millis(5000.0),
> ```

Let's let this be a defined constant. Where might be a good place to define it? It feels like it would be useful to centralize and name the SNACKBAR_DURATION

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 155 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764#-NZltHMi4Iy2kHWIRLfR:-NZz7Aea7-UiV-sYYKCn:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c2b9c6facb591429b6e7671916290468d91321b1/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L155)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

looks like we should have a getSelectedAudioFile method in the chapter
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationView.kt` line 58 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764#-NZltWGGEST8RIlht74K:-NZzEBNuAT0gBJncouj0:b-ds7j83) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c2b9c6facb591429b6e7671916290468d91321b1/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationView.kt#L58)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Let's let this be a defined constant. Where might be a good place to define it? It feels like it would be useful to centralize and name the SNACKBAR_DURATION
</blockquote></details>

I remember that Tony worked on creating a snackbar handler that was merged into orature-2 branch. Maybe we can add this constant there later?

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/764#-:-N_3usDq-eP4vujnZm9T:bnfp4nl)* status: 0 of 6 files reviewed, 2 unresolved discussions

**Pull request merged**
