### PR TITLE
Refactor css theme colors

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/430)

### CODE REVIEW

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/430)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/controls/src/main/resources/css/chapter-card.css, line 42 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/430#-MpgUd6S6gQ0k76KSrSD:-MpgUd6S6gQ0k76KSrSE:bhdqv3r) ([raw file](https://github.com/bible-translation-tools/orature/blob/14104cf418b45aa9bd0537df5339c602118995a6/jvm/controls/src/main/resources/css/chapter-card.css#L42)):*
> ```CSS
> }
> 
> .chapter-card__title.label {
> ```

should there be a space before the "." ?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/430)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[jvm/controls/src/main/resources/css/chapter-card.css, line 42 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/430#-MpgUd6S6gQ0k76KSrSD:-Mpgv7xVEsOgvl4VHcoW:b8wax5o) ([raw file](https://github.com/bible-translation-tools/orature/blob/14104cf418b45aa9bd0537df5339c602118995a6/jvm/controls/src/main/resources/css/chapter-card.css#L42)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

should there be a space before the "." ?
</blockquote></details>

space = applies to all children while having continuous "." means having these classes (AND)

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/430)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[jvm/controls/src/main/resources/css/chapter-card.css, line 42 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/430#-MpgUd6S6gQ0k76KSrSD:-Mph-Xl94q_GyhkXiCLB:b-vblr9v) ([raw file](https://github.com/bible-translation-tools/orature/blob/14104cf418b45aa9bd0537df5339c602118995a6/jvm/controls/src/main/resources/css/chapter-card.css#L42)):*
<details><summary><i>Previously, AnonymousWalker (Tony Anh Tran) wrote…</i></summary><blockquote>

space = applies to all children while having continuous "." means having these classes (AND)
</blockquote></details>

https://www.w3schools.com/cssref/css_selectors.asp

**Review by mXaln — APPROVED** [review]
> Reviewed 28 of 29 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/430)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia)

**Pull request merged**
