### PR TITLE
Undo recording, deleting, selecting and checking

### PR DESCRIPTION
**Pull request by AnonymousWalker**
- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/chunking/Chunking.kt` line 131 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-NhlbLX11BK6LzM7I8F0:-NhlbLX11BK6LzM7I8F1:bejlx9y) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c2675391b0152033ce34a739236c6790db6a2aa6/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/chunking/Chunking.kt#L131)):*
> ```Kotlin
>         subscribe<RedoChunkingPageEvent> {
>             viewModel.redoMarker()
>         }
> ```

subscribe and unsubscribe in dock and undock- this will leak the viewmodel.

If a view is ever docked in a new scope, all previously docked views will receive and execute these events.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/chunking/PeerEdit.kt` line 60 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-NhlbYU1268DqT2ipWGh:-NhlbYU1268DqT2ipWGi:blr6zkj) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c2675391b0152033ce34a739236c6790db6a2aa6/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/chunking/PeerEdit.kt#L60)):*
> ```Kotlin
>         subscribe<RedoChunkingPageEvent> {
>             viewModel.redo()
>         }
> ```

This is especially bad because these subscribes are in a Fragment, which is not a singleton.

The viewmodel and fragment are leaked.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BlindDraftViewModel.kt` line 293 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-NhlbuLV0GVBDHRkfh0V:-NhlbuLV0GVBDHRkfh0W:b-9xvv96) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c2675391b0152033ce34a739236c6790db6a2aa6/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BlindDraftViewModel.kt#L293)):*
> ```Kotlin
>     }
> 
>     private inner class ChunkTakeRecordAction(
> ```

This needs to be moved to a model, it does not belong in a viewmodel, nor do any of the other actions present here.

**Comment by AnonymousWalker** [comment]
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/chunking/Chunking.kt` line 131 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-NhlbLX11BK6LzM7I8F0:-NhmMJBeC9xcgmbjpH35:b-ck0ur7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c2675391b0152033ce34a739236c6790db6a2aa6/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/chunking/Chunking.kt#L131)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

subscribe and unsubscribe in dock and undock- this will leak the viewmodel.

If a view is ever docked in a new scope, all previously docked views will receive and execute these events.
</blockquote></details>

I believe the view/fragment will execute the events only when it's docked

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BlindDraftViewModel.kt` line 293 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-NhlbuLV0GVBDHRkfh0V:-NhmNG1R-EV3LwolVv-x:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c2675391b0152033ce34a739236c6790db6a2aa6/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BlindDraftViewModel.kt#L293)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This needs to be moved to a model, it does not belong in a viewmodel, nor do any of the other actions present here.
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/BlindDraftActions.kt` line 8 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-Ni-YAnQ7GYilIpQx704:-Ni-YAnQ7GYilIpQx705:bpdl5vu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1d455f87749ec53708f532635aa0d68ed4d007b1/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/BlindDraftActions.kt#L8)):*
> ```Kotlin
> import org.wycliffeassociates.otter.common.domain.IUndoable
> 
> abstract class ChunkTakeAction(
> ```

Can we replace ChunkTake with BlindDraft for every class name here, in order to be consistent with the file name?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/BlindDraftActions.kt` line 10 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-Ni-YNHlArpV4muuvxoK:-Ni-YNHlArpV4muuvxoL:b-lwch62) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1d455f87749ec53708f532635aa0d68ed4d007b1/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/BlindDraftActions.kt#L10)):*
> ```Kotlin
> abstract class ChunkTakeAction(
>     protected val take: Take,
>     protected val chunk: Chunk
> ```

It feels more reasonable to go Chunk, Take rather than the reverse order, because Chunk is a higher level unit and the take is with the context of the Chunk. 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/ChunkConfirmAction.kt` line 8 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-Ni-YojW85270Y-2oK_P:-Ni-YojW85270Y-2oK_Q:b84qhkh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1d455f87749ec53708f532635aa0d68ed4d007b1/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/ChunkConfirmAction.kt#L8)):*
> ```Kotlin
> import org.wycliffeassociates.otter.common.domain.IUndoable
> 
> class ChunkConfirmAction(
> ```

What does this confirm?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/BlindDraftActions.kt` line 8 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-Ni-YAnQ7GYilIpQx704:-Ni-cFYD8G62hfyV7Eph:b-4rmoh7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1d455f87749ec53708f532635aa0d68ed4d007b1/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/BlindDraftActions.kt#L8)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Can we replace ChunkTake with BlindDraft for every class name here, in order to be consistent with the file name?
</blockquote></details>

I renamed the file instead, since it's beyond the scope of BlindDraft
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/BlindDraftActions.kt` line 10 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-Ni-YNHlArpV4muuvxoK:-Ni-cQRu-glg70y-AJUz:bq0ncok) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1d455f87749ec53708f532635aa0d68ed4d007b1/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/BlindDraftActions.kt#L10)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

It feels more reasonable to go Chunk, Take rather than the reverse order, because Chunk is a higher level unit and the take is with the context of the Chunk.
</blockquote></details>

sounds good
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/ChunkConfirmAction.kt` line 8 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-Ni-YojW85270Y-2oK_P:-Ni-d3pXCTS5_tzvBAV-:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1d455f87749ec53708f532635aa0d68ed4d007b1/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/chunking/ChunkConfirmAction.kt#L8)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

What does this confirm?
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/859#-:-Ni_Qipq8huUAPYZZMLq:bnfp4nl)* status: 0 of 15 files reviewed, all discussions resolved

**Pull request merged**
