### PR TITLE
Source text zoom

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Allows changing font size of source text. The zoom ratio should be consistent among different places including: ` PluginOpenedPage, RecordScripturePage and MarkerView - SourceTextFragment `

This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/558)

image

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
When I change zoom rate on RecordScripturePage, the change is not applied in the PluginOpenedPage.

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/558#-:-N-bA0xf2U1kNgek9SKD:b-dtw25l)* status: all files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/PluginOpenedPage.kt, line 98 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/558#-N-b3uDM5MuJjuPBrexa:-N-b3uDM5MuJjuPBrexb:bzcidgb) ([raw file](https://github.com/bible-translation-tools/orature/blob/09123cf2789d3a489c0b22807f5063c032f1865f/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/PluginOpenedPage.kt#L98)):*
> ```Kotlin
>                 sourceSpeedRateProperty.bind(this@PluginOpenedPage.sourceSpeedRateProperty)
>                 targetSpeedRateProperty.bind(this@PluginOpenedPage.targetSpeedRateProperty)
>                 this@PluginOpenedPage.sourceTextZoomRateProperty.onChange {
> ```

Could you clean this change listener in onUndock?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ChapterPage.kt, line 136 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/558#-N-b8YDI4pbFqV2m_WXH:-N-b8YDI4pbFqV2m_WXI:b-3axm25) ([raw file](https://github.com/bible-translation-tools/orature/blob/09123cf2789d3a489c0b22807f5063c032f1865f/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ChapterPage.kt#L136)):*
> ```Kotlin
>             (workspace.dockedComponentProperty.value as? PluginOpenedPage)?.let {
>                 workspace.navigateBack()
>                 pluginOpenedPage.onUndock()
> ```

Since you are using View instead of Fragment and docking PluginOpenedPage with find method, there is no need to manually dock and undock it. Because it will run twice. Like you have removed pluginOpenedPage.onDock() above, this also should be removed.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordScripturePage.kt, line 186 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/558#-N-b9Y7I6O0sXxGD8ATF:-N-b9Y7I6O0sXxGD8ATG:b-vc4zp2) ([raw file](https://github.com/bible-translation-tools/orature/blob/09123cf2789d3a489c0b22807f5063c032f1865f/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordScripturePage.kt#L186)):*
> ```Kotlin
>             if (!pluginInfo.isNative) {
>                 workspace.dock(pluginOpenedPage)
>                 pluginOpenedPage.onDock()
> ```

pluginOpenedPage.onDock() and pluginOpenedPage.onUndock() should be also removed here, if pluginOpenedPage is a View.



_Code quote:_
```Kotlin
pluginOpenedPage.onDock()
```

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/558)* status: all files reviewed, 3 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/PluginOpenedPage.kt, line 98 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/558#-N-b3uDM5MuJjuPBrexa:-N-cQcOg5VxLtuIZDoBM:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/09123cf2789d3a489c0b22807f5063c032f1865f/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/PluginOpenedPage.kt#L98)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Could you clean this change listener in onUndock?
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ChapterPage.kt, line 136 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/558#-N-b8YDI4pbFqV2m_WXH:-N-cQcy238Ry0d4ohBJr:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/09123cf2789d3a489c0b22807f5063c032f1865f/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ChapterPage.kt#L136)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Since you are using View instead of Fragment and docking PluginOpenedPage with find method, there is no need to manually dock and undock it. Because it will run twice. Like you have removed pluginOpenedPage.onDock() above, this also should be removed.
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordScripturePage.kt, line 186 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/558#-N-b9Y7I6O0sXxGD8ATF:-N-cQdln9OPDaLOYUW1L:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/09123cf2789d3a489c0b22807f5063c032f1865f/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordScripturePage.kt#L186)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

pluginOpenedPage.onDock() and pluginOpenedPage.onUndock() should be also removed here, if pluginOpenedPage is a View.
</blockquote></details>

Done.

**Review by mXaln — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/558)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Comment by OpThomasPrime1** [comment]
Verified by QA (Thomas Oliver) Windows, Linux, Apple

**Pull request merged**
