### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/613)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/613)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/plugins/LaunchPlugin.kt` line 40 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/613#-N5flhYID4MBf-65skGA:-N5flhYID4MBf-65skGB:b-5n40a7) ([raw file](https://github.com/bible-translation-tools/orature/blob/08abc010cb1bd1ab459bb62eb60ad2f3f9dd53cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/plugins/LaunchPlugin.kt#L40)):*
> ```Kotlin
> 
>     fun launchPlugin(type: PluginType, file: File, pluginParameters: PluginParameters): Single<Result> {
>         logger.info("Launching plugin: ${type.name}")
> ```

might as well log when it closes and the result too
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt` line 101 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/613#-N5fm2OF-Pb9yPCX6wKD:-N5fm2OF-Pb9yPCX6wKE:b-6der4w) ([raw file](https://github.com/bible-translation-tools/orature/blob/08abc010cb1bd1ab459bb62eb60ad2f3f9dd53cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L101)):*
> ```Kotlin
>                 importContainer(rcFile)
>             }
>             else -> Single.just(ImportResult.DEPENDENCY_ERROR)
> ```

log this?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/613)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/plugins/LaunchPlugin.kt` line 40 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/613#-N5flhYID4MBf-65skGA:-N5jdNd18Kjb9mafYt7N:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/08abc010cb1bd1ab459bb62eb60ad2f3f9dd53cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/plugins/LaunchPlugin.kt#L40)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

might as well log when it closes and the result too
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt` line 101 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/613#-N5fm2OF-Pb9yPCX6wKD:-N5jdNFvCQMHSKkNmNUC:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/08abc010cb1bd1ab459bb62eb60ad2f3f9dd53cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L101)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

log this?
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/613)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt` line 101 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/613#-N5fm2OF-Pb9yPCX6wKD:-N5odQnFC5IHJM3yq3au:bhtiq7m) ([raw file](https://github.com/bible-translation-tools/orature/blob/08abc010cb1bd1ab459bb62eb60ad2f3f9dd53cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L101)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Specifically the error is a dependency error; like importing tQ before ulb (hence the result)

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/613)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt` line 101 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/613#-N5fm2OF-Pb9yPCX6wKD:-N5oghZiE44lyDQSC8MM:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/08abc010cb1bd1ab459bb62eb60ad2f3f9dd53cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ImportResourceContainer.kt#L101)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Specifically the error is a dependency error; like importing tQ before ulb (hence the result)
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/613#-:-N5ohPKVEBKzT60esd0K:bnfp4nl)* status: 1 of 15 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
