### PR TITLE
Chapter selector grid

### PR DESCRIPTION
**Pull request by AnonymousWalker**
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793)

### CODE REVIEW

**Review by mXaln — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt` line 12 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793#-Nc2Uky7DMnS3jv7nyZk:-Nc2Uky7DMnS3jv7nyZl:b-8kvzbp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b1cb17c7747aa72cab1fc290b02cefb1b39dfbd4/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt#L12)):*
> ```Kotlin
> private const val GRID_COLUMNS = 5
> 
> class ChapterGrid(list: List<ChapterGridItemData>) : GridPane() {
> ```

Many Layouts and Controls have the content provided as properties, and content can be added or changed later and the layout responds accordingly.

Should we do that here?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt` line 12 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793#-Nc2Uky7DMnS3jv7nyZk:-Nc3Au_m5VxngZlu17SI:b-34b4eh) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b1cb17c7747aa72cab1fc290b02cefb1b39dfbd4/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt#L12)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Many Layouts and Controls have the content provided as properties, and content can be added or changed later and the layout responds accordingly.

Should we do that here?
</blockquote></details>

Sounds great! Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt` line 12 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793#-Nc2Uky7DMnS3jv7nyZk:-NcOv2an8zH4EbYNCZvP:b4tk3hi) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b1cb17c7747aa72cab1fc290b02cefb1b39dfbd4/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt#L12)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Sounds great! Done.
</blockquote></details>

You should look at how the list is set in javafx's ListView- The hard reference here gives me a little anxiety and I suspect there's a reason they do it in a slightly obtuse way in ListView

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt` line 12 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793#-Nc2Uky7DMnS3jv7nyZk:-NcZ8SGH7ml-dGSy-g6u:bsxpsej) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b1cb17c7747aa72cab1fc290b02cefb1b39dfbd4/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/chapterselector/ChapterGrid.kt#L12)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

You should look at how the list is set in javafx's ListView- The hard reference here gives me a little anxiety and I suspect there's a reason they do it in a slightly obtuse way in ListView
</blockquote></details>

maybe this way could do it

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/793#-:-Nd0CVTQEDNkVO6WwClZ:bnfp4nl)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @mXaln)

**Pull request merged**
