### PR TITLE
Prevents data loss after opening chapter in Ocenaudio (OT-842)

### PR DESCRIPTION
**Pull request by darrellcolehill**
Prevents the wav file from falling out of sync with active verses once a chapter take has been created.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050)

### CODE REVIEW

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 221 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050#-Nr7TMmB62iFSxKeQaEZ:-Nr7TMmC1bwiGuDdK1qR:b-g4je0s) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/49977a805978f364662ad17b7b41ee141f32263b/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L221)):*
> ```Kotlin
>         seek(relLoc)
> 
>         NarrationTakeModifier.modifyAudioData(
> ```

Not crazy about bouncing the audio this much when we are in a state where they have a chapter take created, but not all markers placed. 

If we always want to keep the wav file up to date with active verses, then this is correct, if not, then this seems a bit over-kill. 

If we do not care about keeping the wav file up to date when we are in a state where a take exists, but not all markers are placed, then we could just bounce the audio before they open the chapter in Ocenaudio.

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 307 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050#-Nrb79w3DoOToNSSHVv5:-Nrb79w3DoOToNSSHVv6:b-n7dy5x) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9f288d14ca5e68516c74273271a6f0724e755a46/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L307)):*
> ```Kotlin
>         val hasAllVersesRecorded = newVerses.any { !it.placed }.not()
> 
>         if (hasAllVersesRecorded) {
> ```

Only bounces the audio when all verses are recorded (i.e. a temporary take was not used to perform the edit chapter action) 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 460 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050#-Nrb7iZrCEpMpqiS-yjy:-Nrb7iZrCEpMpqiS-yjz:b-85lcbg) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9f288d14ca5e68516c74273271a6f0724e755a46/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L460)):*
> ```Kotlin
> 
> 
>         for (i in segments.size until chapterRepresentation.totalVerses.size) {
> ```

Accounts for the fact that now createVersesFromVerseSegments can be called without all verse markers being contained within "segments" 

Prevents us from later on, overwriting totalVerses with a list that does not contain all verses/markers. 
 
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt` line 464 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050#-Nrb8Y-f26tPSE_xZNY1:-Nrb8Y-f26tPSE_xZNY2:bre18r0) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9f288d14ca5e68516c74273271a6f0724e755a46/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/Narration.kt#L464)):*
> ```Kotlin
>         }
> 
>         return nodes
> ```

Returns nodes instead of directly calling onChapterEdit(nodes). 

Calling onChapterEdit here seems like it could be an unexpected side-effect of createVersesFromVerseSegments.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 354 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050#-Nrb9_i7CCcvt7W23JbS:-Nrb9_i7CCcvt7W23JbT:b-e6878x) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9f288d14ca5e68516c74273271a6f0724e755a46/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L354)):*
> ```Kotlin
> 
>     private fun createPotentiallyFinishedChapterTake() {
>         if (potentiallyFinished && (chapterTakeProperty.value == null || chapterTakeProperty.value.isDeleted())) {
> ```

I really don't like this if statement, however, I am unsure how to add this check directly into potentiallyFinished. 

The goal of this if-statement is to check if I am potentially finished (all verses/markers are recorded and I am not currently in a recording or recording paused state) and verify that a chapter take does not already exists.

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 394 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050#-NrbBc2f9vsTP7r8pK_H:-NrbBc2g28EnWUv7rdzG:bkcda1q) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/9f288d14ca5e68516c74273271a6f0724e755a46/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L394)):*
> ```Kotlin
>     }
> 
>     private fun openTakeInPlugin(pluginType: PluginType, take: Take) {
> ```

This is pretty much the same method that was originally in NarrationHeader.  I moved it here so I could directly specify what take to load in and decouple it from the chapterTakeProperty.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1050#-:-NremDo29NidNkyhPwbR:bnfp4nl)* status: 0 of 5 files reviewed, 5 unresolved discussions

**Pull request merged**
