### PR TITLE
Project wizard - group by resources

### PR DESCRIPTION
**Pull request by AnonymousWalker**
image

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/618)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/618)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/skins/cards/BookCardSkin.kt` line 122 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/618#-N6DkPCG5siQsfylX4Ct:-N6DkPCG5siQsfylX4Cu:b-v0j9da) ([raw file](https://github.com/bible-translation-tools/orature/blob/4df2b3999496e55f88d6f4afd9f17670b2b46e61/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/skins/cards/BookCardSkin.kt#L122)):*
> ```Kotlin
>             textProperty().bind(card.slugProperty)
>         }
>         separatorIcon.apply { graphic = FontIcon(MaterialDesign.MDI_CHECKBOX_BLANK_CIRCLE) }
> ```

I don't think that we need a separate property for the separator icon. It's not a dynamic value. You could set it in FXML file statically.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/618)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/skins/cards/BookCardSkin.kt` line 122 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/618#-N6DkPCG5siQsfylX4Ct:-N6DncLt5NdlNPAEQrJq:b-q1fz0m) ([raw file](https://github.com/bible-translation-tools/orature/blob/4df2b3999496e55f88d6f4afd9f17670b2b46e61/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/skins/cards/BookCardSkin.kt#L122)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I don't think that we need a separate property for the separator icon. It's not a dynamic value. You could set it in FXML file statically.
</blockquote></details>

thanks for the catch, that helps me a lot

**Review by mXaln — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/618)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/618)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage.kt` line 116 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/618#-N6IXQv63RYCxhVAJaWx:-N6IXQv63RYCxhVAJaWy:b-aosh0a) ([raw file](https://github.com/bible-translation-tools/orature/blob/28223a0bbe48d4b174e0bb26ce79169bc473f30a/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage.kt#L116)):*
> ```Kotlin
>                                     slugProperty.set(workbook.target.slug.uppercase())
>                                     subtitleProperty.set(
>                                         workbook.source.resourceMetadata?.identifier.uppercase()
> ```

this should be a method on the workbook; rather than make view stuff dig into the workbook data

something like: sourceResourceSlug() or something
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt` line 205 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/618#-N6IXqLZ7c-0JgKiu65V:-N6IXqLZ7c-0JgKiu65W:b-xneqi) ([raw file](https://github.com/bible-translation-tools/orature/blob/28223a0bbe48d4b174e0bb26ce79169bc473f30a/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt#L205)):*
> ```Kotlin
>                     existing.target.slug == it.collection.slug &&
>                             (existing.source.resourceMetadata?.identifier ==
>                                             it.collection.resourceContainer?.identifier)
> ```

can this long chain be a function? especially since it's used above as well?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/618)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage.kt` line 116 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/618#-N6IXQv63RYCxhVAJaWx:-N6IZSG_4DcRmLUZnGlv:b-34b4eu) ([raw file](https://github.com/bible-translation-tools/orature/blob/28223a0bbe48d4b174e0bb26ce79169bc473f30a/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage.kt#L116)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this should be a method on the workbook; rather than make view stuff dig into the workbook data

something like: sourceResourceSlug() or something
</blockquote></details>

Sounds great! Done!
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt` line 205 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/618#-N6IXqLZ7c-0JgKiu65V:-N6Ib09HArejT0TMLDVo:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/28223a0bbe48d4b174e0bb26ce79169bc473f30a/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt#L205)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can this long chain be a function? especially since it's used above as well?
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/618#-:-N6IfpVs1sL4iJAgYklG:bnfp4nl)* status: 6 of 11 files reviewed, all discussions resolved (waiting on @jsarabia and @mXaln)

**Pull request merged**
