### PR TITLE
Import Export Translation

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Export and Import will now persist the chunks and their checking states.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/TakeCheckingStatusMap.kt` line 5 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-Nij2vFdDoYvF9XfeWLo:-Nij2vFdDoYvF9XfeWLp:b-xks8sm) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1f4aac300a4130f5c77bece7a6ff46cd35d0f6cb/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/TakeCheckingStatusMap.kt#L5)):*
> ```Kotlin
> import org.wycliffeassociates.otter.common.data.workbook.TakeCheckingState
> 
> typealias TakeCheckingStatusMap = Map<String, TakeCheckingState>
> ```

Can you comment what the String is?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt` line 438 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-Nij38ic8Kyh6NrWig2u:-Nij38ic8Kyh6NrWig2v:bfsgb88) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1f4aac300a4130f5c77bece7a6ff46cd35d0f6cb/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt#L438)):*
> ```Kotlin
>         } else {
>             mapOf()
>         }
> ```

can this be a function?
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 346 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-Nij3Ing9mhmCP_4YOZP:-Nij3Ing9mhmCP_4YOZQ:bk8ti8g) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1f4aac300a4130f5c77bece7a6ff46cd35d0f6cb/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L346)):*
> ```Kotlin
> 
>                     mapper.writeValue(writer, takeCheckingMap)
>                 }
> ```

can the block within doOnSuccess be a function?
___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/ResourceContainerBuilder.kt` line 165 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-Nij3PAR3_7Pcq77Fvx1:-Nij3PAR3_7Pcq77Fvx2:brk5kqt) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1f4aac300a4130f5c77bece7a6ff46cd35d0f6cb/common/src/test/kotlin/org/wycliffeassociates/otter/common/ResourceContainerBuilder.kt#L165)):*
> ```Kotlin
>                             .setSerializationInclusion(JsonInclude.Include.NON_NULL)
> 
>                         mapper.writeValue(stream, takeCheckingMap)
> ```

same as above, can this be a function?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/TakeCheckingStatusMap.kt` line 5 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-Nij2vFdDoYvF9XfeWLo:-NikqJdA-gmSo1nOANcw:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1f4aac300a4130f5c77bece7a6ff46cd35d0f6cb/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/TakeCheckingStatusMap.kt#L5)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Can you comment what the String is?
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt` line 438 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-Nij38ic8Kyh6NrWig2u:-NikqJuGEqWw_Vv_20va:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1f4aac300a4130f5c77bece7a6ff46cd35d0f6cb/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/project/importer/OngoingProjectImporter.kt#L438)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can this be a function?
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 346 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-Nij3Ing9mhmCP_4YOZP:-Nikqp57E5bNxsmts_qV:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1f4aac300a4130f5c77bece7a6ff46cd35d0f6cb/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L346)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can the block within doOnSuccess be a function?
</blockquote></details>

Done.
___
*[`common/src/test/kotlin/org/wycliffeassociates/otter/common/ResourceContainerBuilder.kt` line 165 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-Nij3PAR3_7Pcq77Fvx1:-NikrAUQ4MHYCO_qvrqW:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1f4aac300a4130f5c77bece7a6ff46cd35d0f6cb/common/src/test/kotlin/org/wycliffeassociates/otter/common/ResourceContainerBuilder.kt#L165)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

same as above, can this be a function?
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-:-NipKCY30puh580am1gV:bnfp4nl)* status: 0 of 17 files reviewed, all discussions resolved

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870)* status: 0 of 20 files reviewed, all discussions resolved (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 213 at r4](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/870#-Niu2BQi37jBpuiBc2QK:-Niu2BQi37jBpuiBc2QL:b-35ntxl) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/151749bcbf21270f6c3636794ee0805a0db684ca/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L213)):*
> ```Kotlin
>             }
> 
>         fileWriter.copyDirectory(sourceAudioDir, RcConstants.SOURCE_AUDIO_DIR)
> ```

preserve user-defined markers between export/import

**Pull request merged**
