### PR TITLE
Common styles for text

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Introduces the common style classes for a hierarchical collection of text, icon,... This allows consistent size/color across the app and reduces the amount of duplicated styling for most text element.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/743)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/743)* status: all files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/controls/src/main/resources/css/theme/light-theme.css` line 58 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/743#-NUS19tk0YGkzbzHXpiR:-NUS19tk0YGkzbzHXpiS:b-ys92xp) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a44104fa36fcfb7413bc26b5e4eccf93d2ea45b1/jvm/controls/src/main/resources/css/theme/light-theme.css#L58)):*
> ```CSS
> 
> /* -------------------- Components mappings --------------------*/
>     -wa-regular-text: #001533;
> ```

default regular text is dark blue color?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/tableview/WorkbookOptionTableCell.kt` line 17 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/743#-NUS1szzECxpQqg-Ta5a:-NUS1szzECxpQqg-Ta5b:by24x4g) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a44104fa36fcfb7413bc26b5e4eccf93d2ea45b1/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/tableview/WorkbookOptionTableCell.kt#L17)):*
> ```Kotlin
>         addClass("btn", "btn--icon", "btn--borderless")
>         graphic = FontIcon(MaterialDesign.MDI_DOTS_HORIZONTAL).apply {
>             addClass("icon-default-color")
> ```

I think css class should not have a property in its name. Why not just call it `icon` or `wa-icon`?

**Comment by AnonymousWalker** [comment]
*[`jvm/controls/src/main/resources/css/theme/light-theme.css` line 58 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/743#-NUS19tk0YGkzbzHXpiR:-NUS3vaq94vWTHS8Ztwq:bxbccxb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a44104fa36fcfb7413bc26b5e4eccf93d2ea45b1/jvm/controls/src/main/resources/css/theme/light-theme.css#L58)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

default regular text is dark blue color?
</blockquote></details>

from figma's style guide

**Comment by AnonymousWalker** [comment]
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/tableview/WorkbookOptionTableCell.kt` line 17 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/743#-NUS1szzECxpQqg-Ta5a:-NUS5xmC8QHw1Z6aubzG:bb7oryy) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/a44104fa36fcfb7413bc26b5e4eccf93d2ea45b1/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/tableview/WorkbookOptionTableCell.kt#L17)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I think css class should not have a property in its name. Why not just call it `icon` or `wa-icon`?
</blockquote></details>

sure

**Review by mXaln — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/743)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — APPROVED** [review]

**Pull request merged**
