### PR TITLE
Project Import dialog

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This import conflict dialog appears when importing a duplicated project

This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/763)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/763)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage2.kt` line 85 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/763#-NYwnho8BipI7YTemr8h:-NYwnho8BipI7YTemr8i:b-qzdppv) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c66ab6aea5cfd9d9c91b303d2823f262bb492164/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage2.kt#L85)):*
I think, there is no need to check if it's docked. According to this https://github.com/edvin/tornadofx-guide/blob/master/part2/EventBus.md

> Subscriptions inside UIComponents like View and Fragment are only active when that component is docked. That means that even if you have a View that has been previously initialized and used, event subscriptions will not reach it unless the View is docked inside a window or some other component.

**Comment by AnonymousWalker** [comment]
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage2.kt` line 85 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/763#-NYwnho8BipI7YTemr8h:-NYwrWRXB40RsSwsk9Ra:b-2ho8mb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/c66ab6aea5cfd9d9c91b303d2823f262bb492164/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage2.kt#L85)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I think, there is no need to check if it's docked. According to this https://github.com/edvin/tornadofx-guide/blob/master/part2/EventBus.md

> Subscriptions inside UIComponents like View and Fragment are only active when that component is docked. That means that even if you have a View that has been previously initialized and used, event subscriptions will not reach it unless the View is docked inside a window or some other component.
</blockquote></details>

Great idea! Thanks for the information

**Review by mXaln — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/763#-:-NYyBKpz-sMPPiQ_7dMf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AnonymousWalker)

**Pull request merged**
