### PR TITLE
Avoid dock/undock NarrationViewModel when plugin opened (OT-780)

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927)

### CODE REVIEW

**Review by mXaln — COMMENTED** [review]
This might lead to situations when audio files are locked (ex. on Windows machines), because we don't close connections to them when we open plugin. Does it work on Windows for you? Especially editing chapter take in external app.

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927#-:-Nl7hdMsCrUj4xqTITvA:bgau6sy)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by AnonymousWalker** [comment]
Yes, it doesn't have the issue because we provide the plugin either a chapter .wav file OR a verse temp file .pcm. These files are created from the original Narration .pcm file, so we don't use the working file directly. I made a few attempts and they worked.

When we open the plugin, the `PluginOpenedPage`view is docked which acts more or less like a "blocking modal" to prevent user interaction with Orature during this time. When we return, it should not reload everything like page navigation but rather dismiss the PluginOpenedPage and resume the current narration view.

**Review by mXaln — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927#-:-Nl8nTOiEi-UHv1K7tri:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AnonymousWalker)

**Comment by AnonymousWalker** [comment]
@jsarabia do you have any objection to this?

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927)* status: all files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 89 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927#-NlO6mBp6EYBHHir-l4r:-NlO6mBp6EYBHHir-l4s:baeoo0p) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f079575fa93c364ddc8cead95dc01579811b001c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L89)):*
> ```Kotlin
>     override fun onDock() {
>         super.onDock()
>         subscribeToEvents()
> ```

why don't you include subscribing to/unsubscribing from events with the dock and undock code which you don't wish to execute?

In other words, you could presumably leave them alone, and probably should so that it is consistent with the dock and undock?

If not, you have to state why, so someone doesn't come along and haphazardly reorder the code in order to "organize it."
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 98 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927#-NlO7JhmCH634IzIObN8:-NlO7JhmCH634IzIObN9:b-4oz2xz) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f079575fa93c364ddc8cead95dc01579811b001c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L98)):*
> ```Kotlin
>         narrationHeader.onDock()
>         audioWorkspaceView.onDock()
>         teleprompterView.onDock()
> ```

consider:

when (viewModel.pluginOpenedProperty.value) {
            // avoid resetting content, undo history, etc. when coming back from plugin
           true -> { viewModel.pluginOpenedProperty.set(false) 
           false -> {
               viewModel.onDock()
               narrationHeader.onDock()
               audioWorkspaceView.onDock()
               teleprompterView.onDock()
            }
}

In order to clearly communicate intention to diverge here, rather than using a return statement to ignore the rest of the code
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 107 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927#-NlO7nDj4w3J27MtNBQr:-NlO7nDj4w3J27MtNBQs:bnj7hl0) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f079575fa93c364ddc8cead95dc01579811b001c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L107)):*
> ```Kotlin
>             // avoid resetting content, undo history, etc. when coming back from plugin
>             return
>         }
> ```

same as above

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 89 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927#-NlO6mBp6EYBHHir-l4r:-NlODxy0EhIXsRHpwNoJ:b-bnj3uf) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f079575fa93c364ddc8cead95dc01579811b001c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L89)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why don't you include subscribing to/unsubscribing from events with the dock and undock code which you don't wish to execute?

In other words, you could presumably leave them alone, and probably should so that it is consistent with the dock and undock?

If not, you have to state why, so someone doesn't come along and haphazardly reorder the code in order to "organize it."
</blockquote></details>

I rewrite the comment to explicitly mention the "states", not the event bindings/subscriptions. Also, when a view is not docked, the events are not handled anyway. As a result, it does not matter if we include them or not.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 98 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927#-NlO7JhmCH634IzIObN8:-NlOCoDMC_NeddxnfR7I:b8ampny) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f079575fa93c364ddc8cead95dc01579811b001c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L98)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

consider:

when (viewModel.pluginOpenedProperty.value) {
            // avoid resetting content, undo history, etc. when coming back from plugin
           true -> { viewModel.pluginOpenedProperty.set(false) 
           false -> {
               viewModel.onDock()
               narrationHeader.onDock()
               audioWorkspaceView.onDock()
               teleprompterView.onDock()
            }
}

In order to clearly communicate intention to diverge here, rather than using a return statement to ignore the rest of the code
</blockquote></details>

great advice! This effectively prevents future issues thanks to the explicit branching.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt` line 107 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927#-NlO7nDj4w3J27MtNBQr:-NlODwgAEjaNQQF_6xeU:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f079575fa93c364ddc8cead95dc01579811b001c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationPage.kt#L107)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/927#-:-NlOjDyO90k8hz87bpNK:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
