### PR TITLE
Takes Page - Hightlight verses during playback

### PR DESCRIPTION
**Pull request by AnonymousWalker**
When a take is played, a corresponding verse is highlighted.

Each take has a marker model property to index the verses by its markers. The playback (SimpleAudioPlayer) slider of the take will update the index of the currently played verse based on the marker model.

image

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/564)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/564)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SimpleAudioPlayer.kt, line 173 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/564#-N0AxQQG60Zvr_Pvjf2t:-N0AxQQG60Zvr_Pvjf2u:b-8rstvi) ([raw file](https://github.com/bible-translation-tools/orature/blob/8daa2a10c20da91edb119a185e970ea7c1935646/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SimpleAudioPlayer.kt#L173)):*
> ```Kotlin
>         menuItems.setAll(createPlaybackRateMenu())
> 
>         slider.valueProperty().onChange {
> ```

I would use property and binding here. onChange creates anonymous listener that never gets deleted and can lead to memory leak.

`playbackProgressChangedProperty.bind(slider.valueProperty())`

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/564)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SimpleAudioPlayer.kt, line 173 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/564#-N0AxQQG60Zvr_Pvjf2t:-N0GzxVTB8Z8ONbvs_Zx:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/8daa2a10c20da91edb119a185e970ea7c1935646/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/media/SimpleAudioPlayer.kt#L173)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I would use property and binding here. onChange creates anonymous listener that never gets deleted and can lead to memory leak.

`playbackProgressChangedProperty.bind(slider.valueProperty())`
</blockquote></details>

Done.

**Review by mXaln — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/564)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Comment by OpThomasPrime1** [comment]
Verified by QA (Thomas Oliver) Windows, Linux, Apple

**Pull request merged**
