### PR TITLE
Allow controlling marker app with keyboard keys

### PR DESCRIPTION
**Pull request by mXaln**
Minimap player can be controlled by keys
Waveform can be controlled by keys
Placed markers can be moved by keys
Fixed slider bug

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/530)

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
I tried with an imported mp3 take and it crashed on exit. Initial thought: probably the added metadata `mp3agic.Mp3File ` causes the problem

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/530)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/controllers/AudioPlayerController.kt, line 237 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzFt-VG7CiApJXDaUPF:-MzFt-VG7CiApJXDaUPG:b-czkpv0) ([raw file](https://github.com/bible-translation-tools/orature/blob/051341a899aaaa35d05813ab2334e250e78b6411/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/controllers/AudioPlayerController.kt#L237)):*
> ```Kotlin
>     }
> 
>     private fun seekInterval(keyCode: KeyCode, fast: Boolean) {
> ```

Speed would best be done with an enum not boolean- it will make the code more readable
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerPlacementWaveform.kt, line 14 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzFtC3N52ImcqDXMcS8:-MzFtC3N52ImcqDXMcS9:b-eg2nz7) ([raw file](https://github.com/bible-translation-tools/orature/blob/051341a899aaaa35d05813ab2334e250e78b6411/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerPlacementWaveform.kt#L14)):*
> ```Kotlin
>     val markerStateProperty = SimpleObjectProperty<VerseMarkerModel>()
> 
>     var onSeekNext: () -> String? = {null}
> ```

why does this return a nullable string? This is a surprising return type for this kind of function
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/ScrollingWaveform.kt, line 15 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzFtLvv2M4v6cDd3_nn:-MzFtLvv2M4v6cDd3_no:bdkw717) ([raw file](https://github.com/bible-translation-tools/orature/blob/051341a899aaaa35d05813ab2334e250e78b6411/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/ScrollingWaveform.kt#L15)):*
> ```Kotlin
>     var onRewind: ((Boolean, (Boolean) -> Unit) -> Unit) = { _, _ ->}
>     var onFastForward: ((Boolean, (Boolean) -> Unit) -> Unit) = { _, _ ->}
>     var onToggleMedia: () -> Unit = {}
> ```

What are you trying to do here? We need to reduce the code complexity here because it is not at all obvious how to use this, and maintainability is going to be awful in a couple months.

Enums will probably help give some clarity over booleans, but the nested lambda is exceptionally confusing.
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrackControl.kt, line 248 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzFvQPt71CsiOa8VJx3:-MzFvQPt71CsiOa8VJx4:b-j4uxgv) ([raw file](https://github.com/bible-translation-tools/orature/blob/051341a899aaaa35d05813ab2334e250e78b6411/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrackControl.kt#L248)):*
> ```Kotlin
>             val percent = position / skinnable.width
>             val moveTo = if (code == KeyCode.LEFT) {
>                 percent - 0.001
> ```

can we name this constant?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/530)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/controllers/AudioPlayerController.kt, line 237 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzFt-VG7CiApJXDaUPF:-MzGLdmMDTVL294NB8aG:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/051341a899aaaa35d05813ab2334e250e78b6411/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/controllers/AudioPlayerController.kt#L237)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Speed would best be done with an enum not boolean- it will make the code more readable
</blockquote></details>

Done.
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/ScrollingWaveform.kt, line 15 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzFtLvv2M4v6cDd3_nn:-MzGLgdJ5gE10NOnhyC7:b-b230o6) ([raw file](https://github.com/bible-translation-tools/orature/blob/051341a899aaaa35d05813ab2334e250e78b6411/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/ScrollingWaveform.kt#L15)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

What are you trying to do here? We need to reduce the code complexity here because it is not at all obvious how to use this, and maintainability is going to be awful in a couple months.

Enums will probably help give some clarity over booleans, but the nested lambda is exceptionally confusing.
</blockquote></details>

The second parameter was the callback function. But, you're right, it looked too complicated. Refactored all.
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrackControl.kt, line 248 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzFvQPt71CsiOa8VJx3:-MzJkplIBVvvmBUPtCsu:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/051341a899aaaa35d05813ab2334e250e78b6411/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/layers/MarkerTrackControl.kt#L248)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can we name this constant?
</blockquote></details>

Done.
___
*[jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerPlacementWaveform.kt, line 14 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzFtC3N52ImcqDXMcS8:-MzJkxKm0Er3bHG86ZVo:bhai1s2) ([raw file](https://github.com/bible-translation-tools/orature/blob/051341a899aaaa35d05813ab2334e250e78b6411/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerPlacementWaveform.kt#L14)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why does this return a nullable string? This is a surprising return type for this kind of function
</blockquote></details>

It was returning the label of the marker that had been sought. I needed it in another function to focus the found marker. Refactored in a more simple way.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/530)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/controllers/AudioPlayerController.kt, line 257 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzKjqgQBemT9zN3tgyQ:-MzKjqgQBemT9zN3tgyR:bqbc0lh) ([raw file](https://github.com/bible-translation-tools/orature/blob/ac02b4a9ed4aa7d5b17339c8d3d6931abfb2851f/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/controllers/AudioPlayerController.kt#L257)):*
> ```Kotlin
>                 KeyCode.RIGHT -> location += interval
>             }
>             seek(Utils.clamp(0, location, player!!.getDurationInFrames()))
> ```

this could be it.getDurationInFrames() to make sure it's the same player in the ?.let block (and it is used in other places here), which would allow for removing the !!

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/530)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/controllers/AudioPlayerController.kt, line 257 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/530#-MzKjqgQBemT9zN3tgyQ:-MzKxB5K3aFYNIPadv3t:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/ac02b4a9ed4aa7d5b17339c8d3d6931abfb2851f/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/controllers/AudioPlayerController.kt#L257)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this could be it.getDurationInFrames() to make sure it's the same player in the ?.let block (and it is used in other places here), which would allow for removing the !!
</blockquote></details>

Done.

**Pull request merged**
