### PR TITLE
Mm save playback speed

### PR DESCRIPTION
**Pull request by jsarabia**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/495)

### CODE REVIEW

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/495)* status: 0 of 25 files reviewed, 2 unresolved discussions

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 62 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/495#-Mv5iKsTB3qNbziDGQ-k:-Mv5iKsTB3qNbziDGQ-l:bw4axa4) ([raw file](https://github.com/bible-translation-tools/orature/blob/2b6641c7e9a45dad97adf3527d2c9345701addcc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L62)):*
> ```Kotlin
> 
>     @Inject
>     lateinit var updateTranslationUseCase: UpdateTranslation
> ```

This shouldn't be in the wbds
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 65 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/495#-Mv5iNvcDiqrMAXzN6Wo:-Mv5iNvcDiqrMAXzN6Wp:b-ov82ed) ([raw file](https://github.com/bible-translation-tools/orature/blob/2b6641c7e9a45dad97adf3527d2c9345701addcc/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L65)):*
> ```Kotlin
> 
>     @Inject
>     lateinit var languageRepository: ILanguageRepository
> ```

This also shouldn't be in the wbds

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/495)* status: 0 of 29 files reviewed, 3 unresolved discussions

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/AssociatedTranslation.kt, line 7 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/495#-MvZEgQM8vHcrkyOKhZx:-MvZEgQM8vHcrkyOKhZy:bc9ao1h) ([raw file](https://github.com/bible-translation-tools/orature/blob/b067dd775a5715955314e49a65e7e32fcccdf06f/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/AssociatedTranslation.kt#L7)):*
> ```Kotlin
> class AssociatedTranslation(
>     val sourceRate: BehaviorRelay<Double>,
>     val targetRate: BehaviorRelay<Double>
> ```

The definition here can just use the Relay interface
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt, line 425 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/495#-MvZFH5A-WQGqjvNh8eT:-MvZFH5A-WQGqjvNh8eU:b-bwmhq4) ([raw file](https://github.com/bible-translation-tools/orature/blob/b067dd775a5715955314e49a65e7e32fcccdf06f/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L425)):*
> ```Kotlin
>                     .doOnError { e -> logger.error("Error in updating translation", e) }
>                     .subscribe()
>             }
> ```

The above code is effectively exactly the same; could you extract this out to a function?
___
*[common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt, line 357 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/495#-MvZFiCZ5ZQJcQuOcAwL:-MvZFiCZ5ZQJcQuOcAwM:b-odydgy) ([raw file](https://github.com/bible-translation-tools/orature/blob/b067dd775a5715955314e49a65e7e32fcccdf06f/common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt#L357)):*
> ```Kotlin
>                 )
>             )
>         )
> ```

Could you add a test here for getting a workbook, updating one of the rates, and verifying that got updated in the database?

**Review by mXaln — COMMENTED** [review]
> Reviewed 1 of 24 files at r1, 17 of 24 files at r2, 11 of 11 files at r3, 6 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/495)* status: all files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/AssociatedTranslation.kt, line 7 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/495#-MvZEgQM8vHcrkyOKhZx:-Mvciu0v-jlJr9t8oU-R:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b067dd775a5715955314e49a65e7e32fcccdf06f/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/AssociatedTranslation.kt#L7)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

The definition here can just use the Relay interface
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt, line 425 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/495#-MvZFH5A-WQGqjvNh8eT:-MvcaRkq7JUe0jxPSxI2:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b067dd775a5715955314e49a65e7e32fcccdf06f/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L425)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

The above code is effectively exactly the same; could you extract this out to a function?
</blockquote></details>

Done.
___
*[common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt, line 357 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/495#-MvZFiCZ5ZQJcQuOcAwL:-MvcdlKdEwbn_8YgH2ka:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b067dd775a5715955314e49a65e7e32fcccdf06f/common/src/test/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/TestWorkbookRepository.kt#L357)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Could you add a test here for getting a workbook, updating one of the rates, and verifying that got updated in the database?
</blockquote></details>

Done.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/495)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt, line 425 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/495#-MvZFH5A-WQGqjvNh8eT:-MvcpOku8rlKjU87xU3p:bgb89q8) ([raw file](https://github.com/bible-translation-tools/orature/blob/b067dd775a5715955314e49a65e7e32fcccdf06f/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L425)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There's still 8 duplicated lines; you can pass in a variable as to whether it's for source or target, since that's the only difference

**Review by mXaln — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/495)* status: 29 of 30 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt, line 425 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/495#-MvZFH5A-WQGqjvNh8eT:-MvcxjGk-wtkh1EJf4tE:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b067dd775a5715955314e49a65e7e32fcccdf06f/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L425)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

There's still 8 duplicated lines; you can pass in a variable as to whether it's for source or target, since that's the only difference
</blockquote></details>

Done.

**Review by jsarabia — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/495#-:-Mvd7cPM7KH6KLnq2qb5:bnfp4nl)* status: 29 of 30 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
