### PR TITLE
Fix crash when delete then create project (OT-797)

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Executes deletion in sequential order using a Queue. Since we have a timeout until the actual deletion executes, project creation during this time will be delayed until the delete operations finish.

This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/947)

### CODE REVIEW

**Review by mXaln — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/947)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AnonymousWalker)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/947)* status: all files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/collections/DeleteProject.kt` line 101 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/947#-Nn9VV2MEdbOgDftlLmU:-Nn9VV2MEdbOgDftlLmV:b20agsi) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/dd272af2d1384e5004c34d670204fc540aeb1a4d/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/collections/DeleteProject.kt#L101)):*
> ```Kotlin
>                 it.onComplete()
>             }
>             .subscribeOn(Schedulers.io())
> ```

What would actually be better than using a queue here would be to solve this by posting the work to run on a global, single-threaded event loop. This would allow the task to run in the background, but the single-threaded nature would provide the benefit of the queue.

Fortunately, such a construct already exists, so we don't need to create something ourselves.

Simply use Schedulers.single()
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/HomePageViewModel2.kt` line 167 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/947#-Nn9Rv1Z3cZll8TyoPaK:-Nn9Rv1Z3cZll8TyoPaL:b-8krkrf) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/dd272af2d1384e5004c34d670204fc540aeb1a4d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/HomePageViewModel2.kt#L167)):*
> ```Kotlin
>     fun deleteProjectGroupWithTimer(cardModel: ProjectGroupCardModel): Disposable {
>         val timeoutMillis = NOTIFICATION_DURATION_SEC * 1000
>         projectWizardViewModel.projectDeleteCounter.incrementAndGet()
> ```

the atomic int should be a private member variable, not a public API

so you'd want projectWizardViewModel.incrementDeletedProjects() or something like that.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/947)* status: all files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/collections/DeleteProject.kt` line 101 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/947#-Nn9VV2MEdbOgDftlLmU:-Nn9o7g-9wdeGeNue9ia:biipetq) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/dd272af2d1384e5004c34d670204fc540aeb1a4d/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/collections/DeleteProject.kt#L101)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

What would actually be better than using a queue here would be to solve this by posting the work to run on a global, single-threaded event loop. This would allow the task to run in the background, but the single-threaded nature would provide the benefit of the queue.

Fortunately, such a construct already exists, so we don't need to create something ourselves.

Simply use Schedulers.single()
</blockquote></details>

Yeah, I like that a lot more, thanks!
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/HomePageViewModel2.kt` line 167 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/947#-Nn9Rv1Z3cZll8TyoPaK:-Nn9oKJC2OawGcajQyzG:b-h43rl5) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/dd272af2d1384e5004c34d670204fc540aeb1a4d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/HomePageViewModel2.kt#L167)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

the atomic int should be a private member variable, not a public API

so you'd want projectWizardViewModel.incrementDeletedProjects() or something like that.
</blockquote></details>

Sounds good, done!

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/947#-:-NnA-ayY4mTe3arfrsnp:bnfp4nl)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
