### PR TITLE
Dark mode waveforms

### PR DESCRIPTION
**Pull request by darrellcolehill**
This change is [Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @darrellcolehill)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt` line 80 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145#-Nyfy0WD7zUzZLRVsgzn:-Nyfy0WE7wtOsQJ75i1K:b-7ok0t4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4bcf7b0df56a98f15182da0e1382b7338a792c41/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt#L80)):*
> ```Kotlin
>         viewModel.onUndockConsume()
>         unsubscribeEvents()
>         disposableListeners.forEach { it.dispose() }
> ```

You probably would prefer to use a CompositeDisposable here

Consider that once you dispose on the listener, the listener is still in the list.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt` line 80 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145#-Nyfy0WD7zUzZLRVsgzn:-NyfzCVHBbDx5XZFaRgG:b-fvu180) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4bcf7b0df56a98f15182da0e1382b7338a792c41/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt#L80)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

You probably would prefer to use a CompositeDisposable here

Consider that once you dispose on the listener, the listener is still in the list.
</blockquote></details>

it seems that CompositeDisposable only works with rx Observable/Disposable types. JavaFX's onChange() has a different disposer, thus we can't use that one

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt` line 80 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145#-Nyfy0WD7zUzZLRVsgzn:-Nyg26If27N9lDALOVwQ:bcqmnrr) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4bcf7b0df56a98f15182da0e1382b7338a792c41/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt#L80)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

it seems that CompositeDisposable only works with rx Observable/Disposable types. JavaFX's onChange() has a different disposer, thus we can't use that one
</blockquote></details>

Would calling appColorMode.toObservable() allow us to change disposableListeners to a CompositeDisposable?

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt` line 80 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145#-Nyfy0WD7zUzZLRVsgzn:-Nyz67wsEHDz2TJR-OgW:b-t1650) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cd62315c621fcce7e1d3c33a2d627fee5eb7c87f/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/Consume.kt#L80)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Would calling appColorMode.toObservable() allow us to change disposableListeners to a CompositeDisposable?
</blockquote></details>

Great finding! It seems to work as if we were using `ListenerDisposer` from onChangeWithDisposer()

**Review by AnonymousWalker — APPROVED** [review]

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, 1 of 2 files at r2, 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145)* status: 5 of 18 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @darrellcolehill)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/PeerEdit.kt` line 225 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145#-NzEmPiQ4vWpLVu49kTX:-NzEmPiQ4vWpLVu49kTY:bx45v71) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/064e4a66c9a34e65b6f14907f0c83a4e07707234/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/PeerEdit.kt#L225)):*
> ```Kotlin
>         }
> 
>         listenerDisposers.forEach { it.dispose() }
> ```

clear the list after calling dispose on each item

**Review by darrellcolehill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145)* status: 5 of 18 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/PeerEdit.kt` line 225 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145#-NzEmPiQ4vWpLVu49kTX:-NzFExT88sP38JfQmBKE:bebrt1w) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/064e4a66c9a34e65b6f14907f0c83a4e07707234/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/translation/PeerEdit.kt#L225)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

clear the list after calling dispose on each item
</blockquote></details>

Will do

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1145#-:-NzFGnkr9R0eWhk3gshD:bnfp4nl)* status: 5 of 18 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @darrellcolehill)

**Pull request merged**
